import Gtz.Certificates.CollarChartReplay

/-!
# Collar atlas kernel-replay certificate: barycentric order chart 23041

Generated by make_chart_certificate.py from the rung-15 atlas cdata
(chart_bary_23041_cdata.txt) and the adaptive coarsest cover emitted by
adaptive_emitter.c.  All data below is UNTRUSTED input to the verified
checker: `checkChart` re-derives every interval bound, re-verifies every
shift variant against its own reflection, and the covering is forced by
the checker's own split rule.  The single `decide` plus the generic
soundness theorem `checkChart_sound` yield the window sign package at
every rational point of the chart cube `(0,1]^4`.
-/

namespace Gtz.CollarReplay.Chart23041

open Gtz.CollarReplay

set_option maxRecDepth 200000
set_option maxHeartbeats 8000000

def chartCores : List Poly := [
  [tm 5 0 0 0 0 (1),
    tm 2 1 1 1 0 (1),
    tm 0 1 2 1 1 (-1)],
  [tm 5 0 0 0 0 (1),
    tm 3 1 0 1 0 (-1),
    tm 0 1 1 2 1 (-1)],
  [tm 4 0 0 0 0 (1),
    tm 1 0 1 1 1 (1),
    tm 0 1 2 1 0 (-1)],
  [tm 3 0 0 1 1 (1),
    tm 4 1 0 0 0 (-1),
    tm 0 1 1 2 1 (1)],
  [tm 5 0 0 0 0 (1),
    tm 4 0 1 0 0 (1),
    tm 3 0 1 1 0 (-1),
    tm 2 0 1 1 1 (1),
    tm 0 0 2 2 1 (-1)]
]

def chartVariants : List VariantEntry := [
  ⟨0, 5,
   [tm 5 0 0 0 0 (1),
    tm 4 0 1 0 0 (1),
    tm 3 0 1 1 0 (-1),
    tm 2 0 2 0 1 (-1),
    tm 1 0 2 1 1 (1),
    tm 3 1 1 0 0 (-1),
    tm 2 1 1 1 0 (1),
    tm 1 1 2 0 1 (1),
    tm 0 1 2 1 1 (-1)]⟩,
  ⟨0, 6,
   [tm 5 0 0 0 0 (1),
    tm 4 1 0 0 0 (1),
    tm 3 1 0 0 1 (-1),
    tm 3 1 0 1 0 (-1),
    tm 2 1 0 1 1 (1),
    tm 3 1 1 0 0 (-1),
    tm 2 1 1 0 1 (2),
    tm 2 1 1 1 0 (1),
    tm 1 1 1 1 1 (-2),
    tm 1 1 2 0 1 (-1),
    tm 0 1 2 1 1 (1)]⟩,
  ⟨0, 7,
   [tm 5 0 0 0 0 (2),
    tm 4 0 0 0 1 (-1),
    tm 4 0 0 1 0 (-1),
    tm 3 0 0 1 1 (1),
    tm 4 0 1 0 0 (-1),
    tm 3 0 1 0 1 (2),
    tm 3 0 1 1 0 (1),
    tm 2 0 1 1 1 (-2),
    tm 2 0 2 0 1 (-1),
    tm 1 0 2 1 1 (1),
    tm 4 1 0 0 0 (-1),
    tm 3 1 0 0 1 (1),
    tm 3 1 0 1 0 (1),
    tm 2 1 0 1 1 (-1),
    tm 3 1 1 0 0 (1),
    tm 2 1 1 0 1 (-2),
    tm 2 1 1 1 0 (-1),
    tm 1 1 1 1 1 (2),
    tm 1 1 2 0 1 (1),
    tm 0 1 2 1 1 (-1)]⟩,
  ⟨0, 9,
   [tm 5 0 0 0 0 (1),
    tm 3 0 1 1 0 (1),
    tm 2 0 2 1 0 (-1),
    tm 1 0 2 1 1 (1),
    tm 2 1 1 1 0 (-1),
    tm 1 1 2 1 0 (1),
    tm 0 1 2 1 1 (-1)]⟩,
  ⟨0, 10,
   [tm 5 0 0 0 0 (1),
    tm 2 1 0 1 1 (1),
    tm 2 1 1 1 0 (1),
    tm 1 1 1 1 1 (-2),
    tm 1 1 2 1 0 (-1),
    tm 0 1 2 1 1 (1)]⟩,
  ⟨0, 12,
   [tm 5 0 0 0 0 (1),
    tm 3 1 1 0 0 (1),
    tm 2 1 1 1 0 (-1),
    tm 2 1 2 0 0 (-1),
    tm 1 1 2 0 1 (1),
    tm 1 1 2 1 0 (1),
    tm 0 1 2 1 1 (-1)]⟩,
  ⟨0, 13,
   [tm 5 0 0 0 0 (1),
    tm 4 0 1 0 0 (1),
    tm 3 0 1 1 0 (-1),
    tm 3 0 2 0 0 (-1),
    tm 2 0 2 0 1 (1),
    tm 2 0 2 1 0 (1),
    tm 1 0 2 1 1 (-1),
    tm 3 1 1 0 0 (-1),
    tm 2 1 1 1 0 (1),
    tm 2 1 2 0 0 (1),
    tm 1 1 2 0 1 (-1),
    tm 1 1 2 1 0 (-1),
    tm 0 1 2 1 1 (1)]⟩,
  ⟨0, 14,
   [tm 5 0 0 0 0 (1),
    tm 3 1 0 0 1 (1),
    tm 2 1 0 1 1 (-1),
    tm 3 1 1 0 0 (1),
    tm 2 1 1 0 1 (-2),
    tm 2 1 1 1 0 (-1),
    tm 1 1 1 1 1 (2),
    tm 2 1 2 0 0 (-1),
    tm 1 1 2 0 1 (1),
    tm 1 1 2 1 0 (1),
    tm 0 1 2 1 1 (-1)]⟩,
  ⟨0, 15,
   [tm 5 0 0 0 0 (1),
    tm 4 0 0 0 1 (1),
    tm 3 0 0 1 1 (-1),
    tm 4 0 1 0 0 (1),
    tm 3 0 1 0 1 (-2),
    tm 3 0 1 1 0 (-1),
    tm 2 0 1 1 1 (2),
    tm 3 0 2 0 0 (-1),
    tm 2 0 2 0 1 (1),
    tm 2 0 2 1 0 (1),
    tm 1 0 2 1 1 (-1),
    tm 3 1 0 0 1 (-1),
    tm 2 1 0 1 1 (1),
    tm 3 1 1 0 0 (-1),
    tm 2 1 1 0 1 (2),
    tm 2 1 1 1 0 (1),
    tm 1 1 1 1 1 (-2),
    tm 2 1 2 0 0 (1),
    tm 1 1 2 0 1 (-1),
    tm 1 1 2 1 0 (-1),
    tm 0 1 2 1 1 (1)]⟩,
  ⟨1, 6,
   [tm 5 0 0 0 0 (1),
    tm 4 1 0 0 0 (-1),
    tm 3 1 0 0 1 (-1),
    tm 3 1 0 1 0 (1),
    tm 2 1 0 1 1 (2),
    tm 1 1 0 2 1 (-1),
    tm 2 1 1 0 1 (1),
    tm 1 1 1 1 1 (-2),
    tm 0 1 1 2 1 (1)]⟩,
  ⟨1, 7,
   [tm 4 0 0 0 1 (-1),
    tm 4 0 0 1 0 (1),
    tm 3 0 0 1 1 (2),
    tm 2 0 0 2 1 (-1),
    tm 3 0 1 0 1 (1),
    tm 2 0 1 1 1 (-2),
    tm 1 0 1 2 1 (1),
    tm 4 1 0 0 0 (1),
    tm 3 1 0 0 1 (1),
    tm 3 1 0 1 0 (-1),
    tm 2 1 0 1 1 (-2),
    tm 1 1 0 2 1 (1),
    tm 2 1 1 0 1 (-1),
    tm 1 1 1 1 1 (2),
    tm 0 1 1 2 1 (-1)]⟩,
  ⟨1, 9,
   [tm 5 0 0 0 0 (1),
    tm 4 0 0 1 0 (-1),
    tm 2 0 1 2 0 (-1),
    tm 1 0 1 2 1 (1),
    tm 3 1 0 1 0 (1),
    tm 1 1 1 2 0 (1),
    tm 0 1 1 2 1 (-1)]⟩,
  ⟨1, 10,
   [tm 5 0 0 0 0 (1),
    tm 3 1 0 1 0 (-1),
    tm 2 1 0 2 0 (-1),
    tm 1 1 0 2 1 (1),
    tm 1 1 1 2 0 (1),
    tm 0 1 1 2 1 (-1)]⟩,
  ⟨1, 12,
   [tm 5 0 0 0 0 (1),
    tm 4 1 0 0 0 (-1),
    tm 3 1 0 1 0 (1),
    tm 3 1 1 0 0 (-1),
    tm 2 1 1 0 1 (1),
    tm 2 1 1 1 0 (2),
    tm 1 1 1 1 1 (-2),
    tm 1 1 1 2 0 (-1),
    tm 0 1 1 2 1 (1)]⟩,
  ⟨1, 14,
   [tm 5 0 0 0 0 (1),
    tm 4 1 0 0 0 (-2),
    tm 3 1 0 0 1 (1),
    tm 3 1 0 1 0 (3),
    tm 2 1 0 1 1 (-2),
    tm 2 1 0 2 0 (-1),
    tm 1 1 0 2 1 (1),
    tm 3 1 1 0 0 (1),
    tm 2 1 1 0 1 (-1),
    tm 2 1 1 1 0 (-2),
    tm 1 1 1 1 1 (2),
    tm 1 1 1 2 0 (1),
    tm 0 1 1 2 1 (-1)]⟩,
  ⟨1, 15,
   [tm 5 0 0 0 0 (-1),
    tm 4 0 0 0 1 (1),
    tm 4 0 0 1 0 (3),
    tm 3 0 0 1 1 (-2),
    tm 3 0 0 2 0 (-1),
    tm 2 0 0 2 1 (1),
    tm 4 0 1 0 0 (1),
    tm 3 0 1 0 1 (-1),
    tm 3 0 1 1 0 (-2),
    tm 2 0 1 1 1 (2),
    tm 2 0 1 2 0 (1),
    tm 1 0 1 2 1 (-1),
    tm 4 1 0 0 0 (2),
    tm 3 1 0 0 1 (-1),
    tm 3 1 0 1 0 (-3),
    tm 2 1 0 1 1 (2),
    tm 2 1 0 2 0 (1),
    tm 1 1 0 2 1 (-1),
    tm 3 1 1 0 0 (-1),
    tm 2 1 1 0 1 (1),
    tm 2 1 1 1 0 (2),
    tm 1 1 1 1 1 (-2),
    tm 1 1 1 2 0 (-1),
    tm 0 1 1 2 1 (1)]⟩,
  ⟨2, 5,
   [tm 4 0 0 0 0 (1),
    tm 2 0 1 0 1 (1),
    tm 1 0 1 1 1 (-1),
    tm 2 0 2 0 0 (-1),
    tm 1 0 2 1 0 (1),
    tm 1 1 2 0 0 (1),
    tm 0 1 2 1 0 (-1)]⟩,
  ⟨2, 11,
   [tm 4 0 0 0 0 (1),
    tm 2 0 0 1 1 (-1),
    tm 2 0 1 1 0 (1),
    tm 1 0 1 1 1 (1),
    tm 1 0 2 1 0 (-1),
    tm 2 1 0 1 0 (1),
    tm 1 1 1 1 0 (-2),
    tm 0 1 2 1 0 (1)]⟩,
  ⟨2, 13,
   [tm 4 0 0 0 0 (1),
    tm 3 0 1 0 0 (1),
    tm 2 0 1 0 1 (-1),
    tm 2 0 1 1 0 (-1),
    tm 1 0 1 1 1 (1),
    tm 2 0 2 0 0 (-1),
    tm 1 0 2 1 0 (1),
    tm 1 1 2 0 0 (1),
    tm 0 1 2 1 0 (-1)]⟩,
  ⟨3, 11,
   [tm 5 0 0 0 0 (-1),
    tm 4 0 0 1 0 (1),
    tm 3 0 0 1 1 (-1),
    tm 3 0 0 2 0 (1),
    tm 2 0 0 2 1 (-1),
    tm 2 0 1 2 0 (-1),
    tm 1 0 1 2 1 (1),
    tm 4 1 0 0 0 (1),
    tm 2 1 0 2 0 (-1),
    tm 1 1 0 2 1 (1),
    tm 1 1 1 2 0 (1),
    tm 0 1 1 2 1 (-1)]⟩,
  ⟨4, 5,
   [tm 5 0 0 0 0 (1),
    tm 3 0 1 0 1 (1),
    tm 3 0 1 1 0 (1),
    tm 2 0 1 1 1 (-1),
    tm 2 0 2 0 1 (-1),
    tm 1 0 2 1 1 (2),
    tm 0 0 2 2 1 (-1)]⟩,
  ⟨4, 13,
   [tm 5 0 0 0 0 (1),
    tm 4 0 1 0 0 (1),
    tm 3 0 1 0 1 (-1),
    tm 2 0 1 1 1 (1),
    tm 3 0 2 0 0 (-1),
    tm 2 0 2 0 1 (1),
    tm 2 0 2 1 0 (2),
    tm 1 0 2 1 1 (-2),
    tm 1 0 2 2 0 (-1),
    tm 0 0 2 2 1 (1)]⟩
]

def chartThresholds : List ThresholdData := [
  ⟨⟨-1, []⟩,
    ⟨-1, []⟩,
    ⟨1, []⟩,
    ⟨1, []⟩,
    ⟨0, []⟩,
    ⟨1, []⟩⟩
]

def chartCandidates : List CandidateData := [
  -- T01567
  ⟨[⟨-1, []⟩,
      ⟨-1, [⟨1, 1⟩]⟩,
      ⟨-1, [⟨0, 1⟩]⟩,
      ⟨-1, []⟩,
      ⟨-1, []⟩],
    ⟨1, []⟩,
    [⟨1, []⟩]⟩,
  -- T04567
  ⟨[⟨-1, []⟩,
      ⟨1, [⟨1, 1⟩]⟩,
      ⟨-1, [⟨0, 1⟩]⟩,
      ⟨-1, []⟩,
      ⟨-1, []⟩],
    ⟨-1, []⟩,
    [⟨-1, []⟩]⟩,
  -- T13456
  ⟨[⟨1, [⟨3, 1⟩]⟩,
      ⟨-1, []⟩,
      ⟨-1, []⟩,
      ⟨-1, []⟩,
      ⟨-1, [⟨2, 1⟩]⟩],
    ⟨1, []⟩,
    [⟨1, []⟩]⟩,
  -- T14567
  ⟨[⟨-1, []⟩,
      ⟨-1, []⟩,
      ⟨-1, [⟨0, 1⟩]⟩,
      ⟨-1, [⟨2, 1⟩]⟩,
      ⟨-1, []⟩],
    ⟨-1, []⟩,
    [⟨-1, [⟨4, 1⟩]⟩]⟩,
  -- T34567
  ⟨[⟨-1, []⟩,
      ⟨-1, []⟩,
      ⟨-1, []⟩,
      ⟨-1, [⟨2, 1⟩]⟩,
      ⟨-1, [⟨3, 1⟩]⟩],
    ⟨-1, []⟩,
    [⟨-1, []⟩]⟩
]

def chartCover : CoverTree :=
  (.node 0
    (.node 1
      (.leaf (.guardPair 0 0 1 0 1))
      (.node 2
        (.leaf (.windowWin 0 0))
        (.node 3
          (.leaf (.windowWin 0 0))
          (.leaf (.guardPair 0 0 1 0 1))        )      )    )
    (.node 1
      (.node 2
        (.leaf (.windowWin 0 0))
        (.node 3
          (.leaf (.windowWin 3 0))
          (.leaf (.windowWin 3 0))        )      )
      (.node 2
        (.leaf (.guardPair 4 0 2 0 3))
        (.node 3
          (.node 0
            (.leaf (.guardPair 0 0 1 0 1))
            (.node 1
              (.leaf (.windowWin 3 0))
              (.leaf (.guardPair 0 0 1 0 1))            )          )
          (.node 0
            (.leaf (.guardPair 0 0 1 0 1))
            (.node 1
              (.leaf (.windowWin 3 0))
              (.leaf (.guardPair 0 0 1 0 1))            )          )        )      )    )  )

def chartData : ChartData :=
  ⟨chartCores, chartVariants, chartThresholds, chartCandidates,
   chartCover⟩

/-- The replayed check: one kernel evaluation of the whole certificate. -/
theorem chartCheckPasses : checkChart chartData = true := by decide

/-- KERNEL-CHECKED: the collar window sign package holds at every
rational point of this chart's half-open cube. -/
theorem chartWindowCertified (den one two three four : Int)
    (domain : PointLiesInDomain den one two three four) :
    WindowWitnessAt chartData den one two three four :=
  checkChart_sound chartData chartCheckPasses den one two three four
    domain

#print axioms chartWindowCertified

end Gtz.CollarReplay.Chart23041
