/-
Copyright (c) 2026 Grigory Evko. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Gtz.Design.ComplementPairCriterion
import Gtz.Design.GaugeWallKernelLaw

/-!
# The complement block on the gauge wall

The full-selection inverse looks complicated in ambient coordinates, but the
rank-one gauge wall removes the axis component of every triangle direction.
The remaining inverse problem is the weighted triangle Laplacian. This module
solves that system without dividing by its determinant and then spends the
solution in the complement form.

The main consequences are:

* `kFourGaugeWall_triangle_inverse_block` gives all six entries of the inverse
  form on the triangle labels after multiplication by the positive Laplacian
  denominator;
* `kFourGaugeWall_triangle_complement_block_scaled` shows that the entire
  triangle principal block of the complement matrix is a positive scalar times
  the signed rank-one matrix generated by `(1, -1, 1)`;
* `kFourGaugeWall_posDef_compl_triangle_star_iff` reduces each of the nine
  triangle-star card-four candidates to its single strict pair-minor inequality;
* `kFourGaugeWall_not_posDef_compl_triangle_pair` rules out every card-four
  selection omitting two triangle labels.

Thus the complement form recovers the gauge-wall rank obstruction and isolates
exactly the nine live triangle-star omissions in one coordinate-free calculation.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

namespace Gtz

open Matrix

private theorem triangleSystem_solve
    {a b c x0 x1 x2 y0 y1 : ℝ}
    (hrel : x1 = x0 + x2)
    (hzero : a * x0 + b * x1 = y0)
    (hone : -a * x0 + c * x2 = y1) :
    (a * b + a * c + b * c) * x0 = c * y0 - b * y1 ∧
      (a * b + a * c + b * c) * x1 = (a + c) * y0 + a * y1 ∧
      (a * b + a * c + b * c) * x2 = a * y0 + (a + b) * y1 := by
  subst x1
  constructor
  · linear_combination c * hzero - b * hone
  constructor
  · linear_combination (a + c) * hzero + a * hone
  · linear_combination a * hzero + (a + b) * hone

private theorem kFourGaugeWall_axis_inverse_triangle_zero
    (point : DirectionChartPoint 6) (axis : Fin 3 → ℝ) (scale : ℝ)
    (hscale : 0 < scale)
    (hwall : directionChartGap kFourDirection point.mass point.weight
      ({3, 4, 5} : Finset (Fin 6)) = scale • atomMatrix axis)
    (haxisSum : axis ⬝ᵥ kFourAllOnes ≠ 0) (triangle : Fin 6)
    (htriangle : triangle ∈ kFourTriangleLabels) :
    axis ⬝ᵥ ((directionChartGap kFourDirection point.mass point.weight
      Finset.univ)⁻¹ *ᵥ kFourDirection triangle) = 0 := by
  have haxisInv := kFourGaugeWall_inv_mulVec_axis point axis scale hwall
  have hread := congrArg (fun vec => kFourDirection triangle ⬝ᵥ vec) haxisInv
  rw [dotProduct_smul, smul_eq_mul] at hread
  have htriOnes : kFourDirection triangle ⬝ᵥ kFourAllOnes = 0 := by
    revert htriangle
    fin_cases triangle <;>
      simp [kFourTriangleLabels, kFourDirection, kFourAllOnes, dotProduct,
        Fin.sum_univ_three]
  rw [htriOnes] at hread
  have hfactor : scale * (axis ⬝ᵥ kFourAllOnes) ≠ 0 :=
    mul_ne_zero hscale.ne' haxisSum
  have hrightZero : kFourDirection triangle ⬝ᵥ
      ((directionChartGap kFourDirection point.mass point.weight Finset.univ)⁻¹
        *ᵥ axis) = 0 := by
    exact (mul_eq_zero.mp hread).resolve_left hfactor
  have hinvSymm :
      ((directionChartGap kFourDirection point.mass point.weight Finset.univ)⁻¹)ᵀ
        = (directionChartGap kFourDirection point.mass point.weight Finset.univ)⁻¹ := by
    rw [Matrix.transpose_nonsing_inv,
      directionChartGap_transpose kFourDirection point.mass point.weight Finset.univ]
  rw [dotProduct_mulVec_comm_of_transpose_eq hinvSymm]
  exact hrightZero

private theorem kFourGaugeWall_triangle_inverse_system
    (point : DirectionChartPoint 6) (axis : Fin 3 → ℝ) (scale : ℝ)
    (hscale : 0 < scale)
    (hwall : directionChartGap kFourDirection point.mass point.weight
      ({3, 4, 5} : Finset (Fin 6)) = scale • atomMatrix axis)
    (haxisSum : axis ⬝ᵥ kFourAllOnes ≠ 0) (triangle : Fin 6)
    (htriangle : triangle ∈ kFourTriangleLabels) :
    let q := (directionChartGap kFourDirection point.mass point.weight
      Finset.univ)⁻¹ *ᵥ kFourDirection triangle
    let a := point.mass 0 / point.weight 0
    let b := point.mass 1 / point.weight 1
    let c := point.mass 2 / point.weight 2
    a * (kFourDirection 0 ⬝ᵥ q) + b * (kFourDirection 1 ⬝ᵥ q)
        = kFourDirection triangle 0 ∧
      -a * (kFourDirection 0 ⬝ᵥ q) + c * (kFourDirection 2 ⬝ᵥ q)
        = kFourDirection triangle 1 := by
  dsimp only
  let gapU := directionChartGap kFourDirection point.mass point.weight Finset.univ
  let q := gapU⁻¹ *ᵥ kFourDirection triangle
  change
    point.mass 0 / point.weight 0 * (kFourDirection 0 ⬝ᵥ q) +
        point.mass 1 / point.weight 1 * (kFourDirection 1 ⬝ᵥ q) =
          kFourDirection triangle 0 ∧
      -(point.mass 0 / point.weight 0) * (kFourDirection 0 ⬝ᵥ q) +
        point.mass 2 / point.weight 2 * (kFourDirection 2 ⬝ᵥ q) =
          kFourDirection triangle 1
  have hpd := posDef_directionChartGap_univ point
  have hunit : IsUnit gapU.det := isUnit_iff_ne_zero.mpr (ne_of_gt hpd.det_pos)
  have hback : gapU *ᵥ q = kFourDirection triangle := by
    dsimp only [q]
    rw [Matrix.mulVec_mulVec, Matrix.mul_nonsing_inv _ hunit, Matrix.one_mulVec]
  have haxisZero := kFourGaugeWall_axis_inverse_triangle_zero point axis scale hscale
    hwall haxisSum triangle htriangle
  change axis ⬝ᵥ q = 0 at haxisZero
  rw [show gapU = scale • atomMatrix axis
      + ((point.mass 0 / point.weight 0) • atomMatrix (kFourDirection 0)
        + ((point.mass 1 / point.weight 1) • atomMatrix (kFourDirection 1)
          + (point.mass 2 / point.weight 2) • atomMatrix (kFourDirection 2))) from
      kFourGaugeWall_univ_eq point axis scale hwall,
    Matrix.add_mulVec, Matrix.add_mulVec, Matrix.add_mulVec,
    Matrix.smul_mulVec, Matrix.smul_mulVec, Matrix.smul_mulVec, Matrix.smul_mulVec,
    atomMatrix_mulVec_eq_smul, atomMatrix_mulVec_eq_smul,
    atomMatrix_mulVec_eq_smul, atomMatrix_mulVec_eq_smul,
    haxisZero, smul_smul, mul_zero, zero_smul, zero_add] at hback
  simp only [smul_smul] at hback
  constructor
  · have := congrFun hback 0
    simpa [kFourDirection, Pi.add_apply, Pi.smul_apply, smul_eq_mul] using this
  · have := congrFun hback 1
    simp only [kFourDirection, Pi.add_apply, Pi.smul_apply, smul_eq_mul,
      dotProduct, Fin.sum_univ_three, Matrix.cons_val_zero, Matrix.cons_val_one,
      Matrix.head_cons, Matrix.cons_val_two, Matrix.tail_cons] at this ⊢
    linear_combination this

theorem kFourGaugeWall_triangle_inverse_form_zero
    (point : DirectionChartPoint 6) (axis : Fin 3 → ℝ) (scale : ℝ)
    (hscale : 0 < scale)
    (hwall : directionChartGap kFourDirection point.mass point.weight
      ({3, 4, 5} : Finset (Fin 6)) = scale • atomMatrix axis)
    (haxisSum : axis ⬝ᵥ kFourAllOnes ≠ 0) :
    let a := point.mass 0 / point.weight 0
    let b := point.mass 1 / point.weight 1
    let c := point.mass 2 / point.weight 2
    let delta := a * b + a * c + b * c
    delta * (kFourDirection 0 ⬝ᵥ
      ((directionChartGap kFourDirection point.mass point.weight Finset.univ)⁻¹
        *ᵥ kFourDirection 0)) = b + c := by
  dsimp only
  let q := (directionChartGap kFourDirection point.mass point.weight Finset.univ)⁻¹
    *ᵥ kFourDirection 0
  change
    (point.mass 0 / point.weight 0 * (point.mass 1 / point.weight 1) +
        point.mass 0 / point.weight 0 * (point.mass 2 / point.weight 2) +
        point.mass 1 / point.weight 1 * (point.mass 2 / point.weight 2)) *
      (kFourDirection 0 ⬝ᵥ q) =
        point.mass 1 / point.weight 1 + point.mass 2 / point.weight 2
  obtain ⟨hzero, hone⟩ := kFourGaugeWall_triangle_inverse_system point axis scale hscale
    hwall haxisSum 0 (by decide)
  change _ = _ at hzero hone ⊢
  have hrel : kFourDirection 1 ⬝ᵥ q
      = (kFourDirection 0 ⬝ᵥ q) + (kFourDirection 2 ⬝ᵥ q) := by
    simp only [kFourDirection, dotProduct, Fin.sum_univ_three, Matrix.cons_val_zero,
      Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_two, Matrix.tail_cons]
    ring
  have hsolve := triangleSystem_solve hrel hzero hone
  simpa [kFourDirection, add_comm] using hsolve.1

private theorem kFourGaugeWall_triangle_inverse_form_system
    (point : DirectionChartPoint 6) (axis : Fin 3 → ℝ) (scale : ℝ)
    (hscale : 0 < scale)
    (hwall : directionChartGap kFourDirection point.mass point.weight
      ({3, 4, 5} : Finset (Fin 6)) = scale • atomMatrix axis)
    (haxisSum : axis ⬝ᵥ kFourAllOnes ≠ 0) (triangle : Fin 6)
    (htriangle : triangle ∈ kFourTriangleLabels) :
    let a := point.mass 0 / point.weight 0
    let b := point.mass 1 / point.weight 1
    let c := point.mass 2 / point.weight 2
    let delta := a * b + a * c + b * c
    let inv := (directionChartGap kFourDirection point.mass point.weight Finset.univ)⁻¹
    delta * (kFourDirection 0 ⬝ᵥ (inv *ᵥ kFourDirection triangle)) =
        c * kFourDirection triangle 0 - b * kFourDirection triangle 1 ∧
      delta * (kFourDirection 1 ⬝ᵥ (inv *ᵥ kFourDirection triangle)) =
        (a + c) * kFourDirection triangle 0 + a * kFourDirection triangle 1 ∧
      delta * (kFourDirection 2 ⬝ᵥ (inv *ᵥ kFourDirection triangle)) =
        a * kFourDirection triangle 0 + (a + b) * kFourDirection triangle 1 := by
  dsimp only
  let q := (directionChartGap kFourDirection point.mass point.weight Finset.univ)⁻¹
    *ᵥ kFourDirection triangle
  change
    _ * (kFourDirection 0 ⬝ᵥ q) = _ ∧
      _ * (kFourDirection 1 ⬝ᵥ q) = _ ∧
      _ * (kFourDirection 2 ⬝ᵥ q) = _
  obtain ⟨hzero, hone⟩ := kFourGaugeWall_triangle_inverse_system point axis scale hscale
    hwall haxisSum triangle htriangle
  change _ = _ at hzero hone
  have hrel : kFourDirection 1 ⬝ᵥ q
      = (kFourDirection 0 ⬝ᵥ q) + (kFourDirection 2 ⬝ᵥ q) := by
    simp only [kFourDirection, dotProduct, Fin.sum_univ_three, Matrix.cons_val_zero,
      Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_two, Matrix.tail_cons]
    ring
  exact triangleSystem_solve hrel hzero hone

theorem kFourGaugeWall_triangle_inverse_block
    (point : DirectionChartPoint 6) (axis : Fin 3 → ℝ) (scale : ℝ)
    (hscale : 0 < scale)
    (hwall : directionChartGap kFourDirection point.mass point.weight
      ({3, 4, 5} : Finset (Fin 6)) = scale • atomMatrix axis)
    (haxisSum : axis ⬝ᵥ kFourAllOnes ≠ 0) :
    let a := point.mass 0 / point.weight 0
    let b := point.mass 1 / point.weight 1
    let c := point.mass 2 / point.weight 2
    let delta := a * b + a * c + b * c
    let inv := (directionChartGap kFourDirection point.mass point.weight Finset.univ)⁻¹
    delta * (kFourDirection 0 ⬝ᵥ (inv *ᵥ kFourDirection 0)) = b + c ∧
      delta * (kFourDirection 0 ⬝ᵥ (inv *ᵥ kFourDirection 1)) = c ∧
      delta * (kFourDirection 0 ⬝ᵥ (inv *ᵥ kFourDirection 2)) = -b ∧
      delta * (kFourDirection 1 ⬝ᵥ (inv *ᵥ kFourDirection 1)) = a + c ∧
      delta * (kFourDirection 1 ⬝ᵥ (inv *ᵥ kFourDirection 2)) = a ∧
      delta * (kFourDirection 2 ⬝ᵥ (inv *ᵥ kFourDirection 2)) = a + b := by
  dsimp only
  have hzero := kFourGaugeWall_triangle_inverse_form_system point axis scale hscale hwall
    haxisSum 0 (by decide)
  have hone := kFourGaugeWall_triangle_inverse_form_system point axis scale hscale hwall
    haxisSum 1 (by decide)
  have htwo := kFourGaugeWall_triangle_inverse_form_system point axis scale hscale hwall
    haxisSum 2 (by decide)
  dsimp only at hzero hone htwo
  simp [kFourDirection] at hzero hone htwo ⊢
  constructor
  · linarith [hzero.1]
  constructor
  · linarith [hone.1]
  constructor
  · linarith [htwo.1]
  constructor
  · linarith [hone.2.1]
  constructor
  · linarith [htwo.2.1]
  · linarith [htwo.2.2]

theorem kFourGaugeWall_triangle_complement_block_scaled
    (point : DirectionChartPoint 6) (axis : Fin 3 → ℝ) (scale : ℝ)
    (hscale : 0 < scale)
    (hwall : directionChartGap kFourDirection point.mass point.weight
      ({3, 4, 5} : Finset (Fin 6)) = scale • atomMatrix axis)
    (haxisSum : axis ⬝ᵥ kFourAllOnes ≠ 0) :
    let a := point.mass 0 / point.weight 0
    let b := point.mass 1 / point.weight 1
    let c := point.mass 2 / point.weight 2
    let delta := a * b + a * c + b * c
    let entry := complementMatrixEntry kFourDirection point.mass point.weight
    delta * entry 0 0 = a * b * c ∧
      delta * entry 0 1 = -(a * b * c) ∧
      delta * entry 0 2 = a * b * c ∧
      delta * entry 1 1 = a * b * c ∧
      delta * entry 1 2 = -(a * b * c) ∧
      delta * entry 2 2 = a * b * c := by
  dsimp only
  have hblock := kFourGaugeWall_triangle_inverse_block point axis scale hscale hwall haxisSum
  dsimp only at hblock
  simp only [complementMatrixEntry, fullInverseForm, if_pos, if_neg (by decide : (0 : Fin 6) ≠ 1),
    if_neg (by decide : (0 : Fin 6) ≠ 2), if_neg (by decide : (1 : Fin 6) ≠ 2)]
  constructor
  · linear_combination
      -(point.mass 0 / point.weight 0) ^ 2 * hblock.1
  constructor
  · linear_combination
      -(point.mass 0 / point.weight 0) * (point.mass 1 / point.weight 1) * hblock.2.1
  constructor
  · linear_combination
      -(point.mass 0 / point.weight 0) * (point.mass 2 / point.weight 2) * hblock.2.2.1
  constructor
  · linear_combination
      -(point.mass 1 / point.weight 1) ^ 2 * hblock.2.2.2.1
  constructor
  · linear_combination
      -(point.mass 1 / point.weight 1) * (point.mass 2 / point.weight 2) *
        hblock.2.2.2.2.1
  · linear_combination
      -(point.mass 2 / point.weight 2) ^ 2 * hblock.2.2.2.2.2

private theorem pairFormDiag_eq_complementMatrixEntry_self
    {size : ℕ} (direction : Fin size → (Fin 3 → ℝ))
    (mass weight : Fin size → ℝ) (i : Fin size) :
    pairFormDiag direction mass weight i =
      complementMatrixEntry direction mass weight i i := by
  simp only [pairFormDiag, complementMatrixEntry, if_pos, fullPivot]
  ring

private theorem pairFormCross_sq_eq_complementMatrixEntry_sq
    {size : ℕ} (direction : Fin size → (Fin 3 → ℝ))
    (mass weight : Fin size → ℝ) {i j : Fin size} (hij : i ≠ j) :
    pairFormCross direction mass weight i j ^ 2 =
      complementMatrixEntry direction mass weight i j ^ 2 := by
  simp only [pairFormCross, complementMatrixEntry, if_neg hij]
  ring

private theorem complementMatrixEntry_comm_of_posDef
    {size : ℕ} (direction : Fin size → (Fin 3 → ℝ))
    (mass weight : Fin size → ℝ)
    (huniv : (directionChartGap direction mass weight Finset.univ).PosDef)
    (i j : Fin size) :
    complementMatrixEntry direction mass weight i j =
      complementMatrixEntry direction mass weight j i := by
  by_cases hij : i = j
  · subst j
    rfl
  · have hji : j ≠ i := Ne.symm hij
    simp only [complementMatrixEntry, if_neg hij, if_neg hji,
      fullInverseForm_comm direction mass weight huniv i j]
    ring

theorem kFourGaugeWall_triangle_complement_diag_pos
    (point : DirectionChartPoint 6) (axis : Fin 3 → ℝ) (scale : ℝ)
    (hscale : 0 < scale)
    (hwall : directionChartGap kFourDirection point.mass point.weight
      ({3, 4, 5} : Finset (Fin 6)) = scale • atomMatrix axis)
    (haxisSum : axis ⬝ᵥ kFourAllOnes ≠ 0) (triangle : Fin 6)
    (htriangle : triangle ∈ kFourTriangleLabels) :
    0 < complementMatrixEntry kFourDirection point.mass point.weight
      triangle triangle := by
  have ha : 0 < point.mass 0 / point.weight 0 :=
    div_pos (point.mass_pos 0) (point.weight_pos 0)
  have hb : 0 < point.mass 1 / point.weight 1 :=
    div_pos (point.mass_pos 1) (point.weight_pos 1)
  have hc : 0 < point.mass 2 / point.weight 2 :=
    div_pos (point.mass_pos 2) (point.weight_pos 2)
  have hdelta : 0 <
      point.mass 0 / point.weight 0 * (point.mass 1 / point.weight 1) +
        point.mass 0 / point.weight 0 * (point.mass 2 / point.weight 2) +
        point.mass 1 / point.weight 1 * (point.mass 2 / point.weight 2) := by
    positivity
  have hcommon : 0 < point.mass 0 / point.weight 0 *
      (point.mass 1 / point.weight 1) * (point.mass 2 / point.weight 2) := by
    positivity
  have hblock := kFourGaugeWall_triangle_complement_block_scaled point axis scale hscale
    hwall haxisSum
  dsimp only at hblock
  have hcases : triangle = 0 ∨ triangle = 1 ∨ triangle = 2 := by
    simpa [kFourTriangleLabels] using htriangle
  rcases hcases with rfl | rfl | rfl
  · have hprod : 0 <
        (point.mass 0 / point.weight 0 * (point.mass 1 / point.weight 1) +
            point.mass 0 / point.weight 0 * (point.mass 2 / point.weight 2) +
            point.mass 1 / point.weight 1 * (point.mass 2 / point.weight 2)) *
          complementMatrixEntry kFourDirection point.mass point.weight 0 0 := by
      rw [hblock.1]
      exact hcommon
    exact pos_of_mul_pos_right hprod hdelta.le
  · have hprod : 0 <
        (point.mass 0 / point.weight 0 * (point.mass 1 / point.weight 1) +
            point.mass 0 / point.weight 0 * (point.mass 2 / point.weight 2) +
            point.mass 1 / point.weight 1 * (point.mass 2 / point.weight 2)) *
          complementMatrixEntry kFourDirection point.mass point.weight 1 1 := by
      rw [hblock.2.2.2.1]
      exact hcommon
    exact pos_of_mul_pos_right hprod hdelta.le
  · have hprod : 0 <
        (point.mass 0 / point.weight 0 * (point.mass 1 / point.weight 1) +
            point.mass 0 / point.weight 0 * (point.mass 2 / point.weight 2) +
            point.mass 1 / point.weight 1 * (point.mass 2 / point.weight 2)) *
          complementMatrixEntry kFourDirection point.mass point.weight 2 2 := by
      rw [hblock.2.2.2.2.2]
      exact hcommon
    exact pos_of_mul_pos_right hprod hdelta.le

theorem kFourGaugeWall_posDef_compl_triangle_star_iff
    (point : DirectionChartPoint 6) (axis : Fin 3 → ℝ) (scale : ℝ)
    (hscale : 0 < scale)
    (hwall : directionChartGap kFourDirection point.mass point.weight
      ({3, 4, 5} : Finset (Fin 6)) = scale • atomMatrix axis)
    (haxisSum : axis ⬝ᵥ kFourAllOnes ≠ 0) (triangle star : Fin 6)
    (htriangle : triangle ∈ kFourTriangleLabels)
    (hstar : star ∈ kFourStarLabels) :
    (directionChartGap kFourDirection point.mass point.weight
        (Finset.univ \ {triangle, star})).PosDef ↔
      complementMatrixEntry kFourDirection point.mass point.weight triangle star ^ 2 <
        complementMatrixEntry kFourDirection point.mass point.weight triangle triangle *
          complementMatrixEntry kFourDirection point.mass point.weight star star := by
  have hij : triangle ≠ star := by
    intro heq
    subst star
    have : triangle ∉ kFourStarLabels := by
      have hcases : triangle = 0 ∨ triangle = 1 ∨ triangle = 2 := by
        simpa [kFourTriangleLabels] using htriangle
      rcases hcases with rfl | rfl | rfl <;> decide
    exact this hstar
  have hboostTriangle : 0 < point.mass triangle / point.weight triangle :=
    div_pos (point.mass_pos triangle) (point.weight_pos triangle)
  have hboostStar : 0 < point.mass star / point.weight star :=
    div_pos (point.mass_pos star) (point.weight_pos star)
  rw [posDef_directionChartGap_compl_pair_iff kFourDirection point.mass point.weight
    hij hboostTriangle hboostStar (posDef_directionChartGap_univ point),
    pairFormDiag_eq_complementMatrixEntry_self,
    pairFormDiag_eq_complementMatrixEntry_self,
    pairFormCross_sq_eq_complementMatrixEntry_sq kFourDirection point.mass point.weight hij]
  simp only [kFourGaugeWall_triangle_complement_diag_pos point axis scale hscale hwall
    haxisSum triangle htriangle, true_and]

theorem kFourGaugeWall_triangle_complement_pair_minors
    (point : DirectionChartPoint 6) (axis : Fin 3 → ℝ) (scale : ℝ)
    (hscale : 0 < scale)
    (hwall : directionChartGap kFourDirection point.mass point.weight
      ({3, 4, 5} : Finset (Fin 6)) = scale • atomMatrix axis)
    (haxisSum : axis ⬝ᵥ kFourAllOnes ≠ 0) :
    let entry := complementMatrixEntry kFourDirection point.mass point.weight
    entry 0 0 * entry 1 1 - entry 0 1 ^ 2 = 0 ∧
      entry 0 0 * entry 2 2 - entry 0 2 ^ 2 = 0 ∧
      entry 1 1 * entry 2 2 - entry 1 2 ^ 2 = 0 := by
  dsimp only
  have ha : 0 < point.mass 0 / point.weight 0 :=
    div_pos (point.mass_pos 0) (point.weight_pos 0)
  have hb : 0 < point.mass 1 / point.weight 1 :=
    div_pos (point.mass_pos 1) (point.weight_pos 1)
  have hc : 0 < point.mass 2 / point.weight 2 :=
    div_pos (point.mass_pos 2) (point.weight_pos 2)
  let delta := point.mass 0 / point.weight 0 * (point.mass 1 / point.weight 1) +
    point.mass 0 / point.weight 0 * (point.mass 2 / point.weight 2) +
    point.mass 1 / point.weight 1 * (point.mass 2 / point.weight 2)
  let common := point.mass 0 / point.weight 0 * (point.mass 1 / point.weight 1) *
    (point.mass 2 / point.weight 2)
  have hdelta : delta ≠ 0 := ne_of_gt (by dsimp only [delta]; positivity)
  have hblock := kFourGaugeWall_triangle_complement_block_scaled point axis scale hscale
    hwall haxisSum
  change
    delta * complementMatrixEntry kFourDirection point.mass point.weight 0 0 = common ∧
      delta * complementMatrixEntry kFourDirection point.mass point.weight 0 1 = -common ∧
      delta * complementMatrixEntry kFourDirection point.mass point.weight 0 2 = common ∧
      delta * complementMatrixEntry kFourDirection point.mass point.weight 1 1 = common ∧
      delta * complementMatrixEntry kFourDirection point.mass point.weight 1 2 = -common ∧
      delta * complementMatrixEntry kFourDirection point.mass point.weight 2 2 = common at hblock
  have hsolve {value rhs : ℝ} (h : delta * value = rhs) : value = rhs / delta := by
    apply (eq_div_iff hdelta).2
    rw [mul_comm]
    exact h
  obtain ⟨h00, h01, h02, h11, h12, h22⟩ := hblock
  rw [hsolve h00, hsolve h01, hsolve h02, hsolve h11, hsolve h12, hsolve h22]
  constructor
  · ring
  constructor <;> ring

theorem kFourGaugeWall_not_posDef_compl_triangle_pair
    (point : DirectionChartPoint 6) (axis : Fin 3 → ℝ) (scale : ℝ)
    (hscale : 0 < scale)
    (hwall : directionChartGap kFourDirection point.mass point.weight
      ({3, 4, 5} : Finset (Fin 6)) = scale • atomMatrix axis)
    (haxisSum : axis ⬝ᵥ kFourAllOnes ≠ 0) {first second : Fin 6}
    (hfirst : first ∈ kFourTriangleLabels) (hsecond : second ∈ kFourTriangleLabels)
    (hne : first ≠ second) :
    ¬(directionChartGap kFourDirection point.mass point.weight
      (Finset.univ \ {first, second})).PosDef := by
  intro hpd
  have htest := (posDef_directionChartGap_compl_pair_iff kFourDirection point.mass
    point.weight hne (div_pos (point.mass_pos first) (point.weight_pos first))
    (div_pos (point.mass_pos second) (point.weight_pos second))
    (posDef_directionChartGap_univ point)).mp hpd
  rw [pairFormDiag_eq_complementMatrixEntry_self,
    pairFormDiag_eq_complementMatrixEntry_self,
    pairFormCross_sq_eq_complementMatrixEntry_sq kFourDirection point.mass point.weight hne]
    at htest
  have hminors := kFourGaugeWall_triangle_complement_pair_minors point axis scale hscale
    hwall haxisSum
  dsimp only at hminors
  have hfirstCases : first = 0 ∨ first = 1 ∨ first = 2 := by
    simpa [kFourTriangleLabels] using hfirst
  have hsecondCases : second = 0 ∨ second = 1 ∨ second = 2 := by
    simpa [kFourTriangleLabels] using hsecond
  rcases hfirstCases with rfl | rfl | rfl <;>
    rcases hsecondCases with rfl | rfl | rfl
  · exact hne rfl
  · nlinarith [hminors.1]
  · nlinarith [hminors.2.1]
  · rw [complementMatrixEntry_comm_of_posDef kFourDirection point.mass point.weight
      (posDef_directionChartGap_univ point) 1 0] at htest
    nlinarith [hminors.1]
  · exact hne rfl
  · nlinarith [hminors.2.2]
  · rw [complementMatrixEntry_comm_of_posDef kFourDirection point.mass point.weight
      (posDef_directionChartGap_univ point) 2 0] at htest
    nlinarith [hminors.2.1]
  · rw [complementMatrixEntry_comm_of_posDef kFourDirection point.mass point.weight
      (posDef_directionChartGap_univ point) 2 1] at htest
    nlinarith [hminors.2.2]
  · exact hne rfl

end Gtz

