/-
Copyright (c) 2026 Grigory Evko. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Gtz.Wave.GaugeWallTriangleComplementBlock
import Gtz.Design.KFourChartClosure

set_option autoImplicit false
set_option relaxedAutoImplicit false

/-!
# The gauge wall cuts the spanning tree list from sixteen to nine

On the canonical gauge wall the triangle principal block of the complement
matrix is a positive multiple of the rank-one matrix generated by the sign
pattern `(1, -1, 1)`.  A rank-one form is singular on every pair of
coordinates, so the complement form vanishes at an explicit nonzero
coefficient vector supported on any two triangle labels.

The consequence holds at EVERY omitted cardinality, not only at two:

* `kFourGaugeWall_not_posDef_of_two_triangle_omitted` kills a selection whose
  omitted set carries two distinct triangle labels;
* `kFourGaugeWall_posDef_compl_triangle_card_le_one` reads that as a bound on
  the omitted set of a positive definite selection;
* `kFourGaugeWall_posDef_spanningTree_mem_nine` spends the bound on the
  sixteen-element spanning tree list and leaves exactly the NINE trees that
  carry two triangle edges.

The seven excluded trees are `{3,4,5}` — the wall itself — together with
`{0,3,5}`, `{0,4,5}`, `{1,3,4}`, `{1,4,5}`, `{2,3,4}` and `{2,3,5}`.  Each is
excluded because its complement carries two triangle labels.

This is the card-three half of the gauge-wall obstruction.  The card-four half
is `Gtz.kFourGaugeWall_not_posDef_compl_triangle_pair`, which is the case
`omitted.card = 2` of the theorem below.
-/

namespace Gtz

open Matrix

/-! ## 1. The complement form on a two-label support -/

/-- The complement matrix is symmetric at a positive definite full selection. -/
theorem complementMatrixEntry_symm {size : ℕ} (direction : Fin size → (Fin 3 → ℝ))
    (mass weight : Fin size → ℝ)
    (huniv : (directionChartGap direction mass weight Finset.univ).PosDef)
    (i j : Fin size) :
    complementMatrixEntry direction mass weight i j =
      complementMatrixEntry direction mass weight j i := by
  by_cases hij : i = j
  · subst j
    rfl
  · have hji : j ≠ i := Ne.symm hij
    simp only [complementMatrixEntry, if_neg hij, if_neg hji,
      fullInverseForm_comm direction mass weight huniv i j]
    ring

/-- A coefficient vector supported on two omitted labels reads the complement
form as the two-by-two block on those labels.  No positivity is used. -/
theorem complementForm_support_pair {size : ℕ} (direction : Fin size → (Fin 3 → ℝ))
    (mass weight : Fin size → ℝ) (omitted : Finset (Fin size))
    {i j : Fin size} (hi : i ∈ omitted) (hj : j ∈ omitted) (hij : i ≠ j)
    (coeff : Fin size → ℝ) (hsupp : ∀ x, x ≠ i → x ≠ j → coeff x = 0) :
    complementForm direction mass weight omitted coeff
      = complementMatrixEntry direction mass weight i i * coeff i * coeff i
        + complementMatrixEntry direction mass weight i j * coeff i * coeff j
        + complementMatrixEntry direction mass weight j i * coeff j * coeff i
        + complementMatrixEntry direction mass weight j j * coeff j * coeff j := by
  classical
  rw [complementForm_eq_sum]
  have hnotmem : i ∉ ({j} : Finset (Fin size)) := by simpa using hij
  have hpair : ({i, j} : Finset (Fin size)) ⊆ omitted := by
    intro x hx
    simp only [Finset.mem_insert, Finset.mem_singleton] at hx
    rcases hx with rfl | rfl
    · exact hi
    · exact hj
  have hzero : ∀ x : Fin size, x ∉ ({i, j} : Finset (Fin size)) → coeff x = 0 := by
    intro x hx
    simp only [Finset.mem_insert, Finset.mem_singleton, not_or] at hx
    exact hsupp x hx.1 hx.2
  have hinner : ∀ a : Fin size,
      (∑ b ∈ omitted, complementMatrixEntry direction mass weight a b * coeff a * coeff b)
        = ∑ b ∈ ({i, j} : Finset (Fin size)),
            complementMatrixEntry direction mass weight a b * coeff a * coeff b := by
    intro a
    refine (Finset.sum_subset hpair ?_).symm
    intro x _ hx
    rw [hzero x hx]
    ring
  have houter : ∀ x ∈ omitted, x ∉ ({i, j} : Finset (Fin size)) →
      (∑ b ∈ omitted, complementMatrixEntry direction mass weight x b * coeff x * coeff b)
        = 0 := by
    intro x _ hx
    refine Finset.sum_eq_zero ?_
    intro b _
    rw [hzero x hx]
    ring
  rw [← Finset.sum_subset hpair houter]
  simp only [hinner, Finset.sum_insert hnotmem, Finset.sum_singleton]
  ring

/-! ## 2. The rank-one triangle block -/

/-- The sign pattern generating the rank-one triangle block on the gauge wall. -/
def kFourTriangleSign : Fin 6 → ℝ
  | 0 => 1
  | 1 => -1
  | 2 => 1
  | _ => 0

theorem kFourTriangleSign_sq_of_mem {p : Fin 6} (hp : p ∈ kFourTriangleLabels) :
    kFourTriangleSign p * kFourTriangleSign p = 1 := by
  have hcases : p = 0 ∨ p = 1 ∨ p = 2 := by simpa [kFourTriangleLabels] using hp
  rcases hcases with rfl | rfl | rfl <;> norm_num [kFourTriangleSign]

/-- **THE TRIANGLE BLOCK IS RANK ONE.**  Scaled by the positive Laplacian
denominator, every entry of the triangle principal block of the complement
matrix is the common product times the outer square of the sign pattern. -/
theorem kFourGaugeWall_triangle_block_rankOne
    (point : DirectionChartPoint 6) (axis : Fin 3 → ℝ) (scale : ℝ)
    (hscale : 0 < scale)
    (hwall : directionChartGap kFourDirection point.mass point.weight
      ({3, 4, 5} : Finset (Fin 6)) = scale • atomMatrix axis)
    (haxisSum : axis ⬝ᵥ kFourAllOnes ≠ 0) {p q : Fin 6}
    (hp : p ∈ kFourTriangleLabels) (hq : q ∈ kFourTriangleLabels) :
    (point.mass 0 / point.weight 0 * (point.mass 1 / point.weight 1) +
        point.mass 0 / point.weight 0 * (point.mass 2 / point.weight 2) +
        point.mass 1 / point.weight 1 * (point.mass 2 / point.weight 2)) *
        complementMatrixEntry kFourDirection point.mass point.weight p q
      = point.mass 0 / point.weight 0 * (point.mass 1 / point.weight 1) *
          (point.mass 2 / point.weight 2) *
          (kFourTriangleSign p * kFourTriangleSign q) := by
  have hblock := kFourGaugeWall_triangle_complement_block_scaled point axis scale hscale
    hwall haxisSum
  dsimp only at hblock
  obtain ⟨h00, h01, h02, h11, h12, h22⟩ := hblock
  have hsymm := complementMatrixEntry_symm kFourDirection point.mass point.weight
    (posDef_directionChartGap_univ point)
  have hpc : p = 0 ∨ p = 1 ∨ p = 2 := by simpa [kFourTriangleLabels] using hp
  have hqc : q = 0 ∨ q = 1 ∨ q = 2 := by simpa [kFourTriangleLabels] using hq
  rcases hpc with rfl | rfl | rfl <;> rcases hqc with rfl | rfl | rfl
  · norm_num [kFourTriangleSign]; linear_combination h00
  · norm_num [kFourTriangleSign]; linear_combination h01
  · norm_num [kFourTriangleSign]; linear_combination h02
  · rw [hsymm 1 0]; norm_num [kFourTriangleSign]; linear_combination h01
  · norm_num [kFourTriangleSign]; linear_combination h11
  · norm_num [kFourTriangleSign]; linear_combination h12
  · rw [hsymm 2 0]; norm_num [kFourTriangleSign]; linear_combination h02
  · rw [hsymm 2 1]; norm_num [kFourTriangleSign]; linear_combination h12
  · norm_num [kFourTriangleSign]; linear_combination h22

/-! ## 3. The kill at every omitted cardinality -/

/-- **THE TWO-TRIANGLE KILL.**  On the canonical gauge wall, a selection whose
OMITTED set carries two distinct triangle labels is never positive definite.
The rank-one triangle block is singular on that pair, so the complement form
vanishes at an explicit nonzero coefficient vector.

This holds at every omitted cardinality.  The landed
`kFourGaugeWall_not_posDef_compl_triangle_pair` is the case of cardinality
two. -/
theorem kFourGaugeWall_not_posDef_of_two_triangle_omitted
    (point : DirectionChartPoint 6) (axis : Fin 3 → ℝ) (scale : ℝ)
    (hscale : 0 < scale)
    (hwall : directionChartGap kFourDirection point.mass point.weight
      ({3, 4, 5} : Finset (Fin 6)) = scale • atomMatrix axis)
    (haxisSum : axis ⬝ᵥ kFourAllOnes ≠ 0) {omitted : Finset (Fin 6)} {i j : Fin 6}
    (hi : i ∈ omitted) (hj : j ∈ omitted) (hij : i ≠ j)
    (hitri : i ∈ kFourTriangleLabels) (hjtri : j ∈ kFourTriangleLabels) :
    ¬ (directionChartGap kFourDirection point.mass point.weight
        (Finset.univ \ omitted)).PosDef := by
  classical
  intro hpd
  set coeff : Fin 6 → ℝ := fun x =>
    if x = i then kFourTriangleSign j
    else if x = j then -(kFourTriangleSign i) else 0 with hcoeffdef
  have hci : coeff i = kFourTriangleSign j := by simp [hcoeffdef]
  have hcj : coeff j = -(kFourTriangleSign i) := by
    simp [hcoeffdef, Ne.symm hij]
  have hcz : ∀ x : Fin 6, x ≠ i → x ≠ j → coeff x = 0 := by
    intro x h1 h2
    simp [hcoeffdef, h1, h2]
  have hsqj := kFourTriangleSign_sq_of_mem hjtri
  have hne : ∃ label ∈ omitted, coeff label ≠ 0 := by
    refine ⟨i, hi, ?_⟩
    rw [hci]
    intro hzero
    rw [hzero] at hsqj
    norm_num at hsqj
  have hboost : ∀ label ∈ omitted, 0 < point.mass label / point.weight label :=
    fun label _ => div_pos (point.mass_pos label) (point.weight_pos label)
  have hform := (posDef_directionChartGap_compl_iff kFourDirection point.mass point.weight
    omitted hboost (posDef_directionChartGap_univ point)).mp hpd coeff hne
  rw [complementForm_support_pair kFourDirection point.mass point.weight omitted hi hj hij
    coeff hcz, hci, hcj] at hform
  have hbii := kFourGaugeWall_triangle_block_rankOne point axis scale hscale hwall haxisSum
    hitri hitri
  have hbij := kFourGaugeWall_triangle_block_rankOne point axis scale hscale hwall haxisSum
    hitri hjtri
  have hbji := kFourGaugeWall_triangle_block_rankOne point axis scale hscale hwall haxisSum
    hjtri hitri
  have hbjj := kFourGaugeWall_triangle_block_rankOne point axis scale hscale hwall haxisSum
    hjtri hjtri
  have ha : 0 < point.mass 0 / point.weight 0 :=
    div_pos (point.mass_pos 0) (point.weight_pos 0)
  have hb : 0 < point.mass 1 / point.weight 1 :=
    div_pos (point.mass_pos 1) (point.weight_pos 1)
  have hc : 0 < point.mass 2 / point.weight 2 :=
    div_pos (point.mass_pos 2) (point.weight_pos 2)
  have hdelta : 0 < point.mass 0 / point.weight 0 * (point.mass 1 / point.weight 1) +
      point.mass 0 / point.weight 0 * (point.mass 2 / point.weight 2) +
      point.mass 1 / point.weight 1 * (point.mass 2 / point.weight 2) := by positivity
  have hkill : (point.mass 0 / point.weight 0 * (point.mass 1 / point.weight 1) +
      point.mass 0 / point.weight 0 * (point.mass 2 / point.weight 2) +
      point.mass 1 / point.weight 1 * (point.mass 2 / point.weight 2)) *
      (complementMatrixEntry kFourDirection point.mass point.weight i i *
          kFourTriangleSign j * kFourTriangleSign j +
        complementMatrixEntry kFourDirection point.mass point.weight i j *
          kFourTriangleSign j * -(kFourTriangleSign i) +
        complementMatrixEntry kFourDirection point.mass point.weight j i *
          -(kFourTriangleSign i) * kFourTriangleSign j +
        complementMatrixEntry kFourDirection point.mass point.weight j j *
          -(kFourTriangleSign i) * -(kFourTriangleSign i)) = 0 := by
    linear_combination (kFourTriangleSign j * kFourTriangleSign j) * hbii
      + (kFourTriangleSign j * -(kFourTriangleSign i)) * hbij
      + (-(kFourTriangleSign i) * kFourTriangleSign j) * hbji
      + (-(kFourTriangleSign i) * -(kFourTriangleSign i)) * hbjj
  nlinarith [hform, hkill, hdelta]

/-! ## 4. The reduction of the spanning tree list -/

/-- A positive definite selection omits at most one triangle label. -/
theorem kFourGaugeWall_posDef_compl_triangle_card_le_one
    (point : DirectionChartPoint 6) (axis : Fin 3 → ℝ) (scale : ℝ)
    (hscale : 0 < scale)
    (hwall : directionChartGap kFourDirection point.mass point.weight
      ({3, 4, 5} : Finset (Fin 6)) = scale • atomMatrix axis)
    (haxisSum : axis ⬝ᵥ kFourAllOnes ≠ 0) {omitted : Finset (Fin 6)}
    (hpd : (directionChartGap kFourDirection point.mass point.weight
      (Finset.univ \ omitted)).PosDef) :
    (omitted ∩ kFourTriangleLabels).card ≤ 1 := by
  classical
  by_contra hcard
  push Not at hcard
  obtain ⟨i, hi, j, hj, hij⟩ := Finset.one_lt_card.mp hcard
  exact kFourGaugeWall_not_posDef_of_two_triangle_omitted point axis scale hscale hwall
    haxisSum (Finset.mem_of_mem_inter_left hi) (Finset.mem_of_mem_inter_left hj) hij
    (Finset.mem_of_mem_inter_right hi) (Finset.mem_of_mem_inter_right hj) hpd

/-- The same bound stated on the complement of the selection itself. -/
theorem kFourGaugeWall_posDef_selection_compl_triangle_card_le_one
    (point : DirectionChartPoint 6) (axis : Fin 3 → ℝ) (scale : ℝ)
    (hscale : 0 < scale)
    (hwall : directionChartGap kFourDirection point.mass point.weight
      ({3, 4, 5} : Finset (Fin 6)) = scale • atomMatrix axis)
    (haxisSum : axis ⬝ᵥ kFourAllOnes ≠ 0) {selected : Finset (Fin 6)}
    (hpd : (directionChartGap kFourDirection point.mass point.weight selected).PosDef) :
    (selectedᶜ ∩ kFourTriangleLabels).card ≤ 1 := by
  classical
  refine kFourGaugeWall_posDef_compl_triangle_card_le_one point axis scale hscale hwall
    haxisSum ?_
  have hrw : Finset.univ \ selectedᶜ = selected := by
    rw [← Finset.compl_eq_univ_sdiff, compl_compl]
  rw [hrw]
  exact hpd

/-- The nine spanning trees that carry two triangle edges. -/
def kFourGaugeWallTreeShortList : List (Finset (Fin 6)) :=
  [{0, 1, 3}, {0, 1, 4}, {0, 1, 5}, {0, 2, 3}, {0, 2, 4}, {0, 2, 5},
   {1, 2, 3}, {1, 2, 4}, {1, 2, 5}]

private theorem shortList_of_card (winner : Finset (Fin 6))
    (hmem : winner ∈ kFourSpanningTreeList)
    (hcard : (winnerᶜ ∩ kFourTriangleLabels).card ≤ 1) :
    winner ∈ kFourGaugeWallTreeShortList := by
  revert hmem hcard
  revert winner
  decide

/-- **THE GAUGE WALL CUTS THE TREE LIST TO NINE.**  A positive definite
spanning tree on the canonical gauge wall lies in the nine-element short list.
The seven excluded trees are the wall `{3,4,5}` together with `{0,3,5}`,
`{0,4,5}`, `{1,3,4}`, `{1,4,5}`, `{2,3,4}` and `{2,3,5}`. -/
theorem kFourGaugeWall_posDef_spanningTree_mem_nine
    (point : DirectionChartPoint 6) (axis : Fin 3 → ℝ) (scale : ℝ)
    (hscale : 0 < scale)
    (hwall : directionChartGap kFourDirection point.mass point.weight
      ({3, 4, 5} : Finset (Fin 6)) = scale • atomMatrix axis)
    (haxisSum : axis ⬝ᵥ kFourAllOnes ≠ 0) {winner : Finset (Fin 6)}
    (hmem : winner ∈ kFourSpanningTreeList)
    (hpd : (directionChartGap kFourDirection point.mass point.weight winner).PosDef) :
    winner ∈ kFourGaugeWallTreeShortList :=
  shortList_of_card winner hmem
    (kFourGaugeWall_posDef_selection_compl_triangle_card_le_one point axis scale hscale
      hwall haxisSum hpd)

/-- Every tree of the short list carries exactly two triangle edges and one
star edge. -/
theorem kFourGaugeWallTreeShortList_shape :
    ∀ winner ∈ kFourGaugeWallTreeShortList,
      (winner ∩ kFourTriangleLabels).card = 2 ∧
        (winner ∩ kFourStarLabels).card = 1 := by
  decide

/-- The short list is exactly the spanning trees carrying two triangle edges. -/
theorem kFourGaugeWallTreeShortList_eq_filter :
    ∀ winner : Finset (Fin 6),
      (winner ∈ kFourGaugeWallTreeShortList ↔
        winner ∈ kFourSpanningTreeList ∧ (winner ∩ kFourTriangleLabels).card = 2) := by
  decide

end Gtz
