/-
# The chart's first-order system, DERIVED from minimality

`Gtz.Quantitative.ChartStationary`, `Gtz.Quantitative.ChartStrongStationary` and
`Gtz.Quantitative.ChartCovering` all take their datum as a HYPOTHESIS.  Every theorem in
that layer reads "given a chart stationarity datum, ...", and the passage from "this point
minimises the chart objective" to "this datum holds" lives outside Lean.  This file closes
that passage, and nothing else.

The objective is

    G(P, t) = max over rank-subsets C of lambda_min(W[C]),   W = P - diag t,

over the constraint set {P symmetric idempotent of trace rank} x {t > 0, sum t = 1}.

## The argument, in one paragraph

Suppose one tangent direction has, at every ACTIVE block, a tight unit vector whose slope
is strictly negative.  Move along the CAYLEY curve `P(s) = Q(s) P Q(s)ᵀ`,
`Q(s) = (1 + sK)(1 - sK)⁻¹`, generated by the skew matrix `K = ½ [Pdot, P]`, together with
the straight line `t(s) = t + s tdot`.  At an active block the FROZEN tight vector is a
legitimate test vector for the MOVED block, so its Rayleigh quotient is an upper bound for
the moved least eigenvalue, and that quotient is `value + s (slope) + O(s²)` — strictly
below `value` for small positive `s`.  At an inactive block the side condition
`Gtz.IsChartInactiveStrict` supplies a probe STRICTLY below `value`, and the same frozen
probe stays strictly below for small `s`.  So no block dominates at `value` at the moved
point, contradicting minimality.  The contrapositive is `Gtz.IsChartTightCovering`, which
the shipped Gordan exchange already turns into the strong multiplier bundle.

## What is PROVED here

* `chartCayley` — the Cayley transform of a skew matrix is ORTHOGONAL at every step
  (`chartCayley_transpose_mul_self`), and `chartCayleyProjection` is a symmetric idempotent
  of the same trace at every step.  The constraint set is preserved EXACTLY, not to first
  order.  This is the Grassmannian curve the sibling file's honesty (a) names as missing.
* `abs_chartCayleyProjection_form_sub_le` — **THE FROZEN-PROBE EXPANSION.**  A fixed unit
  probe's Rayleigh quotient along the curve is the base quotient plus `2s ⟨v, [K,P] v⟩`,
  with error at most `8 s² ‖K‖_F²`.  Elementary throughout: Cauchy–Schwarz on the raw dot
  product, the shipped resolvent contraction of `Gtz.LinAlg.ResolventPerturbation`, and the
  fact that an orthogonal projection contracts.  No operator norm, no eigenvalue, no
  derivative, no differentiability API.
* `chartTangentSkew_commutator` — `[½[Pdot,P], P] = ½ Pdot` exactly when the direction's
  two diagonal blocks vanish, which is the definition of `Gtz.IsChartTangent`.  So the
  curve realises the prescribed direction, and `abs_chartTangentCurve_gap_form_sub_le`
  reads the whole first-order term as the SHIPPED `Gtz.chartTangentSlope`.
* `sq_chartCayleyProjection_sub_entry_le` — the curve is entrywise Lipschitz in the step,
  so a merely LOCAL minimality hypothesis suffices.
* `exists_chartTangentCurve_descent` — **THE DESCENT LEMMA.**
* `isChartTightCovering_of_localMinimum` and `isChartTightCovering_of_globalMinimum` — the
  covering condition AT A MINIMUM, landing exactly on `Gtz.IsChartTightCovering`.
* `isChartStrongStationaryData_of_globalMinimum` and
  `exists_isChartStationaryData_and_isChartArgmaxValue_of_globalMinimum` — the shipped
  bundles, and `Gtz.IsChartArgmaxValue`, from minimality.
* `isChartArgmaxValue_of_isChartInactiveStrict` — **ADMISSIBILITY IS DERIVED, not assumed.**
  Every exclusion in the layer consumes `Gtz.IsChartArgmaxValue` as a hypothesis; here it
  follows from the inactive side condition plus one tight direction per active block.

## The four checks the campaign asked for, and what they returned

**(1) The Rayleigh quotient is an exact upper bound at an active block — HOLDS, and more
cheaply than stated.**  In the ambient phrasing this layer uses it is not a lemma about
eigenvalues at all: `ChartBlockDominatesAtValue` quantifies over probes supported in the
block, so ONE unit probe strictly below `value` refutes domination by definition
(`not_chartBlockDominatesAtValue_of_probe`).  No symmetry hypothesis, no attainment, no
spectral theorem.  The direction matters: an upper bound on the least eigenvalue is what a
DESCENT argument needs, and it is exactly the direction in which a frozen probe is
worthless for RIGIDITY — `Gtz.stratumCriticalRay_not_posSemidef` is the shipped
counterexample to reading a frozen-probe second-order coefficient as convexity, and nothing
here contradicts it.

**(2) The Cayley transform is orthogonal and rational — HOLDS, with the smallness
hypothesis DELETED.**  `1 - sK` is invertible at EVERY real step, not only at small ones,
because `⟨x, Kx⟩ = 0` for skew `K` forces `|(1 - sK)x|² = |x|² + s²|Kx|² ≥ |x|²`
(`coercive_chartCayleyDenominator`).  Smallness of the step enters in exactly three places
and none of them is the transform: keeping the weights positive, meeting the closeness
radius, and beating the second-order remainder.

**(3) Weyl controls the inactive blocks — NOT NEEDED, and `Gtz.lipschitzWith_lambdaMinCLM`
is NOT consumed anywhere below.**  `Gtz.IsChartInactiveStrict` hands back a PROBE, not an
eigenvalue, and the same frozen-probe expansion keeps that probe strictly below the value.
Uniformity over the finitely many `rank`-subsets is a `Finset` minimum of finitely many
positive slacks (`exists_pos_le_forall_mem`), not a uniform Lipschitz estimate.  Routing
through Weyl would have forced the `Gtz.lambdaMinMat` submatrix reindexing that the whole
chart layer is built to avoid.

**(4) Admissibility at a minimum — DERIVED, not definitional, and LOCAL minimality
suffices.**  `Gtz.IsChartArgmaxValue` does not come for free from minimality: it needs the
active family to be the argmax family (which is `Gtz.IsChartInactiveStrict`) AND a unit
tight direction at each active block.  With both it is a theorem here.  Conversely
`IsChartInactiveStrict` IS essentially definitional at a global minimum whose active family
is taken to be the argmax family, and it needs no attainment: `lambda_min(W[C]) < value` is
an infimum strictly below `value` and therefore already exhibits a probe.  What is NOT free
is `exists_tightDir` — producing a tight eigenvector at a block where `lambda_min(W[C])`
EQUALS `value` is the spectral theorem, and this file does not supply it.  It is not needed
for the covering conclusion (covering is vacuous at a block with no tight vector — see
`Gtz.isChartTightCovering_of_forall_isChartTightVector_eq_zero`); it is needed only to
rebuild the bundle and to derive admissibility.  On local versus global: the argument is
LOCAL, the entrywise estimate `sq_chartCayleyProjection_sub_entry_le` proves it, and
`isChartTightCovering_of_localMinimum` is the primary statement with the global form its
corollary.  The chain supplies a global minimum, so the global form is the one that will be
used; the local form is stated because it is strictly stronger and costs one estimate.

## HONESTY — WHAT THIS BUYS AND WHAT IT DOES NOT

**IT CLOSES NO CELL.  It does not bear on `GtzWeighted 6 3` or `GtzWeighted 7 3`.**  The
condition derived here is `Gtz.IsChartTightCovering`, which
`Gtz.isChartTightCovering_iff_forall_hasBalancedMultiplier` proves EQUIVALENT to the
universal-selection form, and honesty (c) of `Gtz.Quantitative.ChartStrongStationary`
records that at the `(4,2)` SIC, the `(6,3)` trine and the `(9,3)` Hesse configuration
every active tight eigenvalue is SIMPLE, so by
`Gtz.isChartStrongStationaryData_iff_of_simpleTightBlocks` the strong system holds there
exactly when the weak one does — which it does.  A necessary condition MUST accept genuine
minima; that is correct behaviour, not a defect.  What it means is that this file contains
NO realness ingredient and cannot separate the fields, and it must never be advertised as a
route to either open cell.  Any reading of the theorems below as progress on `(6,3)` or
`(7,3)` is a misreading.

**What it does buy.**  It removes a scaffolding gap: the layer's theorems no longer need a
datum handed to them by assumption, provided minimality and the inactive side condition are
supplied.  `Gtz.IsChartInactiveStrict`, which until now was consumed only by its own
reading lemma, becomes load-bearing.  `Gtz.IsChartArgmaxValue` stops being an assumption
wherever minimality is available.  And the argument runs
on the CHART objective throughout, so nothing here depends on the design-side objective or
on `Gtz.ChartPointHasDesign`.

**What is NOT established here.**  That the chart objective attains its minimum (that is
attainment, and it is not proved in this file); that the argmax family is nonempty or that
its blocks carry tight directions (spectral theorem); any claim about the paper's
conditional theorems, which are not inputs to this file; and any second-order statement
whatsoever.  `Gtz.hasBalancedMultiplier_iff_not_exists_descent` says the criterion is sharp
at first order and silent beyond it, and that remains exactly true after this file.

## NOT here, deliberately

* No manifold, no tangent bundle, no derivative and no `HasDerivAt`.  The curve is a
  rational matrix function and the expansion is an inequality with an explicit constant.
* No reproof of the Gordan exchange, of the descent lemma of
  `Gtz.Quantitative.ChartStrongStationary`, or of the cone vocabulary of
  `Gtz.Quantitative.ChartCovering`.  All three are imported and consumed.
* No eigenvalue function, no `Gtz.lambdaMinMat`, no submatrix reindexing, and no Weyl.
* No second-order object.  There is no curvature term, no Hessian and no
  second-variation form anywhere below, and none may be added to this file.
-/
import Mathlib
import Gtz.LinAlg.ResolventPerturbation
import Gtz.Quantitative.ChartCovering

set_option autoImplicit false
set_option relaxedAutoImplicit false

namespace Gtz

open Matrix

variable {size : ℕ}

/-! ## A sqrt-free operator cap -/

/-- **THE SQUARED FROBENIUS CAP** of a matrix: the sum of the squares of all its
entries.  It caps the image form, `|A x|² ≤ cap · |x|²`, by one Cauchy–Schwarz per
row, and it is used here only to bound a second-order remainder, so no sharpness is
claimed or needed. -/
def chartFrobeniusSquare (target : Matrix (Fin size) (Fin size) ℝ) : ℝ :=
  ∑ rowIndex : Fin size, ∑ colIndex : Fin size, target rowIndex colIndex ^ 2

theorem chartFrobeniusSquare_nonneg (target : Matrix (Fin size) (Fin size) ℝ) :
    0 ≤ chartFrobeniusSquare target :=
  Finset.sum_nonneg fun _ _ => Finset.sum_nonneg fun _ _ => sq_nonneg _

/-- **THE CAP CAPS THE IMAGE FORM**: `|A x|² ≤ ‖A‖_F² · |x|²`, one Cauchy–Schwarz
per row and then a sum. -/
theorem mulVec_dotProduct_self_le_chartFrobeniusSquare
    (target : Matrix (Fin size) (Fin size) ℝ) (probe : Fin size → ℝ) :
    (target *ᵥ probe) ⬝ᵥ (target *ᵥ probe)
      ≤ chartFrobeniusSquare target * (probe ⬝ᵥ probe) := by
  have hrow : ∀ rowIndex : Fin size,
      ((target *ᵥ probe) rowIndex) ^ 2
        ≤ (∑ colIndex : Fin size, target rowIndex colIndex ^ 2)
          * ∑ colIndex : Fin size, probe colIndex ^ 2 := by
    intro rowIndex
    have hcauchy := Finset.sum_mul_sq_le_sq_mul_sq (Finset.univ : Finset (Fin size))
      (fun colIndex => target rowIndex colIndex) probe
    simpa only [Matrix.mulVec, dotProduct] using hcauchy
  calc (target *ᵥ probe) ⬝ᵥ (target *ᵥ probe)
      = ∑ rowIndex : Fin size, ((target *ᵥ probe) rowIndex) ^ 2 :=
        dotProduct_self_eq_sum_sq _
    _ ≤ ∑ rowIndex : Fin size,
          (∑ colIndex : Fin size, target rowIndex colIndex ^ 2)
            * ∑ colIndex : Fin size, probe colIndex ^ 2 :=
        Finset.sum_le_sum fun rowIndex _ => hrow rowIndex
    _ = chartFrobeniusSquare target * (probe ⬝ᵥ probe) := by
        rw [← Finset.sum_mul, chartFrobeniusSquare, dotProduct_self_eq_sum_sq]

/-- From `a² ≤ cap²` with a nonnegative cap, the two-sided bound `|a| ≤ cap`. -/
theorem abs_le_of_sq_le_sq_of_nonneg {value cap : ℝ} (hsq : value ^ 2 ≤ cap ^ 2)
    (hcapNonneg : 0 ≤ cap) : |value| ≤ cap := by
  nlinarith [abs_nonneg value, sq_abs value, sq_nonneg (|value| - cap), sq_nonneg (|value| + cap)]

/-! ## Skew matrices -/

/-- **A SKEW MATRIX HAS VANISHING QUADRATIC FORM.**  The single fact that makes the
Cayley denominator invertible at EVERY step and its inverse a contraction. -/
theorem dotProduct_mulVec_skew_self_eq_zero {skew : Matrix (Fin size) (Fin size) ℝ}
    (hskew : skewᵀ = -skew) (probe : Fin size → ℝ) : probe ⬝ᵥ (skew *ᵥ probe) = 0 := by
  have hflip : probe ⬝ᵥ (skew *ᵥ probe) = -(probe ⬝ᵥ (skew *ᵥ probe)) := by
    calc probe ⬝ᵥ (skew *ᵥ probe)
        = (skewᵀ *ᵥ probe) ⬝ᵥ probe := (dotProduct_mulVec_transpose skew probe probe).symm
      _ = ((-skew) *ᵥ probe) ⬝ᵥ probe := by rw [hskew]
      _ = -(probe ⬝ᵥ (skew *ᵥ probe)) := by
          rw [Matrix.neg_mulVec, neg_dotProduct, dotProduct_comm]
  linarith

/-! ## The chart's own contractions

Two readings of "a symmetric idempotent is a contraction", both from the shipped
identity `Gtz.dotProduct_mulVec_eq_image_dotProduct_self`. -/

/-- The chart's quadratic form is nonnegative. -/
theorem dotProduct_mulVec_nonneg_of_symmetricIdempotent
    {projection : Matrix (Fin size) (Fin size) ℝ} (hsymmetric : projectionᵀ = projection)
    (hidempotent : projection * projection = projection) (probe : Fin size → ℝ) :
    0 ≤ probe ⬝ᵥ (projection *ᵥ probe) := by
  rw [dotProduct_mulVec_eq_image_dotProduct_self hsymmetric hidempotent]
  exact dotProduct_self_nonneg _

/-- The chart's quadratic form is capped by the squared length: apply the same
identity to the complementary projection `1 - P`. -/
theorem dotProduct_mulVec_le_self_of_symmetricIdempotent
    {projection : Matrix (Fin size) (Fin size) ℝ} (hsymmetric : projectionᵀ = projection)
    (hidempotent : projection * projection = projection) (probe : Fin size → ℝ) :
    probe ⬝ᵥ (projection *ᵥ probe) ≤ probe ⬝ᵥ probe := by
  have hcomplementSymmetric :
      (1 - projection : Matrix (Fin size) (Fin size) ℝ)ᵀ = 1 - projection := by
    rw [Matrix.transpose_sub, Matrix.transpose_one, hsymmetric]
  have hcomplementIdempotent :
      (1 - projection : Matrix (Fin size) (Fin size) ℝ) * (1 - projection) = 1 - projection := by
    rw [Matrix.sub_mul, Matrix.mul_sub, Matrix.mul_sub, Matrix.one_mul, Matrix.mul_one,
      Matrix.one_mul, hidempotent]
    abel
  have hnonneg := dotProduct_mulVec_nonneg_of_symmetricIdempotent hcomplementSymmetric
    hcomplementIdempotent probe
  rw [Matrix.sub_mulVec, dotProduct_sub, Matrix.one_mulVec] at hnonneg
  linarith

/-- The chart contracts squared lengths, which is the form the remainder bound uses. -/
theorem mulVec_dotProduct_self_le_of_symmetricIdempotent
    {projection : Matrix (Fin size) (Fin size) ℝ} (hsymmetric : projectionᵀ = projection)
    (hidempotent : projection * projection = projection) (probe : Fin size → ℝ) :
    (projection *ᵥ probe) ⬝ᵥ (projection *ᵥ probe) ≤ probe ⬝ᵥ probe := by
  rw [← dotProduct_mulVec_eq_image_dotProduct_self hsymmetric hidempotent]
  exact dotProduct_mulVec_le_self_of_symmetricIdempotent hsymmetric hidempotent probe

/-! ## The Cayley denominator -/

/-- **THE CAYLEY DENOMINATOR** `1 - s K`.  Its transpose at a skew `K` is the same
expression at `-s`, which is why one definition serves both factors of the
transform. -/
def chartCayleyDenominator (step : ℝ) (skew : Matrix (Fin size) (Fin size) ℝ) :
    Matrix (Fin size) (Fin size) ℝ :=
  1 - step • skew

theorem transpose_chartCayleyDenominator {skew : Matrix (Fin size) (Fin size) ℝ}
    (hskew : skewᵀ = -skew) (step : ℝ) :
    (chartCayleyDenominator step skew)ᵀ = chartCayleyDenominator (-step) skew := by
  rw [chartCayleyDenominator, chartCayleyDenominator, Matrix.transpose_sub, Matrix.transpose_one,
    Matrix.transpose_smul, hskew, smul_neg, neg_smul, sub_neg_eq_add]

/-- The denominator's action on a probe, unfolded. -/
theorem chartCayleyDenominator_mulVec (step : ℝ) (skew : Matrix (Fin size) (Fin size) ℝ)
    (probe : Fin size → ℝ) :
    chartCayleyDenominator step skew *ᵥ probe = probe - step • (skew *ᵥ probe) := by
  have hsmulImage : (step • skew) *ᵥ probe = step • (skew *ᵥ probe) := by
    funext atomIndex
    simp only [Matrix.mulVec, dotProduct, Matrix.smul_apply, Pi.smul_apply, smul_eq_mul,
      Finset.mul_sum]
    exact Finset.sum_congr rfl fun colIndex _ => by ring
  rw [chartCayleyDenominator, Matrix.sub_mulVec, Matrix.one_mulVec, hsmulImage]

/-- **THE DENOMINATOR EXPANDS THE FORM**, at EVERY step: `|(1 - sK)x|² = |x|² +
s²|Kx|² ≥ |x|²`, because the cross term is the skew form and vanishes.  No smallness
of the step is needed anywhere — this is what makes the Cayley curve global. -/
theorem coercive_chartCayleyDenominator {skew : Matrix (Fin size) (Fin size) ℝ}
    (hskew : skewᵀ = -skew) (step : ℝ) (probe : Fin size → ℝ) :
    1 * (probe ⬝ᵥ probe)
      ≤ (chartCayleyDenominator step skew *ᵥ probe)
        ⬝ᵥ (chartCayleyDenominator step skew *ᵥ probe) := by
  have himage := chartCayleyDenominator_mulVec step skew probe
  have hcross : probe ⬝ᵥ (skew *ᵥ probe) = 0 := dotProduct_mulVec_skew_self_eq_zero hskew probe
  have hexpand : (probe - step • (skew *ᵥ probe)) ⬝ᵥ (probe - step • (skew *ᵥ probe))
      = probe ⬝ᵥ probe
        + step ^ 2 * ((skew *ᵥ probe) ⬝ᵥ (skew *ᵥ probe)) := by
    rw [dotProduct_sub, sub_dotProduct, sub_dotProduct, smul_dotProduct, dotProduct_smul,
      dotProduct_smul, smul_eq_mul, smul_eq_mul, smul_eq_mul, hcross,
      dotProduct_comm (skew *ᵥ probe) probe, hcross]
    simp only [smul_dotProduct, smul_eq_mul]
    ring
  rw [himage, hexpand, one_mul]
  nlinarith [dotProduct_self_nonneg (skew *ᵥ probe), sq_nonneg step]

theorem isUnit_det_chartCayleyDenominator {skew : Matrix (Fin size) (Fin size) ℝ}
    (hskew : skewᵀ = -skew) (step : ℝ) :
    IsUnit (chartCayleyDenominator step skew).det :=
  coercive_isUnit_det one_pos (coercive_chartCayleyDenominator hskew step)

/-- **THE RESOLVENT CONTRACTS**: `|(1 - sK)⁻¹ y| ≤ |y|`, at every step. -/
theorem inverse_chartCayleyDenominator_contraction {skew : Matrix (Fin size) (Fin size) ℝ}
    (hskew : skewᵀ = -skew) (step : ℝ) (target : Fin size → ℝ) :
    ((chartCayleyDenominator step skew)⁻¹ *ᵥ target)
        ⬝ᵥ ((chartCayleyDenominator step skew)⁻¹ *ᵥ target)
      ≤ target ⬝ᵥ target := by
  have hbound := inverse_contraction_of_coercive one_pos
    (coercive_chartCayleyDenominator hskew step) target
  linarith

/-! ## The Cayley transform -/

/-- **THE CAYLEY TRANSFORM** `Q(s) = (1 + sK)(1 - sK)⁻¹` of a skew matrix.  Rational
in the step, orthogonal at every step, and equal to `1` at step zero. -/
noncomputable def chartCayley (step : ℝ) (skew : Matrix (Fin size) (Fin size) ℝ) :
    Matrix (Fin size) (Fin size) ℝ :=
  chartCayleyDenominator (-step) skew * (chartCayleyDenominator step skew)⁻¹

/-- The product of two denominators, in closed form. -/
theorem chartCayleyDenominator_mul_chartCayleyDenominator (firstStep secondStep : ℝ)
    (skew : Matrix (Fin size) (Fin size) ℝ) :
    chartCayleyDenominator firstStep skew * chartCayleyDenominator secondStep skew
      = 1 - (firstStep + secondStep) • skew + (firstStep * secondStep) • (skew * skew) := by
  simp only [chartCayleyDenominator, Matrix.sub_mul, Matrix.mul_sub, Matrix.one_mul,
    Matrix.mul_one, Matrix.smul_mul, Matrix.mul_smul, add_smul]
  module

/-- The two denominators commute — both products are `1 - s²K²`. -/
theorem chartCayleyDenominator_mul_comm (step : ℝ) (skew : Matrix (Fin size) (Fin size) ℝ) :
    chartCayleyDenominator (-step) skew * chartCayleyDenominator step skew
      = chartCayleyDenominator step skew * chartCayleyDenominator (-step) skew := by
  rw [chartCayleyDenominator_mul_chartCayleyDenominator,
    chartCayleyDenominator_mul_chartCayleyDenominator, neg_add_cancel, add_neg_cancel,
    show (-step) * step = step * (-step) from by ring]

/-- **THE INVERSE INHERITS THE COMMUTATION**: `A B = B A` with `A` invertible gives
`A⁻¹ B = B A⁻¹`, read at the two denominators. -/
theorem inverse_chartCayleyDenominator_mul_comm {skew : Matrix (Fin size) (Fin size) ℝ}
    (hskew : skewᵀ = -skew) (step : ℝ) :
    (chartCayleyDenominator (-step) skew)⁻¹ * chartCayleyDenominator step skew
      = chartCayleyDenominator step skew * (chartCayleyDenominator (-step) skew)⁻¹ := by
  have hnegUnit := isUnit_det_chartCayleyDenominator hskew (-step)
  calc (chartCayleyDenominator (-step) skew)⁻¹ * chartCayleyDenominator step skew
      = (chartCayleyDenominator (-step) skew)⁻¹ * chartCayleyDenominator step skew
          * (chartCayleyDenominator (-step) skew
            * (chartCayleyDenominator (-step) skew)⁻¹) := by
        rw [Matrix.mul_nonsing_inv _ hnegUnit, Matrix.mul_one]
    _ = (chartCayleyDenominator (-step) skew)⁻¹
          * (chartCayleyDenominator (-step) skew * chartCayleyDenominator step skew)
          * (chartCayleyDenominator (-step) skew)⁻¹ := by
        rw [chartCayleyDenominator_mul_comm]
        simp only [Matrix.mul_assoc]
    _ = chartCayleyDenominator step skew * (chartCayleyDenominator (-step) skew)⁻¹ := by
        rw [← Matrix.mul_assoc, Matrix.nonsing_inv_mul _ hnegUnit, Matrix.one_mul]

/-- **THE TRANSPOSE OF THE CAYLEY TRANSFORM** is the transform at the negated step. -/
theorem transpose_chartCayley {skew : Matrix (Fin size) (Fin size) ℝ}
    (hskew : skewᵀ = -skew) (step : ℝ) :
    (chartCayley step skew)ᵀ = chartCayley (-step) skew := by
  rw [chartCayley, chartCayley, Matrix.transpose_mul, Matrix.transpose_nonsing_inv,
    transpose_chartCayleyDenominator hskew, transpose_chartCayleyDenominator hskew, neg_neg,
    inverse_chartCayleyDenominator_mul_comm hskew]

/-- **THE CAYLEY TRANSFORM IS ORTHOGONAL**, at every step: the two denominators
commute and each cancels against its own inverse. -/
theorem chartCayley_transpose_mul_self {skew : Matrix (Fin size) (Fin size) ℝ}
    (hskew : skewᵀ = -skew) (step : ℝ) :
    (chartCayley step skew)ᵀ * chartCayley step skew = 1 := by
  have hnegUnit := isUnit_det_chartCayleyDenominator hskew (-step)
  have hposUnit := isUnit_det_chartCayleyDenominator hskew step
  rw [transpose_chartCayley hskew, chartCayley, chartCayley, neg_neg]
  calc chartCayleyDenominator step skew * (chartCayleyDenominator (-step) skew)⁻¹
        * (chartCayleyDenominator (-step) skew * (chartCayleyDenominator step skew)⁻¹)
      = chartCayleyDenominator step skew
          * ((chartCayleyDenominator (-step) skew)⁻¹ * chartCayleyDenominator (-step) skew)
          * (chartCayleyDenominator step skew)⁻¹ := by
        simp only [Matrix.mul_assoc]
    _ = 1 := by
        rw [Matrix.nonsing_inv_mul _ hnegUnit, Matrix.mul_one,
          Matrix.mul_nonsing_inv _ hposUnit]

theorem chartCayley_mul_transpose_self {skew : Matrix (Fin size) (Fin size) ℝ}
    (hskew : skewᵀ = -skew) (step : ℝ) :
    chartCayley step skew * (chartCayley step skew)ᵀ = 1 :=
  mul_eq_one_comm.mpr (chartCayley_transpose_mul_self hskew step)

/-- **THE TRANSPOSE IN RESOLVENT FORM**: `Q(s)ᵀ = 2 (1 + sK)⁻¹ - 1`.  This is the
shape the frozen-probe expansion consumes, because it exhibits `Q(s)ᵀ v` as `2u - v`
with `u` the solution of `(1 + sK) u = v`. -/
theorem transpose_chartCayley_eq_two_smul_inverse_sub_one
    {skew : Matrix (Fin size) (Fin size) ℝ} (hskew : skewᵀ = -skew) (step : ℝ) :
    (chartCayley step skew)ᵀ
      = (2 : ℝ) • (chartCayleyDenominator (-step) skew)⁻¹ - 1 := by
  have hnegUnit := isUnit_det_chartCayleyDenominator hskew (-step)
  have hsplit : chartCayleyDenominator step skew
      = (2 : ℝ) • (1 : Matrix (Fin size) (Fin size) ℝ) - chartCayleyDenominator (-step) skew := by
    rw [chartCayleyDenominator, chartCayleyDenominator, neg_smul]
    module
  rw [transpose_chartCayley hskew, chartCayley, neg_neg, hsplit, Matrix.sub_mul,
    Matrix.smul_mul, Matrix.one_mul, Matrix.mul_nonsing_inv _ hnegUnit]

/-! ## The Cayley curve of charts -/

/-- **THE CAYLEY CURVE OF CHARTS** `P(s) = Q(s) P Q(s)ᵀ`: symmetric, idempotent and of
the same trace at EVERY step, and rational in the step.  This is the curve on the
Grassmannian that `Gtz.Quantitative.ChartStrongStationary` honesty (a) names as its
first missing ingredient. -/
noncomputable def chartCayleyProjection (step : ℝ)
    (skew projection : Matrix (Fin size) (Fin size) ℝ) : Matrix (Fin size) (Fin size) ℝ :=
  chartCayley step skew * projection * (chartCayley step skew)ᵀ

theorem transpose_chartCayleyProjection {projection : Matrix (Fin size) (Fin size) ℝ}
    (hsymmetric : projectionᵀ = projection) (step : ℝ)
    (skew : Matrix (Fin size) (Fin size) ℝ) :
    (chartCayleyProjection step skew projection)ᵀ
      = chartCayleyProjection step skew projection := by
  rw [chartCayleyProjection, Matrix.transpose_mul, Matrix.transpose_transpose,
    Matrix.transpose_mul, hsymmetric, ← Matrix.mul_assoc]

theorem chartCayleyProjection_mul_self {skew projection : Matrix (Fin size) (Fin size) ℝ}
    (hskew : skewᵀ = -skew) (hidempotent : projection * projection = projection) (step : ℝ) :
    chartCayleyProjection step skew projection * chartCayleyProjection step skew projection
      = chartCayleyProjection step skew projection := by
  have horthogonal := chartCayley_transpose_mul_self hskew step
  calc chartCayleyProjection step skew projection * chartCayleyProjection step skew projection
      = chartCayley step skew * projection * ((chartCayley step skew)ᵀ * chartCayley step skew)
          * (projection * (chartCayley step skew)ᵀ) := by
        simp only [chartCayleyProjection, Matrix.mul_assoc]
    _ = chartCayley step skew * (projection * projection) * (chartCayley step skew)ᵀ := by
        rw [horthogonal, Matrix.mul_one]
        simp only [Matrix.mul_assoc]
    _ = chartCayleyProjection step skew projection := by
        rw [hidempotent, chartCayleyProjection]

theorem trace_chartCayleyProjection {skew : Matrix (Fin size) (Fin size) ℝ}
    (hskew : skewᵀ = -skew) (step : ℝ) (projection : Matrix (Fin size) (Fin size) ℝ) :
    Matrix.trace (chartCayleyProjection step skew projection) = Matrix.trace projection := by
  rw [chartCayleyProjection,
    Matrix.trace_mul_comm (chartCayley step skew * projection) (chartCayley step skew)ᵀ,
    ← Matrix.mul_assoc, chartCayley_transpose_mul_self hskew step, Matrix.one_mul]

/-! ## The frozen-probe expansion

The step from a tangent direction to an actual decrease of the objective, and the
place where the argument is one-sided on purpose: a FIXED probe gives an UPPER bound
on the block's least eigenvalue, which is exactly the direction a descent argument
needs, and exactly the direction in which a frozen probe is USELESS for rigidity —
see `Gtz.stratumCriticalRay_not_posSemidef`, the shipped counterexample to reading a
frozen-probe second-order coefficient as convexity. -/

/-- Scalars pull out of a matrix-vector product. -/
theorem smul_mulVec_eq_smul_mulVec (scale : ℝ) (target : Matrix (Fin size) (Fin size) ℝ)
    (probe : Fin size → ℝ) : (scale • target) *ᵥ probe = scale • (target *ᵥ probe) := by
  funext atomIndex
  simp only [Matrix.mulVec, dotProduct, Matrix.smul_apply, Pi.smul_apply, smul_eq_mul,
    Finset.mul_sum]
  exact Finset.sum_congr rfl fun colIndex _ => by ring

/-- A symmetric matrix moves across the dot product. -/
theorem dotProduct_mulVec_comm_of_symmetric {target : Matrix (Fin size) (Fin size) ℝ}
    (hsymmetric : targetᵀ = target) (leftVec rightVec : Fin size → ℝ) :
    leftVec ⬝ᵥ (target *ᵥ rightVec) = rightVec ⬝ᵥ (target *ᵥ leftVec) := by
  have hadjoint := dotProduct_mulVec_transpose target leftVec rightVec
  rw [hsymmetric] at hadjoint
  rw [← hadjoint, dotProduct_comm]

/-- **THE COMMUTATOR FORM IS TWICE THE MIXED FORM**, with a sign: for symmetric `P` and
skew `K`, `⟨v, [K,P] v⟩ = -2 ⟨v, P K v⟩`.  This is what turns the curve's first-order
coefficient into the shipped tangent slope. -/
theorem dotProduct_mulVec_commutator_eq {skew projection : Matrix (Fin size) (Fin size) ℝ}
    (hskew : skewᵀ = -skew) (hsymmetric : projectionᵀ = projection) (probe : Fin size → ℝ) :
    probe ⬝ᵥ ((skew * projection - projection * skew) *ᵥ probe)
      = -2 * (probe ⬝ᵥ ((projection * skew) *ᵥ probe)) := by
  have hswap : probe ⬝ᵥ ((skew * projection) *ᵥ probe)
      = -(probe ⬝ᵥ ((projection * skew) *ᵥ probe)) := by
    have hadjoint := dotProduct_mulVec_transpose (skew * projection) probe probe
    rw [Matrix.transpose_mul, hskew, hsymmetric, Matrix.mul_neg, Matrix.neg_mulVec,
      neg_dotProduct, dotProduct_comm] at hadjoint
    linarith
  rw [Matrix.sub_mulVec, dotProduct_sub, hswap]
  ring

/-- **THE PULLED PROBE** `u = (1 + sK)⁻¹ v`, the solution of `u + sKu = v`.  The whole
expansion is bookkeeping around this one vector. -/
noncomputable def chartCayleyPull (step : ℝ) (skew : Matrix (Fin size) (Fin size) ℝ)
    (probe : Fin size → ℝ) : Fin size → ℝ :=
  (chartCayleyDenominator (-step) skew)⁻¹ *ᵥ probe

theorem chartCayleyPull_dotProduct_self_le {skew : Matrix (Fin size) (Fin size) ℝ}
    (hskew : skewᵀ = -skew) (step : ℝ) (probe : Fin size → ℝ) :
    chartCayleyPull step skew probe ⬝ᵥ chartCayleyPull step skew probe ≤ probe ⬝ᵥ probe :=
  inverse_chartCayleyDenominator_contraction hskew (-step) probe

/-- The defining equation of the pulled probe, as a drift identity. -/
theorem chartCayleyPull_sub_eq {skew : Matrix (Fin size) (Fin size) ℝ}
    (hskew : skewᵀ = -skew) (step : ℝ) (probe : Fin size → ℝ) :
    chartCayleyPull step skew probe - probe
      = -(step • (skew *ᵥ chartCayleyPull step skew probe)) := by
  have hnegUnit := isUnit_det_chartCayleyDenominator hskew (-step)
  have hsolve : chartCayleyDenominator (-step) skew *ᵥ chartCayleyPull step skew probe = probe := by
    rw [chartCayleyPull, Matrix.mulVec_mulVec, Matrix.mul_nonsing_inv _ hnegUnit,
      Matrix.one_mulVec]
  rw [chartCayleyDenominator_mulVec, neg_smul, sub_neg_eq_add] at hsolve
  calc chartCayleyPull step skew probe - probe
      = chartCayleyPull step skew probe
        - (chartCayleyPull step skew probe
          + step • (skew *ᵥ chartCayleyPull step skew probe)) := by rw [hsolve]
    _ = -(step • (skew *ᵥ chartCayleyPull step skew probe)) := by abel

/-- **THE OFFSET** `Q(s)ᵀ v - v`, which the expansion shows is `-2s K u`. -/
noncomputable def chartCayleyOffset (step : ℝ) (skew : Matrix (Fin size) (Fin size) ℝ)
    (probe : Fin size → ℝ) : Fin size → ℝ :=
  (chartCayley step skew)ᵀ *ᵥ probe - probe

theorem chartCayleyOffset_eq {skew : Matrix (Fin size) (Fin size) ℝ}
    (hskew : skewᵀ = -skew) (step : ℝ) (probe : Fin size → ℝ) :
    chartCayleyOffset step skew probe
      = -((2 * step) • (skew *ᵥ chartCayleyPull step skew probe)) := by
  have htransform : (chartCayley step skew)ᵀ *ᵥ probe
      = (2 : ℝ) • chartCayleyPull step skew probe - probe := by
    rw [transpose_chartCayley_eq_two_smul_inverse_sub_one hskew, Matrix.sub_mulVec,
      Matrix.one_mulVec, smul_mulVec_eq_smul_mulVec, chartCayleyPull]
  have hdrift := chartCayleyPull_sub_eq hskew step probe
  rw [chartCayleyOffset, htransform]
  have hrewrite : (2 : ℝ) • chartCayleyPull step skew probe - probe - probe
      = (2 : ℝ) • (chartCayleyPull step skew probe - probe) := by
    rw [smul_sub]
    module
  rw [hrewrite, hdrift, smul_neg, smul_smul]

/-- A negated scaled vector's self-product. -/
theorem neg_smul_dotProduct_self (scale : ℝ) (vector : Fin size → ℝ) :
    (-(scale • vector)) ⬝ᵥ (-(scale • vector)) = scale ^ 2 * (vector ⬝ᵥ vector) := by
  rw [neg_dotProduct, dotProduct_neg, neg_neg, smul_dotProduct, dotProduct_smul, smul_eq_mul,
    smul_eq_mul]
  ring

/-- **THE EXPANSION, EXACTLY.**  The Rayleigh quotient of a frozen probe along the
Cayley curve splits into the base quotient, the first-order commutator term, and two
remainder terms — a cross term against the pull's drift and the offset's own quotient.
No inequality and no smallness anywhere: this is an identity at every step. -/
theorem chartCayleyProjection_form_eq {skew projection : Matrix (Fin size) (Fin size) ℝ}
    (hskew : skewᵀ = -skew) (hsymmetric : projectionᵀ = projection)
    (step : ℝ) (probe : Fin size → ℝ) :
    probe ⬝ᵥ (chartCayleyProjection step skew projection *ᵥ probe)
      = probe ⬝ᵥ (projection *ᵥ probe)
        + 2 * step * (probe ⬝ᵥ ((skew * projection - projection * skew) *ᵥ probe))
        - 4 * step
            * (probe ⬝ᵥ (projection *ᵥ (skew *ᵥ (chartCayleyPull step skew probe - probe))))
        + chartCayleyOffset step skew probe
            ⬝ᵥ (projection *ᵥ chartCayleyOffset step skew probe) := by
  have hmoved : probe ⬝ᵥ (chartCayleyProjection step skew projection *ᵥ probe)
      = ((chartCayley step skew)ᵀ *ᵥ probe)
        ⬝ᵥ (projection *ᵥ ((chartCayley step skew)ᵀ *ᵥ probe)) := by
    rw [chartCayleyProjection, ← Matrix.mulVec_mulVec, ← Matrix.mulVec_mulVec,
      ← dotProduct_mulVec_transpose (chartCayley step skew) probe
        (projection *ᵥ ((chartCayley step skew)ᵀ *ᵥ probe))]
  have hshift : (chartCayley step skew)ᵀ *ᵥ probe
      = probe + chartCayleyOffset step skew probe := by
    rw [chartCayleyOffset]
    abel
  have hcross : chartCayleyOffset step skew probe ⬝ᵥ (projection *ᵥ probe)
      = probe ⬝ᵥ (projection *ᵥ chartCayleyOffset step skew probe) :=
    dotProduct_mulVec_comm_of_symmetric hsymmetric _ _
  have hoffsetForm : probe ⬝ᵥ (projection *ᵥ chartCayleyOffset step skew probe)
      = -(2 * step) * (probe ⬝ᵥ (projection *ᵥ (skew *ᵥ chartCayleyPull step skew probe))) := by
    rw [chartCayleyOffset_eq hskew, Matrix.mulVec_neg, Matrix.mulVec_smul, dotProduct_neg,
      dotProduct_smul, smul_eq_mul]
    ring
  have hpullSplit : skew *ᵥ chartCayleyPull step skew probe
      = skew *ᵥ probe + skew *ᵥ (chartCayleyPull step skew probe - probe) := by
    rw [← Matrix.mulVec_add]
    congr 1
    abel
  have hmainForm : probe ⬝ᵥ (projection *ᵥ (skew *ᵥ probe))
      = probe ⬝ᵥ ((projection * skew) *ᵥ probe) := by
    rw [Matrix.mulVec_mulVec]
  have hcommutator := dotProduct_mulVec_commutator_eq hskew hsymmetric probe
  rw [hmoved, hshift, Matrix.mulVec_add, dotProduct_add, add_dotProduct, add_dotProduct, hcross,
    hoffsetForm, hpullSplit, Matrix.mulVec_add, dotProduct_add, hmainForm, hcommutator]
  ring

/-- **THE REMAINDER IS SECOND ORDER.**  Along the Cayley curve a FIXED unit probe's
Rayleigh quotient against the chart is the base quotient plus `2s ⟨v, [K,P] v⟩`, with an
error at most `8 s² ‖K‖_F²`.

Only elementary inequalities enter: Cauchy–Schwarz on the raw dot product, the
resolvent contraction `|(1 + sK)⁻¹ v| ≤ |v|`, and the fact that an orthogonal
projection contracts.  No operator norm, no eigenvalue, no derivative. -/
theorem abs_chartCayleyProjection_form_sub_le
    {skew projection : Matrix (Fin size) (Fin size) ℝ}
    (hskew : skewᵀ = -skew) (hsymmetric : projectionᵀ = projection)
    (hidempotent : projection * projection = projection)
    (step : ℝ) {probe : Fin size → ℝ} (hunit : probe ⬝ᵥ probe = 1) :
    |probe ⬝ᵥ (chartCayleyProjection step skew projection *ᵥ probe)
        - (probe ⬝ᵥ (projection *ᵥ probe)
          + 2 * step * (probe ⬝ᵥ ((skew * projection - projection * skew) *ᵥ probe)))|
      ≤ 8 * step ^ 2 * chartFrobeniusSquare skew := by
  have hcapNonneg := chartFrobeniusSquare_nonneg skew
  have hpullNorm : chartCayleyPull step skew probe ⬝ᵥ chartCayleyPull step skew probe ≤ 1 := by
    have hbound := chartCayleyPull_dotProduct_self_le hskew step probe
    rw [hunit] at hbound
    exact hbound
  have hskewPullNorm : (skew *ᵥ chartCayleyPull step skew probe)
      ⬝ᵥ (skew *ᵥ chartCayleyPull step skew probe) ≤ chartFrobeniusSquare skew := by
    have hbound := mulVec_dotProduct_self_le_chartFrobeniusSquare skew
      (chartCayleyPull step skew probe)
    nlinarith [dotProduct_self_nonneg (chartCayleyPull step skew probe)]
  have hdriftNorm : (chartCayleyPull step skew probe - probe)
      ⬝ᵥ (chartCayleyPull step skew probe - probe)
      ≤ step ^ 2 * chartFrobeniusSquare skew := by
    rw [chartCayleyPull_sub_eq hskew, neg_smul_dotProduct_self]
    nlinarith [sq_nonneg step]
  have hoffsetNorm : chartCayleyOffset step skew probe ⬝ᵥ chartCayleyOffset step skew probe
      ≤ 4 * step ^ 2 * chartFrobeniusSquare skew := by
    rw [chartCayleyOffset_eq hskew, neg_smul_dotProduct_self]
    nlinarith [sq_nonneg step]
  have hselfTermLower : 0 ≤ chartCayleyOffset step skew probe
      ⬝ᵥ (projection *ᵥ chartCayleyOffset step skew probe) :=
    dotProduct_mulVec_nonneg_of_symmetricIdempotent hsymmetric hidempotent _
  have hselfTermUpper : chartCayleyOffset step skew probe
      ⬝ᵥ (projection *ᵥ chartCayleyOffset step skew probe)
      ≤ 4 * step ^ 2 * chartFrobeniusSquare skew := by
    have hcontract := dotProduct_mulVec_le_self_of_symmetricIdempotent hsymmetric hidempotent
      (chartCayleyOffset step skew probe)
    linarith
  have hstepSq : |step| * |step| = step ^ 2 := by rw [abs_mul_abs_self]; ring
  have hcrossSq : (probe ⬝ᵥ (projection *ᵥ (skew *ᵥ (chartCayleyPull step skew probe - probe)))) ^ 2
      ≤ (chartFrobeniusSquare skew * |step|) ^ 2 := by
    have hcauchy := dotProduct_sq_le_mul probe
      (projection *ᵥ (skew *ᵥ (chartCayleyPull step skew probe - probe)))
    rw [hunit, one_mul] at hcauchy
    have hproject := mulVec_dotProduct_self_le_of_symmetricIdempotent hsymmetric hidempotent
      (skew *ᵥ (chartCayleyPull step skew probe - probe))
    have hskewImage := mulVec_dotProduct_self_le_chartFrobeniusSquare skew
      (chartCayleyPull step skew probe - probe)
    have hlast : chartFrobeniusSquare skew
        * ((chartCayleyPull step skew probe - probe) ⬝ᵥ (chartCayleyPull step skew probe - probe))
        ≤ (chartFrobeniusSquare skew * |step|) ^ 2 := by
      have hscaled : chartFrobeniusSquare skew
          * ((chartCayleyPull step skew probe - probe)
            ⬝ᵥ (chartCayleyPull step skew probe - probe))
          ≤ chartFrobeniusSquare skew * (step ^ 2 * chartFrobeniusSquare skew) :=
        mul_le_mul_of_nonneg_left hdriftNorm hcapNonneg
      calc chartFrobeniusSquare skew
            * ((chartCayleyPull step skew probe - probe)
              ⬝ᵥ (chartCayleyPull step skew probe - probe))
          ≤ chartFrobeniusSquare skew * (step ^ 2 * chartFrobeniusSquare skew) := hscaled
        _ = (chartFrobeniusSquare skew * |step|) ^ 2 := by rw [← hstepSq]; ring
    linarith
  have hcrossAbs :
      |probe ⬝ᵥ (projection *ᵥ (skew *ᵥ (chartCayleyPull step skew probe - probe)))|
        ≤ chartFrobeniusSquare skew * |step| :=
    abs_le_of_sq_le_sq_of_nonneg hcrossSq (mul_nonneg hcapNonneg (abs_nonneg step))
  have hsplit : probe ⬝ᵥ (chartCayleyProjection step skew projection *ᵥ probe)
        - (probe ⬝ᵥ (projection *ᵥ probe)
          + 2 * step * (probe ⬝ᵥ ((skew * projection - projection * skew) *ᵥ probe)))
      = -4 * step
          * (probe ⬝ᵥ (projection *ᵥ (skew *ᵥ (chartCayleyPull step skew probe - probe))))
        + chartCayleyOffset step skew probe
            ⬝ᵥ (projection *ᵥ chartCayleyOffset step skew probe) := by
    rw [chartCayleyProjection_form_eq hskew hsymmetric]
    ring
  rw [hsplit]
  have hcrossScaled : |(-4 : ℝ) * step
      * (probe ⬝ᵥ (projection *ᵥ (skew *ᵥ (chartCayleyPull step skew probe - probe))))|
      ≤ 4 * step ^ 2 * chartFrobeniusSquare skew := by
    have hleftAbs : |(-4 : ℝ) * step| ≤ 4 * |step| := by rw [abs_mul]; norm_num
    have hproduct : |(-4 : ℝ) * step
        * (probe ⬝ᵥ (projection *ᵥ (skew *ᵥ (chartCayleyPull step skew probe - probe))))|
        ≤ 4 * |step| * (chartFrobeniusSquare skew * |step|) := by
      rw [abs_mul]
      exact mul_le_mul hleftAbs hcrossAbs (abs_nonneg _)
        (le_trans (abs_nonneg _) hleftAbs)
    calc |(-4 : ℝ) * step
          * (probe ⬝ᵥ (projection *ᵥ (skew *ᵥ (chartCayleyPull step skew probe - probe))))|
        ≤ 4 * |step| * (chartFrobeniusSquare skew * |step|) := hproduct
      _ = 4 * step ^ 2 * chartFrobeniusSquare skew := by rw [← hstepSq]; ring
  rw [abs_le] at hcrossScaled ⊢
  constructor <;> linarith [hcrossScaled.1, hcrossScaled.2, hselfTermLower, hselfTermUpper]

/-! ## The curve stays close to its base point

An entrywise estimate LINEAR in the step, so that a merely LOCAL minimality hypothesis
suffices.  Nothing below needs it — the chain supplies a global minimum — but without it
the reader cannot tell whether the argument is local or global, and the honest answer is
that it is local. -/

/-- The Cayley transform preserves squared lengths. -/
theorem chartCayley_mulVec_dotProduct_self {skew : Matrix (Fin size) (Fin size) ℝ}
    (hskew : skewᵀ = -skew) (step : ℝ) (probe : Fin size → ℝ) :
    (chartCayley step skew *ᵥ probe) ⬝ᵥ (chartCayley step skew *ᵥ probe) = probe ⬝ᵥ probe := by
  have hadjoint := dotProduct_mulVec_transpose (chartCayley step skew)
    (chartCayley step skew *ᵥ probe) probe
  rw [Matrix.mulVec_mulVec, chartCayley_transpose_mul_self hskew step, Matrix.one_mulVec,
    dotProduct_comm] at hadjoint
  exact hadjoint.symm

/-- **THE OFFSET IS FIRST ORDER IN THE STEP**, at every probe. -/
theorem chartCayleyOffset_dotProduct_self_le {skew : Matrix (Fin size) (Fin size) ℝ}
    (hskew : skewᵀ = -skew) (step : ℝ) (probe : Fin size → ℝ) :
    chartCayleyOffset step skew probe ⬝ᵥ chartCayleyOffset step skew probe
      ≤ 4 * step ^ 2 * chartFrobeniusSquare skew * (probe ⬝ᵥ probe) := by
  have hcapNonneg := chartFrobeniusSquare_nonneg skew
  have hpullNorm := chartCayleyPull_dotProduct_self_le hskew step probe
  have hskewImage := mulVec_dotProduct_self_le_chartFrobeniusSquare skew
    (chartCayleyPull step skew probe)
  rw [chartCayleyOffset_eq hskew, neg_smul_dotProduct_self]
  calc (2 * step) ^ 2
        * ((skew *ᵥ chartCayleyPull step skew probe) ⬝ᵥ (skew *ᵥ chartCayleyPull step skew probe))
      ≤ (2 * step) ^ 2
          * (chartFrobeniusSquare skew
            * (chartCayleyPull step skew probe ⬝ᵥ chartCayleyPull step skew probe)) :=
        mul_le_mul_of_nonneg_left hskewImage (sq_nonneg _)
    _ ≤ (2 * step) ^ 2 * (chartFrobeniusSquare skew * (probe ⬝ᵥ probe)) := by
        have hinner := mul_le_mul_of_nonneg_left hpullNorm hcapNonneg
        exact mul_le_mul_of_nonneg_left hinner (sq_nonneg _)
    _ = 4 * step ^ 2 * chartFrobeniusSquare skew * (probe ⬝ᵥ probe) := by ring

/-- The parallelogram cap: `|a + b|² ≤ 2|a|² + 2|b|²`. -/
theorem add_dotProduct_self_le_two_mul (leftVec rightVec : Fin size → ℝ) :
    (leftVec + rightVec) ⬝ᵥ (leftVec + rightVec)
      ≤ 2 * (leftVec ⬝ᵥ leftVec) + 2 * (rightVec ⬝ᵥ rightVec) := by
  have hgap : 0 ≤ (leftVec - rightVec) ⬝ᵥ (leftVec - rightVec) :=
    dotProduct_self_nonneg _
  rw [dotProduct_sub, sub_dotProduct, sub_dotProduct] at hgap
  rw [dotProduct_add, add_dotProduct, add_dotProduct]
  have hsymmetry : rightVec ⬝ᵥ leftVec = leftVec ⬝ᵥ rightVec := dotProduct_comm _ _
  linarith [hsymmetry]

/-- **THE CURVE'S DISPLACEMENT, on a probe**: the difference of the two charts splits
into two offsets, one on each side. -/
theorem chartCayleyProjection_sub_mulVec {skew projection : Matrix (Fin size) (Fin size) ℝ}
    (hskew : skewᵀ = -skew) (step : ℝ) (probe : Fin size → ℝ) :
    (chartCayleyProjection step skew projection *ᵥ probe) - (projection *ᵥ probe)
      = chartCayleyOffset (-step) skew (projection *ᵥ probe)
        + chartCayley step skew *ᵥ (projection *ᵥ chartCayleyOffset step skew probe) := by
  have htransposeBack : (chartCayley (-step) skew)ᵀ = chartCayley step skew := by
    rw [transpose_chartCayley hskew, neg_neg]
  rw [chartCayleyOffset, chartCayleyOffset, htransposeBack, chartCayleyProjection,
    ← Matrix.mulVec_mulVec, ← Matrix.mulVec_mulVec, Matrix.mulVec_sub, Matrix.mulVec_sub]
  abel

/-- **THE CURVE IS ENTRYWISE LIPSCHITZ IN THE STEP**, squared form.  A merely local
minimality hypothesis therefore suffices, and this is the estimate that says so. -/
theorem sq_chartCayleyProjection_sub_entry_le {skew projection : Matrix (Fin size) (Fin size) ℝ}
    (hskew : skewᵀ = -skew) (hsymmetric : projectionᵀ = projection)
    (hidempotent : projection * projection = projection) (step : ℝ)
    (rowIndex colIndex : Fin size) :
    (chartCayleyProjection step skew projection rowIndex colIndex
        - projection rowIndex colIndex) ^ 2
      ≤ 16 * step ^ 2 * chartFrobeniusSquare skew := by
  classical
  have hcapNonneg := chartFrobeniusSquare_nonneg skew
  set columnProbe : Fin size → ℝ := Pi.single colIndex 1 with hcolumnProbe
  set rowProbe : Fin size → ℝ := Pi.single rowIndex 1 with hrowProbe
  have hunitProbe : ∀ pivotIndex : Fin size,
      (Pi.single pivotIndex (1 : ℝ)) ⬝ᵥ (Pi.single pivotIndex (1 : ℝ)) = 1 := by
    intro pivotIndex
    simp [dotProduct, Pi.single_apply]
  have hentry : ∀ target : Matrix (Fin size) (Fin size) ℝ,
      rowProbe ⬝ᵥ (target *ᵥ columnProbe) = target rowIndex colIndex := by
    intro target
    simp [hrowProbe, hcolumnProbe, dotProduct, Matrix.mulVec, Pi.single_apply]
  have hdisplacement :=
    chartCayleyProjection_sub_mulVec (projection := projection) hskew step columnProbe
  set firstPart : Fin size → ℝ := chartCayleyOffset (-step) skew (projection *ᵥ columnProbe)
    with hfirstPart
  set secondPart : Fin size → ℝ :=
    chartCayley step skew *ᵥ (projection *ᵥ chartCayleyOffset step skew columnProbe)
    with hsecondPart
  have hfirstNorm : firstPart ⬝ᵥ firstPart ≤ 4 * step ^ 2 * chartFrobeniusSquare skew := by
    have hbound := chartCayleyOffset_dotProduct_self_le hskew (-step) (projection *ᵥ columnProbe)
    have hcontract := mulVec_dotProduct_self_le_of_symmetricIdempotent hsymmetric hidempotent
      columnProbe
    rw [hunitProbe colIndex] at hcontract
    have hstepSq : (-step) ^ 2 = step ^ 2 := by ring
    rw [hstepSq] at hbound
    have hscale : 4 * step ^ 2 * chartFrobeniusSquare skew
        * ((projection *ᵥ columnProbe) ⬝ᵥ (projection *ᵥ columnProbe))
        ≤ 4 * step ^ 2 * chartFrobeniusSquare skew * 1 :=
      mul_le_mul_of_nonneg_left hcontract
        (mul_nonneg (by positivity : (0 : ℝ) ≤ 4 * step ^ 2) hcapNonneg)
    rw [hfirstPart]
    linarith
  have hsecondNorm : secondPart ⬝ᵥ secondPart ≤ 4 * step ^ 2 * chartFrobeniusSquare skew := by
    rw [hsecondPart, chartCayley_mulVec_dotProduct_self hskew]
    have hcontract := mulVec_dotProduct_self_le_of_symmetricIdempotent hsymmetric hidempotent
      (chartCayleyOffset step skew columnProbe)
    have hoffset := chartCayleyOffset_dotProduct_self_le hskew step columnProbe
    rw [hunitProbe colIndex] at hoffset
    linarith
  have hsum : (chartCayleyProjection step skew projection *ᵥ columnProbe
        - projection *ᵥ columnProbe)
      ⬝ᵥ (chartCayleyProjection step skew projection *ᵥ columnProbe - projection *ᵥ columnProbe)
      ≤ 16 * step ^ 2 * chartFrobeniusSquare skew := by
    rw [hdisplacement]
    have hcap := add_dotProduct_self_le_two_mul firstPart secondPart
    linarith
  have hcauchy := dotProduct_sq_le_mul rowProbe
    (chartCayleyProjection step skew projection *ᵥ columnProbe - projection *ᵥ columnProbe)
  rw [hunitProbe rowIndex, one_mul] at hcauchy
  have hextract : rowProbe ⬝ᵥ (chartCayleyProjection step skew projection *ᵥ columnProbe
      - projection *ᵥ columnProbe)
      = chartCayleyProjection step skew projection rowIndex colIndex
        - projection rowIndex colIndex := by
    rw [← Matrix.sub_mulVec, hentry]
    simp
  rw [hextract] at hcauchy
  linarith

/-! ## From a tangent direction to a curve

`Gtz.IsChartTangent` is a definition, and the identification with a manifold tangent
space is the reader's.  What is proved here is the only thing the descent argument
needs from that identification: the skew generator `K = ½ [Pdot, P]` produces a Cayley
curve whose first-order term IS `Pdot`, and the curve lies in the constraint set. -/

/-- **THE SKEW GENERATOR OF A TANGENT DIRECTION**, `K = ½ [Pdot, P]`. -/
noncomputable def chartTangentSkew (projection directionMatrix : Matrix (Fin size) (Fin size) ℝ) :
    Matrix (Fin size) (Fin size) ℝ :=
  (2 : ℝ)⁻¹ • (directionMatrix * projection - projection * directionMatrix)

theorem transpose_chartTangentSkew {projection directionMatrix : Matrix (Fin size) (Fin size) ℝ}
    (hsymmetric : projectionᵀ = projection) (hdirectionSymmetric : directionMatrixᵀ = directionMatrix) :
    (chartTangentSkew projection directionMatrix)ᵀ
      = -chartTangentSkew projection directionMatrix := by
  rw [chartTangentSkew, Matrix.transpose_smul, Matrix.transpose_sub, Matrix.transpose_mul,
    Matrix.transpose_mul, hsymmetric, hdirectionSymmetric, ← smul_neg]
  congr 1
  abel

/-- **THE CURVE'S FIRST-ORDER TERM IS THE DIRECTION.**  `[K, P] = ½ Pdot` exactly when
the direction's two diagonal blocks vanish, which is what `Gtz.IsChartTangent` says.  The
factor `½` is absorbed by the transform's own factor of two, so the curve's derivative is
`Pdot` on the nose. -/
theorem chartTangentSkew_commutator {projection directionMatrix : Matrix (Fin size) (Fin size) ℝ}
    {directionWeight : Fin size → ℝ}
    (hidempotent : projection * projection = projection)
    (htangent : IsChartTangent projection directionMatrix directionWeight) :
    chartTangentSkew projection directionMatrix * projection
        - projection * chartTangentSkew projection directionMatrix
      = (2 : ℝ)⁻¹ • directionMatrix := by
  have hfull : directionMatrix
      = projection * directionMatrix * projection
        + projection * directionMatrix * (1 - projection)
        + (1 - projection) * directionMatrix * projection
        + (1 - projection) * directionMatrix * (1 - projection) := by
    simp only [Matrix.sub_mul, Matrix.mul_sub, Matrix.one_mul, Matrix.mul_one]
    abel
  have hoffSum : projection * directionMatrix * (1 - projection)
      + (1 - projection) * directionMatrix * projection = directionMatrix := by
    conv_rhs => rw [hfull, htangent.rangeBlock_eq_zero, htangent.kernelBlock_eq_zero]
    abel
  have hanticommutator : projection * directionMatrix + directionMatrix * projection
      = directionMatrix := by
    have hexpand : projection * directionMatrix * (1 - projection)
        + (1 - projection) * directionMatrix * projection
        = projection * directionMatrix + directionMatrix * projection
          - projection * directionMatrix * projection
          - projection * directionMatrix * projection := by
      simp only [Matrix.mul_sub, Matrix.sub_mul, Matrix.mul_one, Matrix.one_mul]
      abel
    rw [hexpand, htangent.rangeBlock_eq_zero, sub_zero, sub_zero] at hoffSum
    exact hoffSum
  rw [chartTangentSkew, Matrix.smul_mul, Matrix.mul_smul, ← smul_sub]
  congr 1
  have hleft : (directionMatrix * projection - projection * directionMatrix) * projection
      = directionMatrix * projection - projection * directionMatrix * projection := by
    rw [Matrix.sub_mul, Matrix.mul_assoc, hidempotent]
  have hright : projection * (directionMatrix * projection - projection * directionMatrix)
      = projection * directionMatrix * projection - projection * directionMatrix := by
    rw [Matrix.mul_sub, ← Matrix.mul_assoc, ← Matrix.mul_assoc, hidempotent]
  rw [hleft, hright, htangent.rangeBlock_eq_zero, sub_zero, zero_sub, sub_neg_eq_add, add_comm]
  exact hanticommutator

/-- **THE TANGENT CURVE OF CHARTS**: the Cayley curve generated by a tangent direction.
Symmetric, idempotent and of the same trace at every step. -/
noncomputable def chartTangentCurve (step : ℝ)
    (projection directionMatrix : Matrix (Fin size) (Fin size) ℝ) :
    Matrix (Fin size) (Fin size) ℝ :=
  chartCayleyProjection step (chartTangentSkew projection directionMatrix) projection

/-- **THE TANGENT CURVE OF WEIGHTS**: the straight line inside the simplex. -/
def chartCayleyWeight (step : ℝ) (weight directionWeight : Fin size → ℝ) : Fin size → ℝ :=
  fun atomIndex => weight atomIndex + step * directionWeight atomIndex

theorem sum_chartCayleyWeight_eq {weight directionWeight : Fin size → ℝ}
    (hdirectionSum : ∑ atomIndex : Fin size, directionWeight atomIndex = 0) (step : ℝ) :
    ∑ atomIndex : Fin size, chartCayleyWeight step weight directionWeight atomIndex
      = ∑ atomIndex : Fin size, weight atomIndex := by
  simp only [chartCayleyWeight]
  rw [Finset.sum_add_distrib, ← Finset.mul_sum, hdirectionSum, mul_zero, add_zero]

/-- The chart gap's quadratic form, unfolded.  Definitionally `Gtz.chartTangentSlope`
evaluated at the POINT rather than at a direction — the gap map is affine, so the same
expression serves both. -/
theorem dotProduct_chartStationaryGap_mulVec_eq (chartMatrix : Matrix (Fin size) (Fin size) ℝ)
    (chartWeight probe : Fin size → ℝ) :
    probe ⬝ᵥ (chartStationaryGap chartMatrix chartWeight *ᵥ probe)
      = probe ⬝ᵥ (chartMatrix *ᵥ probe)
        - ∑ atomIndex : Fin size, chartWeight atomIndex * probe atomIndex ^ 2 :=
  chartTangentSlope_eq_sub probe chartMatrix chartWeight

/-- **THE MOVED GAP, TO FIRST ORDER.**  Along the tangent curve a FIXED unit probe's gap
quotient is the base quotient plus `step` times the SHIPPED tangent slope
`Gtz.chartTangentSlope`, with a second-order remainder.  The weight leg is exact — the
gap is affine in the weights — so the whole remainder comes from the Grassmannian leg. -/
theorem abs_chartTangentCurve_gap_form_sub_le
    {projection directionMatrix : Matrix (Fin size) (Fin size) ℝ}
    {weight directionWeight : Fin size → ℝ}
    (hsymmetric : projectionᵀ = projection) (hidempotent : projection * projection = projection)
    (htangent : IsChartTangent projection directionMatrix directionWeight)
    (step : ℝ) {probe : Fin size → ℝ} (hunit : probe ⬝ᵥ probe = 1) :
    |probe ⬝ᵥ (chartStationaryGap (chartTangentCurve step projection directionMatrix)
          (chartCayleyWeight step weight directionWeight) *ᵥ probe)
        - (probe ⬝ᵥ (chartStationaryGap projection weight *ᵥ probe)
          + step * chartTangentSlope probe directionMatrix directionWeight)|
      ≤ 8 * step ^ 2 * chartFrobeniusSquare (chartTangentSkew projection directionMatrix) := by
  have hskewGenerator := transpose_chartTangentSkew hsymmetric htangent.isSymmetric
  have hexpansion :=
    abs_chartCayleyProjection_form_sub_le hskewGenerator hsymmetric hidempotent step hunit
  have hcommutatorForm : probe ⬝ᵥ ((chartTangentSkew projection directionMatrix * projection
        - projection * chartTangentSkew projection directionMatrix) *ᵥ probe)
      = (2 : ℝ)⁻¹ * (probe ⬝ᵥ (directionMatrix *ᵥ probe)) := by
    rw [chartTangentSkew_commutator hidempotent htangent, smul_mulVec_eq_smul_mulVec,
      dotProduct_smul, smul_eq_mul]
  rw [hcommutatorForm] at hexpansion
  have hweightSplit : ∑ atomIndex : Fin size,
      chartCayleyWeight step weight directionWeight atomIndex * probe atomIndex ^ 2
      = (∑ atomIndex : Fin size, weight atomIndex * probe atomIndex ^ 2)
        + step * ∑ atomIndex : Fin size, directionWeight atomIndex * probe atomIndex ^ 2 := by
    rw [Finset.mul_sum, ← Finset.sum_add_distrib]
    exact Finset.sum_congr rfl fun atomIndex _ => by rw [chartCayleyWeight]; ring
  rw [dotProduct_chartStationaryGap_mulVec_eq, dotProduct_chartStationaryGap_mulVec_eq,
    chartTangentSlope_eq_sub, hweightSplit, chartTangentCurve]
  rw [abs_le] at hexpansion ⊢
  exact ⟨by linarith [hexpansion.1], by linarith [hexpansion.2]⟩

/-! ## Domination at a value, and the objective read without an eigenvalue -/

/-- **A BLOCK DOMINATES AT A VALUE**: the chart gap's quadratic form is at least `value`
times the squared length at every probe supported in the block.  In the submatrix reading
this is `lambda_min(W[C]) >= value`.

Stated ambiently, matching `Gtz.ChartDominates` (which is this at `value = 0`) and
`Gtz.IsChartArgmaxValue`; that the ambient quotient IS the block's is the same fact
`Gtz.chartTangentSlope_eq_subset_double_sum` proves for directions.  No `Gtz.lambdaMinMat`
and no submatrix reindexing appears anywhere below. -/
def ChartBlockDominatesAtValue (projection : Matrix (Fin size) (Fin size) ℝ)
    (weight : Fin size → ℝ) (value : ℝ) (chosenSubset : Finset (Fin size)) : Prop :=
  ∀ probe : Fin size → ℝ,
    (∀ atomIndex : Fin size, atomIndex ∉ chosenSubset → probe atomIndex = 0) →
    value * (probe ⬝ᵥ probe) ≤ probe ⬝ᵥ (chartStationaryGap projection weight *ᵥ probe)

/-- **THE CHART OBJECTIVE IS AT LEAST `value`** at a chart point: some `rank`-subset
dominates there at that value.  This is `G(P, t) >= value` written without `G`, and it is
the only form of the objective the minimality hypothesis below needs. -/
def HasChartDominatingSubsetAtValue (rank : ℕ) (projection : Matrix (Fin size) (Fin size) ℝ)
    (weight : Fin size → ℝ) (value : ℝ) : Prop :=
  ∃ chosenSubset : Finset (Fin size), chosenSubset.card = rank
    ∧ ChartBlockDominatesAtValue projection weight value chosenSubset

variable {projection : Matrix (Fin size) (Fin size) ℝ} {weight : Fin size → ℝ} {value : ℝ}

/-- **ONE UNIT PROBE STRICTLY BELOW THE VALUE REFUTES DOMINATION.**  This is where the
"Rayleigh quotient is an exact upper bound for the least eigenvalue" step lives, and in
the ambient phrasing it is not a lemma about eigenvalues at all — it is the definition
read at a single probe. -/
theorem not_chartBlockDominatesAtValue_of_probe {chosenSubset : Finset (Fin size)}
    {probe : Fin size → ℝ} (hunit : probe ⬝ᵥ probe = 1)
    (hsupport : ∀ atomIndex : Fin size, atomIndex ∉ chosenSubset → probe atomIndex = 0)
    (hstrict : probe ⬝ᵥ (chartStationaryGap projection weight *ᵥ probe) < value) :
    ¬ ChartBlockDominatesAtValue projection weight value chosenSubset := by
  intro hdominates
  have hbound := hdominates probe hsupport
  rw [hunit, mul_one] at hbound
  linarith

/-- **A TIGHT VECTOR SITS EXACTLY AT THE VALUE.**  Tightness is asserted only ON the
subset and the vector vanishes off it, so the ambient quotient reads the eigenvalue
equation at every coordinate that contributes. -/
theorem dotProduct_chartStationaryGap_mulVec_of_isChartTightVector
    {chosenSubset : Finset (Fin size)} {tightVec : Fin size → ℝ}
    (htight : IsChartTightVector projection weight value chosenSubset tightVec) :
    tightVec ⬝ᵥ (chartStationaryGap projection weight *ᵥ tightVec)
      = value * (tightVec ⬝ᵥ tightVec) := by
  have hterm : ∀ atomIndex : Fin size,
      tightVec atomIndex * (chartStationaryGap projection weight *ᵥ tightVec) atomIndex
        = value * (tightVec atomIndex * tightVec atomIndex) := by
    intro atomIndex
    by_cases hmem : atomIndex ∈ chosenSubset
    · rw [htight.isTight atomIndex hmem]; ring
    · rw [htight.hasSupport atomIndex hmem]; ring
  calc tightVec ⬝ᵥ (chartStationaryGap projection weight *ᵥ tightVec)
      = ∑ atomIndex : Fin size,
          tightVec atomIndex * (chartStationaryGap projection weight *ᵥ tightVec) atomIndex := rfl
    _ = ∑ atomIndex : Fin size, value * (tightVec atomIndex * tightVec atomIndex) :=
        Finset.sum_congr rfl fun atomIndex _ => hterm atomIndex
    _ = value * (tightVec ⬝ᵥ tightVec) := by rw [← Finset.mul_sum]; rfl

/-! ## Uniform caps and floors -/

/-- **A FINITE FAMILY OF POSITIVE NUMBERS HAS A POSITIVE FLOOR.**  This is the whole of
the "uniformly over the finitely many subsets" step, and it needs no Lipschitz constant. -/
theorem exists_pos_le_forall_mem {indexType : Type*} (indexSet : Finset indexType)
    (measure : indexType → ℝ) (hpositive : ∀ index ∈ indexSet, 0 < measure index) :
    ∃ floorValue : ℝ, 0 < floorValue ∧ ∀ index ∈ indexSet, floorValue ≤ measure index := by
  classical
  rcases indexSet.eq_empty_or_nonempty with hempty | hnonempty
  · exact ⟨1, one_pos, fun index hmem => absurd hmem (by rw [hempty]; exact Finset.notMem_empty _)⟩
  · obtain ⟨minIndex, hminMem, hmin⟩ := indexSet.exists_min_image measure hnonempty
    exact ⟨measure minIndex, hpositive minIndex hminMem, hmin⟩

/-- From `x² ≤ bound` with a nonnegative bound, the crude cap `|x| ≤ 1 + bound`.  Crude on
purpose: it is spent on a smallness threshold and nowhere else. -/
theorem abs_le_one_add_of_sq_le {value bound : ℝ} (hsq : value ^ 2 ≤ bound) (hbound : 0 ≤ bound) :
    |value| ≤ 1 + bound := by
  refine abs_le_of_sq_le_sq_of_nonneg ?_ (by linarith)
  nlinarith

/-- **A CAP ON THE WEIGHT DIRECTION.** -/
def chartWeightCap (directionWeight : Fin size → ℝ) : ℝ :=
  1 + ∑ atomIndex : Fin size, directionWeight atomIndex ^ 2

theorem chartWeightCap_nonneg (directionWeight : Fin size → ℝ) :
    0 ≤ chartWeightCap directionWeight := by
  have hsum : 0 ≤ ∑ atomIndex : Fin size, directionWeight atomIndex ^ 2 :=
    Finset.sum_nonneg fun _ _ => sq_nonneg _
  rw [chartWeightCap]
  linarith

theorem abs_directionWeight_le_chartWeightCap (directionWeight : Fin size → ℝ)
    (atomIndex : Fin size) : |directionWeight atomIndex| ≤ chartWeightCap directionWeight := by
  have hterm : directionWeight atomIndex ^ 2
      ≤ ∑ otherIndex : Fin size, directionWeight otherIndex ^ 2 :=
    Finset.single_le_sum (fun otherIndex _ => sq_nonneg (directionWeight otherIndex))
      (Finset.mem_univ atomIndex)
  exact abs_le_one_add_of_sq_le hterm (Finset.sum_nonneg fun _ _ => sq_nonneg _)

/-- **A UNIFORM CAP ON THE TANGENT SLOPE** over unit probes. -/
def chartSlopeCap (directionMatrix : Matrix (Fin size) (Fin size) ℝ)
    (directionWeight : Fin size → ℝ) : ℝ :=
  (1 + chartFrobeniusSquare directionMatrix) + chartWeightCap directionWeight

theorem chartSlopeCap_nonneg (directionMatrix : Matrix (Fin size) (Fin size) ℝ)
    (directionWeight : Fin size → ℝ) : 0 ≤ chartSlopeCap directionMatrix directionWeight := by
  have hfrobenius := chartFrobeniusSquare_nonneg directionMatrix
  have hweight := chartWeightCap_nonneg directionWeight
  rw [chartSlopeCap]
  linarith

theorem abs_chartTangentSlope_le_chartSlopeCap
    (directionMatrix : Matrix (Fin size) (Fin size) ℝ) (directionWeight : Fin size → ℝ)
    {probe : Fin size → ℝ} (hunit : probe ⬝ᵥ probe = 1) :
    |chartTangentSlope probe directionMatrix directionWeight|
      ≤ chartSlopeCap directionMatrix directionWeight := by
  have hquadratic : |probe ⬝ᵥ (directionMatrix *ᵥ probe)|
      ≤ 1 + chartFrobeniusSquare directionMatrix := by
    refine abs_le_one_add_of_sq_le ?_ (chartFrobeniusSquare_nonneg directionMatrix)
    have hcauchy := dotProduct_sq_le_mul probe (directionMatrix *ᵥ probe)
    have himage := mulVec_dotProduct_self_le_chartFrobeniusSquare directionMatrix probe
    rw [hunit, one_mul] at hcauchy
    rw [hunit, mul_one] at himage
    linarith
  have hweightPart : |∑ atomIndex : Fin size,
      directionWeight atomIndex * probe atomIndex ^ 2| ≤ chartWeightCap directionWeight := by
    have hsquares : ∑ atomIndex : Fin size, probe atomIndex ^ 2 = 1 := by
      rw [← dotProduct_self_eq_sum_sq, hunit]
    calc |∑ atomIndex : Fin size, directionWeight atomIndex * probe atomIndex ^ 2|
        ≤ ∑ atomIndex : Fin size, |directionWeight atomIndex * probe atomIndex ^ 2| :=
          Finset.abs_sum_le_sum_abs _ _
      _ ≤ ∑ atomIndex : Fin size, chartWeightCap directionWeight * probe atomIndex ^ 2 := by
          refine Finset.sum_le_sum fun atomIndex _ => ?_
          rw [abs_mul, abs_of_nonneg (sq_nonneg (probe atomIndex))]
          exact mul_le_mul_of_nonneg_right
            (abs_directionWeight_le_chartWeightCap directionWeight atomIndex)
            (sq_nonneg (probe atomIndex))
      _ = chartWeightCap directionWeight := by
          rw [← Finset.mul_sum, hsquares, mul_one]
  rw [chartTangentSlope_eq_sub, chartSlopeCap]
  rw [abs_le] at hquadratic hweightPart ⊢
  exact ⟨by linarith [hquadratic.1, hweightPart.2], by linarith [hquadratic.2, hweightPart.1]⟩

/-! ## THE DESCENT LEMMA -/

/-- **THE DESCENT LEMMA, in full.**  Suppose that at a chart point with strictly positive
weights every `rank`-subset is either carried by the active family or has a probe
STRICTLY below the value (`Gtz.IsChartInactiveStrict`), that each active block carries a
unit tight direction, and that along one tangent direction EVERY active block's tight
slope is strictly negative.  Then there is a positive step along the Cayley curve at which

* the moved chart is still a symmetric idempotent of the same trace and the moved weights
  are still strictly positive and of the same sum — the constraint set is preserved
  EXACTLY, not to first order;
* the moved point is within any prescribed sup-norm radius of the base point;
* and NO `rank`-subset dominates at the value.

So the chart objective is strictly below `value` at the moved point, and the base point is
not a minimiser.  The three ingredients that
`Gtz.Quantitative.ChartStrongStationary` honesty (a) names as missing are supplied here:
the curve is `Gtz.chartCayleyProjection`, the continuity is the frozen-probe expansion
`Gtz.abs_chartTangentCurve_gap_form_sub_le` (no Weyl and no eigenvalue is needed, because
`IsChartInactiveStrict` hands back a PROBE rather than an eigenvalue), and the
identification of the active family with the argmax family is exactly
`IsChartInactiveStrict` itself. -/
theorem exists_chartTangentCurve_descent {rank : ℕ} {activeIndex : Type*}
    {directionMatrix : Matrix (Fin size) (Fin size) ℝ} {directionWeight : Fin size → ℝ}
    {radius : ℝ} {activeSet : Finset activeIndex}
    {activeSubset : activeIndex → Finset (Fin size)} {selection : activeIndex → (Fin size → ℝ)}
    (hsymmetric : projectionᵀ = projection)
    (hidempotent : projection * projection = projection)
    (hweightPos : ∀ atomIndex : Fin size, 0 < weight atomIndex)
    (htangent : IsChartTangent projection directionMatrix directionWeight)
    (hinactive : IsChartInactiveStrict rank projection weight value activeSet activeSubset)
    (hselection : ∀ activeLabel ∈ activeSet,
      IsChartTightDirection projection weight value (activeSubset activeLabel)
        (selection activeLabel))
    (hdescent : ∀ activeLabel ∈ activeSet,
      chartTangentSlope (selection activeLabel) directionMatrix directionWeight < 0)
    (hradiusPos : 0 < radius) :
    ∃ step : ℝ, 0 < step
      ∧ (chartTangentCurve step projection directionMatrix)ᵀ
          = chartTangentCurve step projection directionMatrix
      ∧ chartTangentCurve step projection directionMatrix
          * chartTangentCurve step projection directionMatrix
          = chartTangentCurve step projection directionMatrix
      ∧ Matrix.trace (chartTangentCurve step projection directionMatrix)
          = Matrix.trace projection
      ∧ (∀ atomIndex : Fin size, 0 < chartCayleyWeight step weight directionWeight atomIndex)
      ∧ (∑ atomIndex : Fin size, chartCayleyWeight step weight directionWeight atomIndex)
          = ∑ atomIndex : Fin size, weight atomIndex
      ∧ (∀ rowIndex colIndex : Fin size,
          |chartTangentCurve step projection directionMatrix rowIndex colIndex
            - projection rowIndex colIndex| ≤ radius)
      ∧ (∀ atomIndex : Fin size,
          |chartCayleyWeight step weight directionWeight atomIndex - weight atomIndex| ≤ radius)
      ∧ ¬ HasChartDominatingSubsetAtValue rank
            (chartTangentCurve step projection directionMatrix)
            (chartCayleyWeight step weight directionWeight) value := by
  classical
  have hskewGenerator : (chartTangentSkew projection directionMatrix)ᵀ
      = -chartTangentSkew projection directionMatrix :=
    transpose_chartTangentSkew hsymmetric htangent.isSymmetric
  have hcapNonneg : 0 ≤ chartFrobeniusSquare (chartTangentSkew projection directionMatrix) :=
    chartFrobeniusSquare_nonneg _
  have hslopeCapNonneg := chartSlopeCap_nonneg directionMatrix directionWeight
  have hweightCapNonneg := chartWeightCap_nonneg directionWeight
  obtain ⟨slopeFloor, hslopeFloorPos, hslopeFloor⟩ :=
    exists_pos_le_forall_mem activeSet
      (fun activeLabel =>
        -chartTangentSlope (selection activeLabel) directionMatrix directionWeight)
      (fun activeLabel hmem => by
        have hneg := hdescent activeLabel hmem
        simpa using neg_pos.mpr hneg)
  have hmarginExists : ∀ chosenSubset : Finset (Fin size), ∃ margin : ℝ, 0 < margin
      ∧ (chosenSubset.card = rank →
          (∃ activeLabel ∈ activeSet, activeSubset activeLabel = chosenSubset)
          ∨ ∃ probe : Fin size → ℝ, probe ⬝ᵥ probe = 1
              ∧ (∀ atomIndex : Fin size, atomIndex ∉ chosenSubset → probe atomIndex = 0)
              ∧ probe ⬝ᵥ (chartStationaryGap projection weight *ᵥ probe) ≤ value - margin) := by
    intro chosenSubset
    by_cases hcard : chosenSubset.card = rank
    · rcases hinactive chosenSubset hcard with hactive | ⟨probe, hunit, hsupport, hstrict⟩
      · exact ⟨1, one_pos, fun _ => Or.inl hactive⟩
      · exact ⟨value - probe ⬝ᵥ (chartStationaryGap projection weight *ᵥ probe), by linarith,
          fun _ => Or.inr ⟨probe, hunit, hsupport, by linarith⟩⟩
    · exact ⟨1, one_pos, fun hcontradiction => absurd hcontradiction hcard⟩
  choose margin hmarginPos hmargin using hmarginExists
  obtain ⟨gapFloor, hgapFloorPos, hgapFloor⟩ :=
    exists_pos_le_forall_mem (Finset.powersetCard rank (Finset.univ : Finset (Fin size)))
      margin fun chosenSubset _ => hmarginPos chosenSubset
  obtain ⟨weightFloor, hweightFloorPos, hweightFloor⟩ :=
    exists_pos_le_forall_mem (Finset.univ : Finset (Fin size)) weight
      fun atomIndex _ => hweightPos atomIndex
  set coefficient : ℝ := 24 * chartFrobeniusSquare (chartTangentSkew projection directionMatrix)
      + chartSlopeCap directionMatrix directionWeight + chartWeightCap directionWeight + 1
    with hcoefficientDef
  have hcoefficientPos : 0 < coefficient := by rw [hcoefficientDef]; linarith
  set target : ℝ := min (min slopeFloor gapFloor) (min weightFloor (min radius (radius ^ 2)))
    with htargetDef
  have hradiusSqPos : 0 < radius ^ 2 := by positivity
  have htargetPos : 0 < target := by
    rw [htargetDef]
    exact lt_min (lt_min hslopeFloorPos hgapFloorPos)
      (lt_min hweightFloorPos (lt_min hradiusPos hradiusSqPos))
  have hslopeTarget : target ≤ slopeFloor :=
    le_trans (min_le_left _ _) (min_le_left _ _)
  have hgapTarget : target ≤ gapFloor :=
    le_trans (min_le_left _ _) (min_le_right _ _)
  have hweightTarget : target ≤ weightFloor :=
    le_trans (min_le_right _ _) (min_le_left _ _)
  have hradiusTarget : target ≤ radius :=
    le_trans (min_le_right _ _) (le_trans (min_le_right _ _) (min_le_left _ _))
  have hradiusSqTarget : target ≤ radius ^ 2 :=
    le_trans (min_le_right _ _) (le_trans (min_le_right _ _) (min_le_right _ _))
  set step : ℝ := min 1 (target / (2 * coefficient)) with hstepDef
  have hstepPos : 0 < step := by
    rw [hstepDef]
    exact lt_min one_pos (div_pos htargetPos (by linarith))
  have hstepLeOne : step ≤ 1 := by rw [hstepDef]; exact min_le_left _ _
  have hstepCoefficient : step * coefficient < target := by
    have hstepDiv : step ≤ target / (2 * coefficient) := by rw [hstepDef]; exact min_le_right _ _
    have hscaled : step * coefficient ≤ target / (2 * coefficient) * coefficient :=
      mul_le_mul_of_nonneg_right hstepDiv hcoefficientPos.le
    have hcollapse : target / (2 * coefficient) * coefficient = target / 2 := by
      field_simp
    rw [hcollapse] at hscaled
    linarith
  have hstepSqLe : step ^ 2 ≤ step := by nlinarith [hstepPos, hstepLeOne]
  have hremainderSmall :
      8 * step ^ 2 * chartFrobeniusSquare (chartTangentSkew projection directionMatrix)
        ≤ 8 * step * chartFrobeniusSquare (chartTangentSkew projection directionMatrix) := by
    have hproduct : 0 ≤ chartFrobeniusSquare (chartTangentSkew projection directionMatrix)
        * (step - step ^ 2) := mul_nonneg hcapNonneg (by linarith)
    nlinarith [hproduct]
  have hweightCapLe : chartWeightCap directionWeight ≤ coefficient := by
    rw [hcoefficientDef]; linarith
  have hframeCapLe : 16 * chartFrobeniusSquare (chartTangentSkew projection directionMatrix)
      ≤ coefficient := by rw [hcoefficientDef]; linarith
  have hslopeCapLe : 8 * chartFrobeniusSquare (chartTangentSkew projection directionMatrix)
      ≤ coefficient := by rw [hcoefficientDef]; linarith
  have hbundleCapLe : chartSlopeCap directionMatrix directionWeight
      + 8 * chartFrobeniusSquare (chartTangentSkew projection directionMatrix)
      ≤ coefficient := by rw [hcoefficientDef]; linarith
  have hstepWeightCap : step * chartWeightCap directionWeight ≤ step * coefficient :=
    mul_le_mul_of_nonneg_left hweightCapLe hstepPos.le
  -- the moved point is in the constraint set
  refine ⟨step, hstepPos,
    transpose_chartCayleyProjection hsymmetric step _,
    chartCayleyProjection_mul_self hskewGenerator hidempotent step,
    trace_chartCayleyProjection hskewGenerator step projection, ?_,
    sum_chartCayleyWeight_eq htangent.weight_sum_zero step, ?_, ?_, ?_⟩
  · intro atomIndex
    have hfloor := hweightFloor atomIndex (Finset.mem_univ atomIndex)
    have hdirectionCap := abs_directionWeight_le_chartWeightCap directionWeight atomIndex
    rw [abs_le] at hdirectionCap
    have hproduct : -(step * chartWeightCap directionWeight) ≤ step * directionWeight atomIndex := by
      nlinarith [hstepPos, hdirectionCap.1]
    rw [chartCayleyWeight]
    linarith
  · intro rowIndex colIndex
    have hentrySq := sq_chartCayleyProjection_sub_entry_le hskewGenerator hsymmetric hidempotent
      step rowIndex colIndex
    have hstepFrameCap :
        step * (16 * chartFrobeniusSquare (chartTangentSkew projection directionMatrix))
          ≤ step * coefficient :=
      mul_le_mul_of_nonneg_left hframeCapLe hstepPos.le
    have hsecondOrder :
        16 * step ^ 2 * chartFrobeniusSquare (chartTangentSkew projection directionMatrix)
          ≤ 16 * step * chartFrobeniusSquare (chartTangentSkew projection directionMatrix) := by
      have hproduct : 0 ≤ chartFrobeniusSquare (chartTangentSkew projection directionMatrix)
          * (step - step ^ 2) := mul_nonneg hcapNonneg (by linarith)
      nlinarith [hproduct]
    refine abs_le_of_sq_le_sq_of_nonneg ?_ hradiusPos.le
    rw [chartTangentCurve]
    nlinarith [hentrySq, hsecondOrder, hstepFrameCap, hstepCoefficient, hradiusSqTarget]
  · intro atomIndex
    have hdirectionCap := abs_directionWeight_le_chartWeightCap directionWeight atomIndex
    rw [chartCayleyWeight, add_sub_cancel_left, abs_mul, abs_of_pos hstepPos]
    have hscaled : step * |directionWeight atomIndex| ≤ step * chartWeightCap directionWeight :=
      mul_le_mul_of_nonneg_left hdirectionCap hstepPos.le
    linarith
  · rintro ⟨chosenSubset, hcard, hdominates⟩
    rcases hmargin chosenSubset hcard with
      ⟨activeLabel, hmem, hsubsetEq⟩ | ⟨probe, hprobeUnit, hprobeSupport, hprobeLow⟩
    · have htightDir := hselection activeLabel hmem
      have hbase : selection activeLabel
          ⬝ᵥ (chartStationaryGap projection weight *ᵥ selection activeLabel) = value := by
        rw [dotProduct_chartStationaryGap_mulVec_of_isChartTightVector
          (isChartTightVector_of_isChartTightDirection htightDir), htightDir.isUnit, mul_one]
      have hmoved := abs_chartTangentCurve_gap_form_sub_le (weight := weight)
        (directionWeight := directionWeight) hsymmetric hidempotent htangent step htightDir.isUnit
      rw [abs_le] at hmoved
      have hslopeBound := hslopeFloor activeLabel hmem
      have hactiveKey : 8 * step
            * chartFrobeniusSquare (chartTangentSkew projection directionMatrix) < slopeFloor := by
        have hcap : step
            * (8 * chartFrobeniusSquare (chartTangentSkew projection directionMatrix))
            ≤ step * coefficient :=
          mul_le_mul_of_nonneg_left hslopeCapLe hstepPos.le
        nlinarith [hcap, hstepCoefficient, hslopeTarget]
      have hstrict : selection activeLabel
          ⬝ᵥ (chartStationaryGap (chartTangentCurve step projection directionMatrix)
            (chartCayleyWeight step weight directionWeight) *ᵥ selection activeLabel) < value := by
        nlinarith [hmoved.2, hbase, hremainderSmall, hactiveKey, hstepPos, hslopeBound]
      refine not_chartBlockDominatesAtValue_of_probe htightDir.isUnit ?_ hstrict hdominates
      intro atomIndex hnotMem
      exact htightDir.hasSupport atomIndex (by rw [hsubsetEq]; exact hnotMem)
    · have hmarginBound := hgapFloor chosenSubset
        (Finset.mem_powersetCard.mpr ⟨Finset.subset_univ _, hcard⟩)
      have hmoved := abs_chartTangentCurve_gap_form_sub_le (weight := weight)
        (directionWeight := directionWeight) hsymmetric hidempotent htangent step hprobeUnit
      rw [abs_le] at hmoved
      have hslopeBound := abs_chartTangentSlope_le_chartSlopeCap directionMatrix directionWeight
        hprobeUnit
      rw [abs_le] at hslopeBound
      have hinactiveKey : step * chartSlopeCap directionMatrix directionWeight
          + 8 * step * chartFrobeniusSquare (chartTangentSkew projection directionMatrix)
          < gapFloor := by
        have hcap : step * (chartSlopeCap directionMatrix directionWeight
            + 8 * chartFrobeniusSquare (chartTangentSkew projection directionMatrix))
            ≤ step * coefficient :=
          mul_le_mul_of_nonneg_left hbundleCapLe hstepPos.le
        nlinarith [hcap, hstepCoefficient, hgapTarget]
      have hslopeScaled : step * chartTangentSlope probe directionMatrix directionWeight
          ≤ step * chartSlopeCap directionMatrix directionWeight :=
        mul_le_mul_of_nonneg_left hslopeBound.2 hstepPos.le
      have hstrict : probe
          ⬝ᵥ (chartStationaryGap (chartTangentCurve step projection directionMatrix)
            (chartCayleyWeight step weight directionWeight) *ᵥ probe) < value := by
        linarith [hmoved.2, hprobeLow, hremainderSmall, hinactiveKey, hmarginBound]
      exact not_chartBlockDominatesAtValue_of_probe hprobeUnit hprobeSupport hstrict hdominates

/-! ## Admissibility is a CONSEQUENCE here, not a hypothesis

`Gtz.IsChartArgmaxValue` is the load-bearing hypothesis of the strictness theorem, of both
value floors and of every class closure in the layer, and it is never derived — it is
always assumed.  With the active family identified as the argmax family, which is what
`Gtz.IsChartInactiveStrict` says, it follows. -/

/-- **ADMISSIBILITY FROM THE ACTIVE FAMILY.**  If every `rank`-subset is either carried by
the active family or has a probe strictly below the value, and every active block carries
a unit tight direction, then every `rank`-subset has a probe at or below the value — which
is `Gtz.IsChartArgmaxValue`.

The active blocks contribute their tight direction, whose quotient is EXACTLY the value;
the inactive ones contribute their strict probe.  Nothing else is used. -/
theorem isChartArgmaxValue_of_isChartInactiveStrict {rank : ℕ} {activeIndex : Type*}
    {activeSet : Finset activeIndex} {activeSubset : activeIndex → Finset (Fin size)}
    (hinactive : IsChartInactiveStrict rank projection weight value activeSet activeSubset)
    (hexistsTight : ∀ activeLabel ∈ activeSet, ∃ tightVec : Fin size → ℝ,
      IsChartTightDirection projection weight value (activeSubset activeLabel) tightVec) :
    IsChartArgmaxValue rank projection weight value := by
  intro chosenSubset hcardSubset
  rcases hinactive chosenSubset hcardSubset with
    ⟨activeLabel, hmem, hsubsetEq⟩ | ⟨probe, hunit, hsupport, hstrict⟩
  · obtain ⟨tightVec, htightDir⟩ := hexistsTight activeLabel hmem
    refine ⟨tightVec, htightDir.isUnit, ?_, ?_⟩
    · intro atomIndex hnotMem
      exact htightDir.hasSupport atomIndex (by rw [hsubsetEq]; exact hnotMem)
    · rw [dotProduct_chartStationaryGap_mulVec_of_isChartTightVector
        (isChartTightVector_of_isChartTightDirection htightDir), htightDir.isUnit, mul_one]
  · exact ⟨probe, hunit, hsupport, le_of_lt hstrict⟩

/-! ## The covering condition at a minimum

The conclusion lands EXACTLY on `Gtz.IsChartTightCovering`, because
`Gtz.isChartTightCovering_iff_forall_hasBalancedMultiplier` and
`Gtz.isChartStrongStationaryData_iff_isChartTightCovering` already carry it the rest of the
way.  The Gordan exchange is consumed, never restated. -/

/-- **THE COVERING CONDITION HOLDS AT A LOCAL MINIMUM.**

Read the hypothesis `hminimal` as "the chart objective is at least `value` at every
constraint point near this one": at every symmetric idempotent of the same trace with
strictly positive weights of the same sum, entrywise within `radius` of the base point,
some `rank`-subset dominates at `value`.  The conclusion is that every tangent direction
lies in some active block's tight cone.

Contrapositive of `Gtz.exists_chartTangentCurve_descent`: a direction outside every cone
hands back, per active block, a tight vector of strictly negative slope (this is the
extraction `Gtz.isChartTightCovering_of_forall_hasBalancedMultiplier` performs, redone here
because it is inline there), and the descent lemma then produces a nearby constraint point
at which no subset dominates.

WHAT THIS BUYS AND WHAT IT DOES NOT — see the file header.  It removes a scaffolding gap.
It closes no cell. -/
theorem isChartTightCovering_of_localMinimum {rank : ℕ} {activeIndex : Type*}
    {activeSet : Finset activeIndex} {activeSubset : activeIndex → Finset (Fin size)}
    {radius : ℝ}
    (hsymmetric : projectionᵀ = projection)
    (hidempotent : projection * projection = projection)
    (hweightPos : ∀ atomIndex : Fin size, 0 < weight atomIndex)
    (hinactive : IsChartInactiveStrict rank projection weight value activeSet activeSubset)
    (hradiusPos : 0 < radius)
    (hminimal : ∀ (movedChart : Matrix (Fin size) (Fin size) ℝ) (movedWeight : Fin size → ℝ),
      movedChartᵀ = movedChart → movedChart * movedChart = movedChart →
      Matrix.trace movedChart = Matrix.trace projection →
      (∀ atomIndex : Fin size, 0 < movedWeight atomIndex) →
      (∑ atomIndex : Fin size, movedWeight atomIndex)
        = ∑ atomIndex : Fin size, weight atomIndex →
      (∀ rowIndex colIndex : Fin size,
        |movedChart rowIndex colIndex - projection rowIndex colIndex| ≤ radius) →
      (∀ atomIndex : Fin size, |movedWeight atomIndex - weight atomIndex| ≤ radius) →
      HasChartDominatingSubsetAtValue rank movedChart movedWeight value) :
    IsChartTightCovering projection weight value activeSet activeSubset := by
  classical
  intro direction htangent
  by_contra hmissed
  have hnotCone : ∀ activeLabel : activeIndex, activeLabel ∈ activeSet →
      direction ∉ chartTightCone projection weight value (activeSubset activeLabel) :=
    fun activeLabel hmem hcone => hmissed ⟨activeLabel, hmem, hcone⟩
  have hwitness : ∀ activeLabel : activeIndex, activeLabel ∈ activeSet →
      ∃ tightVec : Fin size → ℝ,
        IsChartTightDirection projection weight value (activeSubset activeLabel) tightVec
          ∧ chartTangentSlope tightVec direction.1 direction.2 < 0 := by
    intro activeLabel hmem
    have hslopeFails : ∃ rawVec : Fin size → ℝ,
        IsChartTightVector projection weight value (activeSubset activeLabel) rawVec
          ∧ chartTangentSlope rawVec direction.1 direction.2 < 0 := by
      by_contra hnoWitness
      refine hnotCone activeLabel hmem
        (mem_chartTightCone_iff.mpr ⟨htangent, fun tightVec htight => ?_⟩)
      rcases le_or_gt 0 (chartTangentSlope tightVec direction.1 direction.2) with
        hnonneg | hnegative
      · exact hnonneg
      · exact absurd ⟨tightVec, htight, hnegative⟩ hnoWitness
    obtain ⟨rawVec, hrawTight, hrawNegative⟩ := hslopeFails
    have hrawNonzero : rawVec ≠ 0 := by
      intro hzero
      rw [hzero, chartTangentSlope_zero_vector] at hrawNegative
      exact lt_irrefl 0 hrawNegative
    obtain ⟨scale, hscalePos, hscaled⟩ :=
      exists_pos_isChartTightDirection_smul_of_isChartTightVector hrawTight hrawNonzero
    refine ⟨scale • rawVec, hscaled, ?_⟩
    rw [chartTangentSlope_smul]
    exact mul_neg_of_pos_of_neg (pow_pos hscalePos 2) hrawNegative
  choose pickTightDir hpickTight hpickNegative using hwitness
  set selection : activeIndex → (Fin size → ℝ) := fun activeLabel =>
    if hmem : activeLabel ∈ activeSet then pickTightDir activeLabel hmem else 0
    with hselectionDef
  have hselectionTight : ∀ activeLabel ∈ activeSet,
      IsChartTightDirection projection weight value (activeSubset activeLabel)
        (selection activeLabel) := by
    intro activeLabel hmem
    simpa only [hselectionDef, dif_pos hmem] using hpickTight activeLabel hmem
  have hselectionNegative : ∀ activeLabel ∈ activeSet,
      chartTangentSlope (selection activeLabel) direction.1 direction.2 < 0 := by
    intro activeLabel hmem
    simpa only [hselectionDef, dif_pos hmem] using hpickNegative activeLabel hmem
  obtain ⟨step, _, htransposeMoved, hidempotentMoved, htraceMoved, hweightPosMoved,
    hweightSumMoved, hchartClose, hweightClose, hnoDominator⟩ :=
    exists_chartTangentCurve_descent hsymmetric hidempotent hweightPos htangent hinactive
      hselectionTight hselectionNegative hradiusPos
  exact hnoDominator (hminimal _ _ htransposeMoved hidempotentMoved htraceMoved hweightPosMoved
    hweightSumMoved hchartClose hweightClose)

/-- **THE COVERING CONDITION AT A GLOBAL MINIMUM.**  The local statement with the two
closeness hypotheses dropped, which is the form the compactness chain supplies: a global
minimiser is a point at which the objective is at least its own value everywhere. -/
theorem isChartTightCovering_of_globalMinimum {rank : ℕ} {activeIndex : Type*}
    {activeSet : Finset activeIndex} {activeSubset : activeIndex → Finset (Fin size)}
    (hsymmetric : projectionᵀ = projection)
    (hidempotent : projection * projection = projection)
    (hweightPos : ∀ atomIndex : Fin size, 0 < weight atomIndex)
    (hinactive : IsChartInactiveStrict rank projection weight value activeSet activeSubset)
    (hminimal : ∀ (movedChart : Matrix (Fin size) (Fin size) ℝ) (movedWeight : Fin size → ℝ),
      movedChartᵀ = movedChart → movedChart * movedChart = movedChart →
      Matrix.trace movedChart = Matrix.trace projection →
      (∀ atomIndex : Fin size, 0 < movedWeight atomIndex) →
      (∑ atomIndex : Fin size, movedWeight atomIndex)
        = ∑ atomIndex : Fin size, weight atomIndex →
      HasChartDominatingSubsetAtValue rank movedChart movedWeight value) :
    IsChartTightCovering projection weight value activeSet activeSubset :=
  isChartTightCovering_of_localMinimum hsymmetric hidempotent hweightPos hinactive one_pos
    fun movedChart movedWeight htransposeMoved hidempotentMoved htraceMoved hweightPosMoved
      hweightSumMoved _ _ =>
      hminimal movedChart movedWeight htransposeMoved hidempotentMoved htraceMoved
        hweightPosMoved hweightSumMoved

/-- **THE STRONG STATIONARITY BUNDLE AT A GLOBAL MINIMUM.**  Covering rebuilt into the
shipped bundle through `Gtz.isChartStrongStationaryData_of_isChartTightCovering`, whose
seven extra hypotheses are exactly the chart-point data covering does not see.

Composed with `Gtz.isChartTightCovering_iff_forall_hasBalancedMultiplier` this is the
universal-selection multiplier condition, and with
`Gtz.exists_multiplier_isChartStationaryData_of_isChartStrongStationaryData` it is the
shipped weak bundle `Gtz.IsChartStationaryData` at every selection.  So the whole
first-order layer now runs from minimality rather than from an assumed datum. -/
theorem isChartStrongStationaryData_of_globalMinimum {rank : ℕ} {activeIndex : Type*}
    {activeSet : Finset activeIndex} {activeSubset : activeIndex → Finset (Fin size)}
    (hsymmetric : projectionᵀ = projection)
    (hidempotent : projection * projection = projection)
    (htraceRank : Matrix.trace projection = (rank : ℝ))
    (hweightPos : ∀ atomIndex : Fin size, 0 < weight atomIndex)
    (hweightSum : ∑ atomIndex : Fin size, weight atomIndex = 1)
    (hcard : ∀ activeLabel ∈ activeSet, (activeSubset activeLabel).card = rank)
    (hexistsTight : ∀ activeLabel ∈ activeSet, ∃ tightVec : Fin size → ℝ,
      IsChartTightDirection projection weight value (activeSubset activeLabel) tightVec)
    (hinactive : IsChartInactiveStrict rank projection weight value activeSet activeSubset)
    (hminimal : ∀ (movedChart : Matrix (Fin size) (Fin size) ℝ) (movedWeight : Fin size → ℝ),
      movedChartᵀ = movedChart → movedChart * movedChart = movedChart →
      Matrix.trace movedChart = Matrix.trace projection →
      (∀ atomIndex : Fin size, 0 < movedWeight atomIndex) →
      (∑ atomIndex : Fin size, movedWeight atomIndex)
        = ∑ atomIndex : Fin size, weight atomIndex →
      HasChartDominatingSubsetAtValue rank movedChart movedWeight value) :
    IsChartStrongStationaryData rank projection weight value activeSet activeSubset :=
  isChartStrongStationaryData_of_isChartTightCovering hsymmetric hidempotent htraceRank
    hweightPos hweightSum hcard hexistsTight
    (isChartTightCovering_of_globalMinimum hsymmetric hidempotent hweightPos hinactive hminimal)

/-- **THE WEAK BUNDLE AND ITS ADMISSIBILITY, TOGETHER, AT A GLOBAL MINIMUM.**  The shipped
`Gtz.IsChartStationaryData` at some selection, together with `Gtz.IsChartArgmaxValue` — the
two hypotheses every exclusion in the layer consumes, both discharged from minimality.

This is the sentence the chain wanted: the conditional theorems of
`Gtz.Quantitative.ChartStationary` and its successors no longer need a datum handed to
them, provided the minimality and the inactive side condition are supplied. -/
theorem exists_isChartStationaryData_and_isChartArgmaxValue_of_globalMinimum {rank : ℕ}
    {activeIndex : Type*} {activeSet : Finset activeIndex}
    {activeSubset : activeIndex → Finset (Fin size)}
    (hsymmetric : projectionᵀ = projection)
    (hidempotent : projection * projection = projection)
    (htraceRank : Matrix.trace projection = (rank : ℝ))
    (hweightPos : ∀ atomIndex : Fin size, 0 < weight atomIndex)
    (hweightSum : ∑ atomIndex : Fin size, weight atomIndex = 1)
    (hcard : ∀ activeLabel ∈ activeSet, (activeSubset activeLabel).card = rank)
    (hexistsTight : ∀ activeLabel ∈ activeSet, ∃ tightVec : Fin size → ℝ,
      IsChartTightDirection projection weight value (activeSubset activeLabel) tightVec)
    (hinactive : IsChartInactiveStrict rank projection weight value activeSet activeSubset)
    (hminimal : ∀ (movedChart : Matrix (Fin size) (Fin size) ℝ) (movedWeight : Fin size → ℝ),
      movedChartᵀ = movedChart → movedChart * movedChart = movedChart →
      Matrix.trace movedChart = Matrix.trace projection →
      (∀ atomIndex : Fin size, 0 < movedWeight atomIndex) →
      (∑ atomIndex : Fin size, movedWeight atomIndex)
        = ∑ atomIndex : Fin size, weight atomIndex →
      HasChartDominatingSubsetAtValue rank movedChart movedWeight value) :
    (∃ (multiplier : activeIndex → ℝ) (selection : activeIndex → (Fin size → ℝ)),
        IsChartStationaryData rank projection weight value activeSet activeSubset multiplier
          selection)
      ∧ IsChartArgmaxValue rank projection weight value :=
  ⟨exists_isChartStationaryData_of_isChartStrongStationaryData
      (isChartStrongStationaryData_of_globalMinimum hsymmetric hidempotent htraceRank hweightPos
        hweightSum hcard hexistsTight hinactive hminimal),
   isChartArgmaxValue_of_isChartInactiveStrict hinactive hexistsTight⟩

/-! ## The curve starts where it should, and the hypotheses are inhabited

Non-vacuity, in two parts: the curve at step zero IS the base point, so the expansion above
is an expansion of something; and the shipped `(4,3)` tetrahedron satisfies the inactive
side condition, so `Gtz.IsChartInactiveStrict` — which before this file was consumed only
by its own reading lemma — is not an empty predicate. -/

theorem chartCayley_zero (skew : Matrix (Fin size) (Fin size) ℝ) : chartCayley 0 skew = 1 := by
  rw [chartCayley, chartCayleyDenominator, chartCayleyDenominator, neg_zero, zero_smul, sub_zero,
    inv_one, Matrix.mul_one]

theorem chartCayleyProjection_zero (skew projection : Matrix (Fin size) (Fin size) ℝ) :
    chartCayleyProjection 0 skew projection = projection := by
  rw [chartCayleyProjection, chartCayley_zero, Matrix.one_mul, Matrix.transpose_one,
    Matrix.mul_one]

theorem chartTangentCurve_zero (projection directionMatrix : Matrix (Fin size) (Fin size) ℝ) :
    chartTangentCurve 0 projection directionMatrix = projection :=
  chartCayleyProjection_zero _ _

theorem chartCayleyWeight_zero (weight directionWeight : Fin size → ℝ) :
    chartCayleyWeight 0 weight directionWeight = weight := by
  funext atomIndex
  rw [chartCayleyWeight, zero_mul, add_zero]

/-- **THE TETRAHEDRON SATISFIES THE INACTIVE SIDE CONDITION**, and trivially: at `(4,3)`
there are exactly four `rank`-subsets and all four are active, so the dichotomy always
takes its left branch.  This is the cheapest possible inhabitant and it is enough to show
`Gtz.IsChartInactiveStrict` is not an empty predicate. -/
theorem chartTetraProjection_isChartInactiveStrict :
    IsChartInactiveStrict 3 chartTetraProjection chartTetraWeight 0
      (Finset.univ : Finset (Fin 4)) chartTetraSubset := by
  intro chosenSubset hcard
  have hexists : ∀ candidate : Finset (Fin 4), candidate.card = 3 →
      ∃ missingIndex : Fin 4, chartTetraSubset missingIndex = candidate := by decide
  obtain ⟨missingIndex, hsubset⟩ := hexists chosenSubset hcard
  exact Or.inl ⟨missingIndex, Finset.mem_univ _, hsubset⟩

/-- **THE TETRAHEDRON IS ADMISSIBLE.**  `Gtz.IsChartArgmaxValue` at the shipped `(4,3)`
witness, from the inactive side condition and the shipped tight directions.

`Gtz.Quantitative.ChartInstances` records that none of its three witnesses is proved
admissible; this settles it for the tetrahedron.  IT BUYS NOTHING BEYOND THAT: the bundle
is satisfied at admissible NON-minima, so admissibility does not upgrade a witness into an
exclusion, and the same file says so. -/
theorem chartTetraProjection_isChartArgmaxValue :
    IsChartArgmaxValue 3 chartTetraProjection chartTetraWeight 0 :=
  isChartArgmaxValue_of_isChartInactiveStrict chartTetraProjection_isChartInactiveStrict
    fun missingIndex _ =>
      ⟨chartTetraTightDir missingIndex, isChartTightDirection_chartTetraTightDir missingIndex⟩

end Gtz
