/-
# The Positivstellensatz frontier at rank three: the symmetric chart, and the
# multiplier-support floor a strict Stengle certificate has to clear

`Gtz.Quantitative.DiscriminantSystem` reduces all of GTZ at rank three to ONE
real-algebraic sentence, `DiscriminantCovering 7`, and
`Gtz.Certificates.PositivstellensatzObstruction` shows the whole
Putinar/Schmuedgen half of the Positivstellensatz is unavailable for it at every
degree, because the CLOSED tie-failure system is inhabited. This file does the
two things that follow from that, and only those: it puts the covering in the
coordinates a symmetry-reduced certificate needs, and it proves a combinatorial
lower bound on the multiplier support of the surviving strict-Stengle form for
one explicitly named sub-system.

There is no certificate here. Rank three is not proved, and nothing below
claims it is.

## PROVED here (every declaration at or below
## `[propext, Classical.choice, Quot.sound]` — 44 at it, 6 at
## `[propext, Quot.sound]`, 3 axiom-free; no `sorry`, no `axiom`, no
## `native_decide`)

**Part I — the covering has no pivot in it.** The pivoted trace leg
`discriminantTrace D pivot pairFirst pairSecond` is the sum of the two `2x2`
minors of `Gram_T - I` THROUGH the pivot, so it breaks the `S_3` symmetry of the
triple. Its three pivot readings sum to twice `discriminantMinorSum`, which is
the fully symmetric `e_2(Gram_T - I)` (`discriminantTrace_pivotSum`), and one
pigeonhole step upgrades that identity to an equivalence:

  `Dominates D {a,b,c} <-> 0 <= e_2(Gram_T - I) and 0 <= e_3(Gram_T - I)`
  (`dominates_triple_iff_symmetricLegs`, for distinct heavy atoms),

hence `SymmetricCovering 7 <-> GtzWeightedAll 3`
(`symmetricCoveringSeven_iff_rank_three`). Both legs are invariant under
relabelling the triple (`exists_increasing_symmetricLegs`), and the existential
over ordered triples therefore factors through the `35` increasing
representatives: `symmetricCoveringSeven_iff_increasingTriples` states the
covering literally over `increasingTriplesSeven`, so "the disjunction is over
`C(7,3)` SUBSETS" is a theorem here and not a reading. Both `S_7` (on atoms) and
`S_3` (inside a triple) are manifest symmetries of the two polynomials. Degrees
are unchanged: `2` and `3` in the six Gram entries of the triple, `4` and `6` in
the atom coordinates.

Worth being precise about the cost: the textbook route to "a symmetric `3x3`
matrix is positive semidefinite iff `e_1, e_2, e_3 >= 0`" goes through the
spectral theorem and Descartes' rule of signs, which `Gtz.LinAlg.PsdKit`
deliberately does not carry. That route is NOT used. The proof here is the three
pivot readings plus `linarith`, and the `e_1` leg never appears because
`AllHeavy` makes `e_1 = sum of heavyExcess > 0` free. `notDominates_symmetricSignature`
records the consequence: a failing all-heavy triple has `e_2 < 0` or `e_3 < 0` —
two inequalities per triple, not three.

**Part II — the tetrahedral block family.** The split tetrahedron of
`Gtz.Quantitative.DecisionAtlasSevenThree` is one point of a whole orbit of exact
ties. For ANY surjection `blocks : Fin 7 -> Fin 4`, put tetrahedron direction
`blocks c` on atom `c` and split each direction's weight `1/4` equally inside its
fibre; Parseval collapses fibrewise onto `tetraDesign`'s own Parseval identity
(`tetraBlockDesign`). Every leverage is exactly `3`, so the design is all-heavy
(`tetraBlockDesign_allHeavy`), and if the map is THIN — every direction used, no
three atoms sharing one, i.e. profile `(2,2,2,1)` — then at every triple of
distinct atoms

  `e_3 = 0` on the rainbow triples and `e_3 = -8` on the rest
  (`..._discriminantTie_of_rainbow`, `..._of_repeated`), so all `35` legs are
  `<= 0` (`tetraBlockDesign_discriminantTie_nonpos`);
  `e_2 = 9` on the rainbow triples and `e_2 = 1` on the rest, so `e_2 >= 1 > 0`
  everywhere ON THIS FAMILY (`tetraBlockDesign_symmetricSignature`).

`splitSevenDesign` is the member carried by
`splitSevenDirection = ![0,1,2,3,0,1,2]`, and the identification is now formal:
`splitSevenDesign_eq_tetraBlockDesign` proves the two designs EQUAL, since
`blockLabelWeight` divides each direction's `1/4` by its fibre size and returns
exactly `1/8, 1/8, 1/8, 1/4, 1/8, 1/8, 1/8`. Every bespoke `splitSevenDesign_*`
lemma of `DecisionAtlasSevenThree` is therefore the `blocks = splitSevenDirection`
instance of a Part II lemma.

**Part III — the multiplier-support floor.** A strict Stengle certificate for the
emptiness of the tie-failure system is an identity `S + P + Z = 0` with `S` in
the multiplicative monoid generated by the strict generators, `P` in the positive
cone, `Z` in the ideal. At any point of the CLOSED system all generators are
`>= 0` and the ideal vanishes, so `S >= 0`, `P >= 0` and `S + P = 0`, forcing
`S = 0`. The region's own strict generators `t_c` and `heavyExcess c` are
strictly positive at every member of the block family, so it is the TIE factors
that must vanish — and a product of reals vanishes exactly when one factor does.
`IsStengleTieSupportSeven` records precisely that, and nothing else: no degrees,
no multiplicities, no polynomiality.

`isStengleTieSupportSeven_increasing_iff` calibrates the notion — the FULL index
set is an admissible support exactly when the tie leg alone covers, which is a
consequence of `DiscriminantCovering 7` and therefore open. The definition is
neither vacuous nor free.

The floor is then combinatorial, and is checked by kernel evaluation:

  `not_isStengleTieSupportSeven_of_card_le_three` — no set of at most three
  triples is a Stengle tie-support, because for every three of the `35` triples
  one of the `105` block systems makes all three share a block
  (`hasSharedBlockForEveryTrio_true`, `35^3` cases, decided in the kernel);

  `four_le_card_of_isStengleTieSupportSeven` — every Stengle tie-support has at
  least FOUR triples.

## INFERRED, NOT MECHANISED — the degree reading, and the two caveats that
## must travel with it

What Part III mechanises is a CARDINALITY floor, `4 <= support.card`. Reading a
degree off it is an inference on top, and it is sound only with both of the
following attached.

(i) SCOPE. `IsStengleTieSupportSeven` quantifies over designs at which EVERY tie
leg is `<= 0`. The floor therefore bounds a certificate for the emptiness of the
ALL-TIE strict system `{-discriminantTie_T > 0 : T in the 35 triples}`, NOT for
`DiscriminantCovering 7`. The two differ, and the gap is mechanised here:
`exists_tieNonneg_notDominates_seven` exhibits a member of the block family at a
NON-thin surjection (`crowdedBlockMap = ![0,0,0,1,2,3,3]`, three atoms on one
direction) whose triple `(0,1,2)` has `e_3 = 8 > 0` and `e_2 = -15 < 0`, hence
does not dominate. So "some tie leg is nonnegative" is strictly weaker than "some
triple dominates"; emptiness of the tie system is necessary for the covering and
never sufficient, and a certificate for it would not close rank three. In
particular the floor constrains NEITHER the atlas route
(`exists_atlas_iff_discriminantCovering`, which the repo flags as the live one)
NOR any certificate whose monoid part uses an `e_2` generator: at the block
family `e_2 >= 1 > 0`, so such a factor is strictly positive there and the
vanishing argument does not run.

(ii) PRESENTATION. Degrees are read off the `35` strict generators
`-discriminantTie_T`, each of degree `3` in the `28` Gram entries and `6` in the
`21` atom coordinates, giving `4 * 3 = 12` and `4 * 6 = 24`. That reading is
specific to this presentation. An equivalent basic system obtained by lifting —
one auxiliary variable `u_T` per triple, ideal generator
`(e_2(T) - u_T) * (e_3(T) - u_T) = 0`, cone generators `e_2(T) - u_T >= 0` and
`e_3(T) - u_T >= 0`, strict generator `-u_T > 0` — is empty exactly when
`DiscriminantCovering 7` holds, and its strict generators have degree `1`
overall and degree `0` in the Gram entries. The support argument still yields
four, but `4 * 0 = 0`. The cardinality floor is presentation-independent; the
degree floor is not.

## CITED (proved elsewhere in this repo, used in the proofs below)

`dominates_triple_iff_discriminantSystem`, `discriminantTie_swap`,
`discriminantMinorSum`, `discriminantTie`, `discriminantTrace`, `heavyExcess`,
`atomPairing`, `atomPairing_comm`, `DiscriminantCovering`,
`discriminantCovering_seven_iff_rank_three`
(`Gtz.Quantitative.DiscriminantSystem`); `tetraAtom`, `tetraAtom_dot_self`,
`tetraDesign` (`Gtz.Design.StressCertificate`); `tetraAtom_dot_of_ne`,
`splitSevenDirection`, `splitSevenDesign`, `increasingTriplesSeven`,
`increasingTriplesSeven_card`, `increasingTriplesSeven_distinct`
(`Gtz.Quantitative.DecisionAtlasSevenThree`); `WeightedDesign.ext`
(`Gtz.Reduction.RatCertificateInstance`).

## REFERENCED IN PROSE ONLY (not imported, not used in any proof here)

`not_hasUniformTieAggregateSeven`, `closedTieFailure_inhabited_seven`
(`Gtz.Certificates.PositivstellensatzObstruction`) for the Putinar half this file
starts from; `exists_atlas_iff_discriminantCovering`
(`Gtz.Quantitative.DecisionAtlasSevenThree`); `allHeavy_heavyExcess_pos`
(`Gtz.Quantitative.DiscriminantSystem`) for the vacuity of the `e_1` leg;
`splitClassDesign_isTie` (`Gtz.Ties.SplitClassTieFamily`), `sharpDesign_isTie`
and `sharpDesign_not_rotated_tetrahedron` (`Gtz.Ties.NonTetrahedralTie`) for the
tie families beyond this one; `discriminantTie_swapPair`
(`Gtz.Quantitative.GoodTripleGraph`), the sibling transposition of
`discriminantTie_rotate`.

## MEASURED (computed outside Lean, NOT proved here, stated as such)

* FOUR IS SHARP FOR THE BLOCK FAMILY. `{012, 013, 024, 034}` does meet the
  rainbow family of every one of the `105` block systems, and exactly `5355` of
  the `52360` four-element subsets of the `35` triples do. Only the lower bound
  is mechanised; the upper bound is an exhaustive search in integer arithmetic
  outside Lean. This is sharpness for the block-family HITTING condition, not for
  `IsStengleTieSupportSeven` itself, which quantifies over every all-heavy
  tie-failure design and whose true minimum may exceed four. So the block family
  alone cannot raise the floor above four.
* THE `e_2` LEG IS NOT UNIFORMLY POSITIVE ON THE TIE STRATUM.
  `tetraBlockDesign_symmetricSignature` gives `e_2 >= 1` on the block family and
  ONLY there; the statement does not extend to ties at large. Counter-witness
  inside this repo's own already-mechanised `Gtz.Ties.SplitClassTieFamily`:
  `splitClassDesign` at class map `![0,1,2,3,0,1,2]` with class totals
  `(p, q, q, q)`, `q = (19 - sqrt 217)/18 = 0.2371711...`, `p = 1 - 3q =
  0.2884867...`, is all-heavy, has all `35` tie legs `<= 0`, and has `e_2 = 0` at
  exactly the four triples `(0,1,5), (0,2,6), (1,4,5), (2,4,6)`; pushing to
  `p = 0.55, q = 0.15` gives `min e_2 = -5.4646...`. Consequently the claim that
  facial reduction driven by ties touches only the determinant-leg multipliers,
  leaving the `e_2` block strictly feasible, is FALSE outside the uniform
  class-total members. Uniform class totals `1/4` reproduce the block family
  exactly (`heavyExcess = 2`, pairings `3` and `-1`), which is why the two
  pictures agree there and only there.
* OTHER TIE ORBITS ARE ALREADY MECHANISED HERE, and they are not special cases of
  the block family: `splitClassDesign_isTie` is an exact tie for EVERY surjection
  onto the classes and EVERY weight vector, at every size, and `sharpDesign_isTie`
  together with `sharpDesign_not_rotated_tetrahedron` is a tie PROVED not to be a
  rotated regular tetrahedron. Neither raises the floor: the `e_3`-vanishing set
  of a `splitClassDesign` is fixed by the class map and not by the weights, so it
  is the same rainbow set the block family already pins. What remains measured
  and unproved is the reported count of eight `(7,3)` tie orbits, one per
  rank-three series-parallel matroid on seven elements; that classification is a
  blind numerical search, and any orbit outside the class-map picture could raise
  the floor.
* Calibration for how far out of reach a certificate at this degree is: no
  machine-checked Positivstellensatz certificate above roughly six variables and
  degree eight exists in any proof assistant, and a sum-of-squares Gram basis at
  degree `12` in the `35` Gram-and-weight variables has `C(41,6) = 4 496 388`
  monomials.

## COMPLEX SANITY CHECK — RUN, and here is what it showed

The rule is that a certificate for the REAL statement must FAIL over `C`, since
`Gtz.Complex.SharpConstantLedger` mechanises a complex `(6,3)` counterexample:
the shared-axis trine `g_j = (sqrt 2, 0, w^j)`, `g_{3+j} = (0, sqrt 2, w^j)` at
uniform weight `1/6`, exactly Parseval, every leverage exactly `3` (all-heavy),
with NONE of its twenty triples dominating.

Applied to Part I. The symmetric reformulation is FIELD-BLIND: `e_1, e_2, e_3` of
a Hermitian `3x3` Gram are real, the pivot-sum identity is a `ring` fact over any
commutative ring, and the pigeonhole step uses only the order on the reals. So
the reformulation cannot by itself decide anything, which is exactly right for an
equivalence with a statement that is TRUE over the reals and FALSE over `C`. Its
ACHIEVABILITY is what is field-sensitive, and the numbers say so: at the trine
every one of the twenty triples has

  `(e_1, e_2, e_3) = (6, 7, -2)` or `(6, 3, -10)`,

so `e_2 > 0` everywhere and the symmetric covering fails over `C` through the
DETERMINANT leg alone. Put beside `tetraBlockDesign_symmetricSignature`, where
the real block family has `e_2 in {1, 9} > 0` and `e_3 in {-8, 0} <= 0` with `0`
ATTAINED, the two pictures have the same shape and differ in exactly one place:
whether `e_3` can reach `0`. Every Gram-visible quantity except the triangle
monomial `<g_a,g_b> <g_b,g_c> <g_c,g_a>` agrees; over the reals its square equals
the product of the three squared pairings and over `C` it is only `<=`. So a
certificate must give the generator `tau_T^2 - rho_ab rho_bc rho_ca` a multiplier
of INDEFINITE sign — the direction unavailable over `C`, and the content of
`Gtz.Quantitative.PhaseFreeNoGo`. The trine figures are MEASURED (60-digit
recomputation of the mechanised witness), not proved here.

Applied to Part III. The deliverable is a NEGATIVE result about certificate
shape, so it cannot prove the false complex statement and the test does not apply
to it as a falsifier. It does constrain the objects, and the constraint is met:
the whole argument runs on the VANISHING SET of the tie leg, which the real block
family has (`e_3 = 0` on the rainbow triples) and the complex trine does not
(`e_3 in {-2, -10}`, strictly negative at every one of its twenty triples). The
support floor is therefore a statement about real tie geometry with no complex
counterpart to leak into.
-/
import Mathlib
import Gtz.Core.Basic
import Gtz.Quantitative.DiscriminantSystem
import Gtz.Quantitative.DecisionAtlasSevenThree
import Gtz.Reduction.RatCertificateInstance

set_option autoImplicit false
set_option relaxedAutoImplicit false
set_option maxRecDepth 40000

namespace Gtz

open Matrix

variable {m : ℕ}

/-! ## Part I. The pivot-free form of the covering

`dominates_triple_iff_discriminantSystem` reads a triple through a chosen PIVOT:
the trace leg `discriminantTrace D pivot pairFirst pairSecond` is the sum of the
two `2x2` minors of `Gram - I` THROUGH that pivot, so it is not a symmetric
function of the triple. `discriminantSystem_pivot_independent` says the truth
value does not depend on the choice, but the polynomial does, and a
symmetry-reduced certificate cannot afford a chart that breaks `S_3`.

This part removes the pivot from the polynomials themselves. The three pivot
readings of the trace leg sum to twice `discriminantMinorSum`, which IS the
second elementary symmetric function `e_2(Gram_T - I)` and is fully symmetric;
one pigeonhole step turns the sum identity into an equivalence. No spectral
theorem is used anywhere: the standard route to "a symmetric `3x3` matrix is
positive semidefinite iff `e_1, e_2, e_3 >= 0`" goes through eigenvalues and
Descartes' rule, and that route is not needed here. -/

/-- Reordering the three atoms of a triple does not change the underlying subset.
Stated for the two reorderings the pivot rotation needs. -/
private theorem tripleSubset_swapFirstTwo (first second third : Fin m) :
    ({second, first, third} : Finset (Fin m)) = {first, second, third} :=
  Finset.insert_comm second first {third}

private theorem tripleSubset_rotate (first second third : Fin m) :
    ({third, first, second} : Finset (Fin m)) = {first, second, third} := by
  ext atomIndex
  simp only [Finset.mem_insert, Finset.mem_singleton]
  tauto

/-- **The tie leg is a cyclic invariant of the triple.** `discriminantTie` is
`det(Gram_T - I)` and determinants do not see the labelling; combined with
`discriminantTie_swap` this gives the full `S_3` invariance.
`Gtz.Quantitative.GoodTripleGraph.discriminantTie_swapPair` is the sibling
transposition, and either of the two together with `discriminantTie_swap`
generates the same group. -/
theorem discriminantTie_rotate (D : WeightedDesign m 3) (first second third : Fin m) :
    discriminantTie D first second third = discriminantTie D third first second := by
  simp only [discriminantTie, atomPairing_comm D third first, atomPairing_comm D third second]
  ring

/-- **The minor sum is a full `S_3` invariant of the triple**, under the
transposition that `discriminantTie_swap` uses. -/
theorem discriminantMinorSum_swapFirstTwo (D : WeightedDesign m 3)
    (first second third : Fin m) :
    discriminantMinorSum D first second third = discriminantMinorSum D second first third := by
  simp only [discriminantMinorSum, atomPairing_comm D second first]
  ring

/-- ... and under the three-cycle. -/
theorem discriminantMinorSum_rotate (D : WeightedDesign m 3) (first second third : Fin m) :
    discriminantMinorSum D first second third = discriminantMinorSum D third first second := by
  simp only [discriminantMinorSum, atomPairing_comm D third first,
    atomPairing_comm D third second]
  ring

/-- **The pivot sum**: the three pivot readings of the trace leg add up to twice
the minor sum. Each unordered pair of the triple lies on exactly two of the three
readings, so the sum double counts `e_2(Gram_T - I)`. Pure `ring`, after
symmetrising the pairings. -/
theorem discriminantTrace_pivotSum (D : WeightedDesign m 3) (first second third : Fin m) :
    discriminantTrace D first second third + discriminantTrace D second first third
        + discriminantTrace D third first second
      = 2 * discriminantMinorSum D first second third := by
  simp only [discriminantTrace, discriminantMinorSum, atomPairing_comm D second first,
    atomPairing_comm D third first, atomPairing_comm D third second]
  ring

/-- **THE PIVOT-FREE NARROWING.** For a triple of distinct HEAVY atoms,
domination is exactly the pair of `S_3`-invariant polynomial inequalities
`discriminantMinorSum >= 0` and `discriminantTie >= 0`.

Forward: domination gives the trace leg at all three pivots, and their sum is
twice the minor sum. Backward: the minor sum being nonnegative makes the sum of
the three trace readings nonnegative, so SOME pivot has a nonnegative trace leg —
pigeonhole, not spectral theory — and that pivot's reading discharges the pivoted
narrowing. The tie leg transports between readings by `discriminantTie_swap` and
`discriminantTie_rotate`. -/
theorem dominates_triple_iff_symmetricLegs (D : WeightedDesign m 3)
    {first second third : Fin m} (hfirstSecond : first ≠ second)
    (hfirstThird : first ≠ third) (hsecondThird : second ≠ third)
    (hfirstHeavy : 1 < leverageOf (D.atom first))
    (hsecondHeavy : 1 < leverageOf (D.atom second))
    (hthirdHeavy : 1 < leverageOf (D.atom third)) :
    Dominates D {first, second, third}
      ↔ (0 ≤ discriminantMinorSum D first second third
          ∧ 0 ≤ discriminantTie D first second third) := by
  have hreadingFirst := dominates_triple_iff_discriminantSystem D hfirstSecond
    hfirstThird hsecondThird hfirstHeavy
  have hreadingSecond := dominates_triple_iff_discriminantSystem D hfirstSecond.symm
    hsecondThird hfirstThird hsecondHeavy
  have hreadingThird := dominates_triple_iff_discriminantSystem D hfirstThird.symm
    hsecondThird.symm hfirstSecond hthirdHeavy
  have hpivotSum := discriminantTrace_pivotSum D first second third
  have htieSwap := discriminantTie_swap D first second third
  have htieRotate := discriminantTie_rotate D first second third
  constructor
  · intro hdominates
    have hfromFirst := hreadingFirst.mp hdominates
    have hfromSecond := hreadingSecond.mp
      (by rw [tripleSubset_swapFirstTwo]; exact hdominates)
    have hfromThird := hreadingThird.mp
      (by rw [tripleSubset_rotate]; exact hdominates)
    exact ⟨by linarith [hfromFirst.1, hfromSecond.1, hfromThird.1], hfromFirst.2⟩
  · rintro ⟨hminorNonneg, htieNonneg⟩
    rcases le_or_gt 0 (discriminantTrace D first second third) with htraceFirst | htraceFirst
    · exact hreadingFirst.mpr ⟨htraceFirst, htieNonneg⟩
    rcases le_or_gt 0 (discriminantTrace D second first third) with htraceSecond | htraceSecond
    · rw [← tripleSubset_swapFirstTwo first second third]
      exact hreadingSecond.mpr ⟨htraceSecond, htieSwap ▸ htieNonneg⟩
    · rw [← tripleSubset_rotate first second third]
      refine hreadingThird.mpr ⟨by linarith, htieRotate ▸ htieNonneg⟩

/-- **The covering, with no pivot in it.** Every all-heavy weighted `(m,3)`
design has a triple of distinct atoms at which the two `S_3`-INVARIANT legs are
both nonnegative. Degrees `2` and `3` in the six Gram entries of the triple, as
before; what is new is that both legs are now invariant under relabelling the
triple, so the ordered existential factors through the `C(m,3)` subsets —
`symmetricCoveringSeven_iff_increasingTriples` states that factoring literally at
`m = 7`. -/
def SymmetricCovering (m : ℕ) : Prop :=
  ∀ D : WeightedDesign m 3, AllHeavy D →
    ∃ first second third : Fin m,
      first ≠ second ∧ first ≠ third ∧ second ≠ third
        ∧ 0 ≤ discriminantMinorSum D first second third
        ∧ 0 ≤ discriminantTie D first second third

/-- **The two coverings are the same sentence.** Nothing is given up by trading
the pivoted trace leg for the symmetric minor sum. -/
theorem symmetricCovering_iff_discriminantCovering (size : ℕ) :
    SymmetricCovering size ↔ DiscriminantCovering size := by
  constructor
  · intro hsymmetric D hheavy
    obtain ⟨first, second, third, hfirstSecond, hfirstThird, hsecondThird,
      hminor, htie⟩ := hsymmetric D hheavy
    refine ⟨first, second, third, hfirstSecond, hfirstThird, hsecondThird, ?_, htie⟩
    exact ((dominates_triple_iff_discriminantSystem D hfirstSecond hfirstThird
      hsecondThird (hheavy first)).mp
        ((dominates_triple_iff_symmetricLegs D hfirstSecond hfirstThird hsecondThird
          (hheavy first) (hheavy second) (hheavy third)).mpr ⟨hminor, htie⟩)).1
  · intro hcover D hheavy
    obtain ⟨first, second, third, hfirstSecond, hfirstThird, hsecondThird,
      htrace, htie⟩ := hcover D hheavy
    refine ⟨first, second, third, hfirstSecond, hfirstThird, hsecondThird, ?_, htie⟩
    exact ((dominates_triple_iff_symmetricLegs D hfirstSecond hfirstThird hsecondThird
      (hheavy first) (hheavy second) (hheavy third)).mp
        ((dominates_triple_iff_discriminantSystem D hfirstSecond hfirstThird
          hsecondThird (hheavy first)).mpr ⟨htrace, htie⟩)).1

/-- **The polynomial frontier of rank three, in `S_3`-invariant coordinates.**
GTZ at rank three for every `n` IS the single sentence: every all-heavy weighted
`(7,3)` design has one of its `35` triples at which `e_2(Gram_T - I) >= 0` and
`e_3(Gram_T - I) >= 0`. This is the shape a symmetry-reduced semidefinite
relaxation wants: the `S_7` action on atoms and the `S_3` action inside a triple
are both manifest symmetries of the two legs. -/
theorem symmetricCoveringSeven_iff_rank_three :
    SymmetricCovering 7 ↔ GtzWeightedAll 3 :=
  (symmetricCovering_iff_discriminantCovering 7).trans discriminantCovering_seven_iff_rank_three

/-- **The failure signature of a triple, pivot-free.** An all-heavy triple that
does NOT dominate has a negative `e_2` or a negative `e_3` — never a "negative
trace", since `e_1(Gram_T - I)` is the sum of the three heavy excesses and
`AllHeavy` makes it positive for free (`allHeavy_heavyExcess_pos`). Two
inequalities per triple, not three. -/
theorem notDominates_symmetricSignature (D : WeightedDesign m 3)
    {first second third : Fin m} (hfirstSecond : first ≠ second)
    (hfirstThird : first ≠ third) (hsecondThird : second ≠ third)
    (hfirstHeavy : 1 < leverageOf (D.atom first))
    (hsecondHeavy : 1 < leverageOf (D.atom second))
    (hthirdHeavy : 1 < leverageOf (D.atom third))
    (hfails : ¬ Dominates D {first, second, third}) :
    discriminantMinorSum D first second third < 0
      ∨ discriminantTie D first second third < 0 := by
  by_contra hneither
  push Not at hneither
  exact hfails ((dominates_triple_iff_symmetricLegs D hfirstSecond hfirstThird
    hsecondThird hfirstHeavy hsecondHeavy hthirdHeavy).mpr hneither)

/-! ### The leg pair depends only on the SUBSET

`discriminantTie_swap` with `discriminantTie_rotate`, and
`discriminantMinorSum_swapFirstTwo` with `discriminantMinorSum_rotate`, give both
legs invariance under a transposition and under a three-cycle — together, under
all of `S_3`. Spelling the remaining three permutations out lets the ordered
existential of `SymmetricCovering` be replaced by one over the increasing
representatives, which is what makes "the disjunction is over `C(m,3)` subsets"
a theorem rather than a reading. -/

private theorem symmetricLegs_swapFirstTwo (D : WeightedDesign m 3)
    (first second third : Fin m) :
    discriminantMinorSum D first second third = discriminantMinorSum D second first third
      ∧ discriminantTie D first second third = discriminantTie D second first third :=
  ⟨discriminantMinorSum_swapFirstTwo D first second third,
    discriminantTie_swap D first second third⟩

private theorem symmetricLegs_rotate (D : WeightedDesign m 3) (first second third : Fin m) :
    discriminantMinorSum D first second third = discriminantMinorSum D third first second
      ∧ discriminantTie D first second third = discriminantTie D third first second :=
  ⟨discriminantMinorSum_rotate D first second third,
    discriminantTie_rotate D first second third⟩

private theorem symmetricLegs_swapLastTwo (D : WeightedDesign m 3)
    (first second third : Fin m) :
    discriminantMinorSum D first second third = discriminantMinorSum D first third second
      ∧ discriminantTie D first second third = discriminantTie D first third second := by
  refine ⟨?_, ?_⟩
  · rw [(symmetricLegs_rotate D first second third).1,
      (symmetricLegs_swapFirstTwo D third first second).1]
  · rw [(symmetricLegs_rotate D first second third).2,
      (symmetricLegs_swapFirstTwo D third first second).2]

private theorem symmetricLegs_rotateTwice (D : WeightedDesign m 3)
    (first second third : Fin m) :
    discriminantMinorSum D first second third = discriminantMinorSum D second third first
      ∧ discriminantTie D first second third = discriminantTie D second third first := by
  refine ⟨?_, ?_⟩
  · rw [(symmetricLegs_rotate D first second third).1,
      (symmetricLegs_rotate D third first second).1]
  · rw [(symmetricLegs_rotate D first second third).2,
      (symmetricLegs_rotate D third first second).2]

private theorem symmetricLegs_reverse (D : WeightedDesign m 3)
    (first second third : Fin m) :
    discriminantMinorSum D first second third = discriminantMinorSum D third second first
      ∧ discriminantTie D first second third = discriminantTie D third second first := by
  refine ⟨?_, ?_⟩
  · rw [(symmetricLegs_swapFirstTwo D first second third).1,
      (symmetricLegs_rotate D second first third).1]
  · rw [(symmetricLegs_swapFirstTwo D first second third).2,
      (symmetricLegs_rotate D second first third).2]

/-- **Both legs are functions of the SUBSET.** Any triple of distinct atoms has
the same minor sum and the same tie leg as its increasing representative. Six
orderings, each discharged by one of the five permutation identities above. -/
theorem exists_increasing_symmetricLegs (D : WeightedDesign m 3)
    {first second third : Fin m} (hfirstSecond : first ≠ second)
    (hfirstThird : first ≠ third) (hsecondThird : second ≠ third) :
    ∃ least middle greatest : Fin m, least < middle ∧ middle < greatest
      ∧ discriminantMinorSum D first second third
          = discriminantMinorSum D least middle greatest
      ∧ discriminantTie D first second third = discriminantTie D least middle greatest := by
  rcases lt_trichotomy first second with hfirstLtSecond | hfirstEqSecond | hsecondLtFirst
  · rcases lt_trichotomy second third with hsecondLtThird | hsecondEqThird | hthirdLtSecond
    · exact ⟨first, second, third, hfirstLtSecond, hsecondLtThird, rfl, rfl⟩
    · exact absurd hsecondEqThird hsecondThird
    · rcases lt_trichotomy first third with hfirstLtThird | hfirstEqThird | hthirdLtFirst
      · exact ⟨first, third, second, hfirstLtThird, hthirdLtSecond,
          (symmetricLegs_swapLastTwo D first second third).1,
          (symmetricLegs_swapLastTwo D first second third).2⟩
      · exact absurd hfirstEqThird hfirstThird
      · exact ⟨third, first, second, hthirdLtFirst, hfirstLtSecond,
          (symmetricLegs_rotate D first second third).1,
          (symmetricLegs_rotate D first second third).2⟩
  · exact absurd hfirstEqSecond hfirstSecond
  · rcases lt_trichotomy first third with hfirstLtThird | hfirstEqThird | hthirdLtFirst
    · exact ⟨second, first, third, hsecondLtFirst, hfirstLtThird,
        (symmetricLegs_swapFirstTwo D first second third).1,
        (symmetricLegs_swapFirstTwo D first second third).2⟩
    · exact absurd hfirstEqThird hfirstThird
    · rcases lt_trichotomy second third with hsecondLtThird | hsecondEqThird | hthirdLtSecond
      · exact ⟨second, third, first, hsecondLtThird, hthirdLtFirst,
          (symmetricLegs_rotateTwice D first second third).1,
          (symmetricLegs_rotateTwice D first second third).2⟩
      · exact absurd hsecondEqThird hsecondThird
      · exact ⟨third, second, first, hthirdLtSecond, hsecondLtFirst,
          (symmetricLegs_reverse D first second third).1,
          (symmetricLegs_reverse D first second third).2⟩

/-- **The covering, indexed by the `35` SUBSETS.** `SymmetricCovering 7` says
exactly that every all-heavy weighted `(7,3)` design has one of the `35`
increasing triples at which both `S_3`-invariant legs are nonnegative. The
ordered existential of the definition and this subset-indexed one are the same
sentence, so the disjunction really is over `C(7,3)` subsets and not over the
`210` ordered readings. -/
theorem symmetricCoveringSeven_iff_increasingTriples :
    SymmetricCovering 7 ↔
      ∀ design : WeightedDesign 7 3, AllHeavy design →
        ∃ triple ∈ increasingTriplesSeven,
          0 ≤ discriminantMinorSum design triple.1 triple.2.1 triple.2.2
            ∧ 0 ≤ discriminantTie design triple.1 triple.2.1 triple.2.2 := by
  constructor
  · intro hcover design hheavy
    obtain ⟨first, second, third, hfirstSecond, hfirstThird, hsecondThird, hminor, htie⟩ :=
      hcover design hheavy
    obtain ⟨least, middle, greatest, hleastLt, hmiddleLt, hminorEq, htieEq⟩ :=
      exists_increasing_symmetricLegs design hfirstSecond hfirstThird hsecondThird
    exact ⟨(least, middle, greatest),
      Finset.mem_filter.mpr ⟨Finset.mem_univ _, hleastLt, hmiddleLt⟩,
      hminorEq ▸ hminor, htieEq ▸ htie⟩
  · intro hcover design hheavy
    obtain ⟨triple, hmem, hminor, htie⟩ := hcover design hheavy
    obtain ⟨hfirstSecond, hfirstThird, hsecondThird⟩ := increasingTriplesSeven_distinct hmem
    exact ⟨triple.1, triple.2.1, triple.2.2, hfirstSecond, hfirstThird, hsecondThird,
      hminor, htie⟩

/-! ## Part II. The tetrahedral block family

The split tetrahedron of `Gtz.Quantitative.DecisionAtlasSevenThree` is ONE point
of a whole orbit of exact ties: put the four regular-tetrahedron directions on
the seven atoms according to any partition into blocks of size at most two, and
split each direction's weight `1/4` equally among the atoms carrying it. The
resulting design is again exactly Parseval, again all-heavy with every leverage
`3`, and again has all `35` tie legs `<= 0`, vanishing exactly on the triples that
carry three distinct directions.

`splitSevenDesign` is the member with blocks `![0,1,2,3,0,1,2]`, and
`splitSevenDesign_eq_tetraBlockDesign` identifies the two on the nose. The whole
orbit is needed for Part III: a single member pins only one rainbow family. -/

/-- The atoms carrying a given block label. -/
def blockFibre (blocks : Fin 7 → Fin 4) (label : Fin 4) : Finset (Fin 7) :=
  Finset.univ.filter fun atomIndex => blocks atomIndex = label

theorem blockFibre_card_pos {blocks : Fin 7 → Fin 4}
    (hsurjective : Function.Surjective blocks) (label : Fin 4) :
    0 < (blockFibre blocks label).card := by
  obtain ⟨witness, hwitness⟩ := hsurjective label
  exact Finset.card_pos.mpr ⟨witness, by simp [blockFibre, hwitness]⟩

/-- The weight carried by each atom of a block: the direction's share `1/4`,
split equally inside the block. -/
noncomputable def blockLabelWeight (blocks : Fin 7 → Fin 4) (label : Fin 4) : ℝ :=
  1 / (4 * ((blockFibre blocks label).card : ℝ))

theorem blockLabelWeight_pos {blocks : Fin 7 → Fin 4}
    (hsurjective : Function.Surjective blocks) (label : Fin 4) :
    0 < blockLabelWeight blocks label := by
  have hcard : (0 : ℝ) < ((blockFibre blocks label).card : ℝ) := by
    exact_mod_cast blockFibre_card_pos hsurjective label
  rw [blockLabelWeight]
  positivity

/-- Each block carries total weight exactly `1/4` — the tetrahedron's own weight
at that direction, which is what makes Parseval survive the split. -/
theorem blockFibre_card_mul_labelWeight {blocks : Fin 7 → Fin 4}
    (hsurjective : Function.Surjective blocks) (label : Fin 4) :
    ((blockFibre blocks label).card : ℝ) * blockLabelWeight blocks label = 1 / 4 := by
  have hcard : ((blockFibre blocks label).card : ℝ) ≠ 0 := by
    have hpos : (0 : ℝ) < ((blockFibre blocks label).card : ℝ) := by
      exact_mod_cast blockFibre_card_pos hsurjective label
    exact ne_of_gt hpos
  rw [blockLabelWeight]
  field_simp

private theorem blockFibre_sum_labelWeight {blocks : Fin 7 → Fin 4}
    (hsurjective : Function.Surjective blocks) (label : Fin 4) :
    ∑ _atomIndex ∈ Finset.univ.filter (fun atomIndex => blocks atomIndex = label),
        blockLabelWeight blocks label = (1 : ℝ) / 4 := by
  rw [Finset.sum_const, nsmul_eq_mul]
  exact blockFibre_card_mul_labelWeight hsurjective label

private theorem blockFibre_sum_smul {blocks : Fin 7 → Fin 4}
    (hsurjective : Function.Surjective blocks) (label : Fin 4)
    (value : Matrix (Fin 3) (Fin 3) ℝ) :
    ∑ _atomIndex ∈ Finset.univ.filter (fun atomIndex => blocks atomIndex = label),
        blockLabelWeight blocks label • value = ((1 : ℝ) / 4) • value := by
  rw [Finset.sum_const, ← Nat.cast_smul_eq_nsmul ℝ, smul_smul]
  congr 1
  exact blockFibre_card_mul_labelWeight hsurjective label

/-- **The tetrahedral block design.** Atom `c` carries tetrahedron direction
`blocks c` and weight `1/(4 * |fibre|)`. Parseval collapses fibrewise onto
`tetraDesign`'s own Parseval identity — the only hypothesis needed is that every
direction is used. -/
noncomputable def tetraBlockDesign (blocks : Fin 7 → Fin 4)
    (hsurjective : Function.Surjective blocks) : WeightedDesign 7 3 where
  atom := fun atomIndex => tetraAtom (blocks atomIndex)
  weight := fun atomIndex => blockLabelWeight blocks (blocks atomIndex)
  weight_pos := fun _ => blockLabelWeight_pos hsurjective _
  weight_sum_one := by
    refine ((Finset.sum_fiberwise' (Finset.univ : Finset (Fin 7)) blocks
      (blockLabelWeight blocks)).symm.trans
        ((Finset.sum_congr rfl fun label _ =>
          blockFibre_sum_labelWeight hsurjective label).trans ?_))
    rw [Finset.sum_const, Finset.card_univ, Fintype.card_fin, nsmul_eq_mul]
    norm_num
  isParseval := by
    refine ((Finset.sum_fiberwise' (Finset.univ : Finset (Fin 7)) blocks
      (fun label => blockLabelWeight blocks label • atomMatrix (tetraAtom label))).symm.trans
        ((Finset.sum_congr rfl fun label _ =>
          blockFibre_sum_smul hsurjective label _).trans ?_))
    exact tetraDesign.isParseval

@[simp] theorem tetraBlockDesign_atom (blocks : Fin 7 → Fin 4)
    (hsurjective : Function.Surjective blocks) (atomIndex : Fin 7) :
    (tetraBlockDesign blocks hsurjective).atom atomIndex = tetraAtom (blocks atomIndex) :=
  rfl

/-- Every atom of a block design has leverage exactly `3`. -/
theorem tetraBlockDesign_leverage (blocks : Fin 7 → Fin 4)
    (hsurjective : Function.Surjective blocks) (atomIndex : Fin 7) :
    leverageOf ((tetraBlockDesign blocks hsurjective).atom atomIndex) = 3 := by
  rw [tetraBlockDesign_atom, leverageOf, ← dotProduct_self_eq_sum_sq]
  exact tetraAtom_dot_self (blocks atomIndex)

theorem tetraBlockDesign_allHeavy (blocks : Fin 7 → Fin 4)
    (hsurjective : Function.Surjective blocks) :
    AllHeavy (tetraBlockDesign blocks hsurjective) := by
  intro atomIndex
  rw [tetraBlockDesign_leverage]
  norm_num

theorem tetraBlockDesign_heavyExcess (blocks : Fin 7 → Fin 4)
    (hsurjective : Function.Surjective blocks) (atomIndex : Fin 7) :
    heavyExcess (tetraBlockDesign blocks hsurjective) atomIndex = 2 := by
  rw [heavyExcess, tetraBlockDesign_leverage]
  norm_num

theorem tetraBlockDesign_atomPairing_of_sameBlock {blocks : Fin 7 → Fin 4}
    (hsurjective : Function.Surjective blocks) {atomFirst atomSecond : Fin 7}
    (hsame : blocks atomFirst = blocks atomSecond) :
    atomPairing (tetraBlockDesign blocks hsurjective) atomFirst atomSecond = 3 := by
  rw [atomPairing, tetraBlockDesign_atom, tetraBlockDesign_atom, hsame]
  exact tetraAtom_dot_self _

theorem tetraBlockDesign_atomPairing_of_differentBlock {blocks : Fin 7 → Fin 4}
    (hsurjective : Function.Surjective blocks) {atomFirst atomSecond : Fin 7}
    (hdifferent : blocks atomFirst ≠ blocks atomSecond) :
    atomPairing (tetraBlockDesign blocks hsurjective) atomFirst atomSecond = -1 := by
  rw [atomPairing, tetraBlockDesign_atom, tetraBlockDesign_atom]
  exact tetraAtom_dot_of_ne hdifferent

/-- With every heavy excess equal to `2`, both legs of a triple are symmetric
functions of its three pairings alone. -/
theorem tetraBlockDesign_discriminantTie_eq (blocks : Fin 7 → Fin 4)
    (hsurjective : Function.Surjective blocks) (pivot pairFirst pairSecond : Fin 7) :
    discriminantTie (tetraBlockDesign blocks hsurjective) pivot pairFirst pairSecond
      = 8 - 2 * (atomPairing (tetraBlockDesign blocks hsurjective) pairFirst pairSecond ^ 2
            + atomPairing (tetraBlockDesign blocks hsurjective) pivot pairFirst ^ 2
            + atomPairing (tetraBlockDesign blocks hsurjective) pivot pairSecond ^ 2)
        + 2 * atomPairing (tetraBlockDesign blocks hsurjective) pairFirst pairSecond
            * atomPairing (tetraBlockDesign blocks hsurjective) pivot pairFirst
            * atomPairing (tetraBlockDesign blocks hsurjective) pivot pairSecond := by
  simp only [discriminantTie, tetraBlockDesign_heavyExcess]
  ring

theorem tetraBlockDesign_discriminantMinorSum_eq (blocks : Fin 7 → Fin 4)
    (hsurjective : Function.Surjective blocks) (pivot pairFirst pairSecond : Fin 7) :
    discriminantMinorSum (tetraBlockDesign blocks hsurjective) pivot pairFirst pairSecond
      = 12 - (atomPairing (tetraBlockDesign blocks hsurjective) pairFirst pairSecond ^ 2
            + atomPairing (tetraBlockDesign blocks hsurjective) pivot pairFirst ^ 2
            + atomPairing (tetraBlockDesign blocks hsurjective) pivot pairSecond ^ 2) := by
  simp only [discriminantMinorSum, tetraBlockDesign_heavyExcess]
  ring

/-- A triple carrying three distinct directions has all three pairings `-1`. -/
private theorem tetraBlockDesign_squaredPairings_of_rainbow {blocks : Fin 7 → Fin 4}
    (hsurjective : Function.Surjective blocks) {pivot pairFirst pairSecond : Fin 7}
    (hpivotFirst : blocks pivot ≠ blocks pairFirst)
    (hpivotSecond : blocks pivot ≠ blocks pairSecond)
    (hpairDistinct : blocks pairFirst ≠ blocks pairSecond) :
    atomPairing (tetraBlockDesign blocks hsurjective) pairFirst pairSecond = -1
      ∧ atomPairing (tetraBlockDesign blocks hsurjective) pivot pairFirst = -1
      ∧ atomPairing (tetraBlockDesign blocks hsurjective) pivot pairSecond = -1 :=
  ⟨tetraBlockDesign_atomPairing_of_differentBlock hsurjective hpairDistinct,
    tetraBlockDesign_atomPairing_of_differentBlock hsurjective hpivotFirst,
    tetraBlockDesign_atomPairing_of_differentBlock hsurjective hpivotSecond⟩

/-- **A rainbow triple TIES**: `discriminantTie = 8 - 6 - 2 = 0` exactly. -/
theorem tetraBlockDesign_discriminantTie_of_rainbow {blocks : Fin 7 → Fin 4}
    (hsurjective : Function.Surjective blocks) {pivot pairFirst pairSecond : Fin 7}
    (hpivotFirst : blocks pivot ≠ blocks pairFirst)
    (hpivotSecond : blocks pivot ≠ blocks pairSecond)
    (hpairDistinct : blocks pairFirst ≠ blocks pairSecond) :
    discriminantTie (tetraBlockDesign blocks hsurjective) pivot pairFirst pairSecond = 0 := by
  obtain ⟨hpair, hfirst, hsecond⟩ :=
    tetraBlockDesign_squaredPairings_of_rainbow hsurjective hpivotFirst hpivotSecond
      hpairDistinct
  rw [tetraBlockDesign_discriminantTie_eq, hpair, hfirst, hsecond]
  norm_num

/-- **A rainbow triple has minor sum `9`**: `12 - 3`. -/
theorem tetraBlockDesign_discriminantMinorSum_of_rainbow {blocks : Fin 7 → Fin 4}
    (hsurjective : Function.Surjective blocks) {pivot pairFirst pairSecond : Fin 7}
    (hpivotFirst : blocks pivot ≠ blocks pairFirst)
    (hpivotSecond : blocks pivot ≠ blocks pairSecond)
    (hpairDistinct : blocks pairFirst ≠ blocks pairSecond) :
    discriminantMinorSum (tetraBlockDesign blocks hsurjective) pivot pairFirst pairSecond
      = 9 := by
  obtain ⟨hpair, hfirst, hsecond⟩ :=
    tetraBlockDesign_squaredPairings_of_rainbow hsurjective hpivotFirst hpivotSecond
      hpairDistinct
  rw [tetraBlockDesign_discriminantMinorSum_eq, hpair, hfirst, hsecond]
  norm_num

/-- A block map is THIN when every direction is used and no three distinct atoms
share a block — equivalently, when the multiplicity profile is `(2,2,2,1)`. -/
def IsThinBlockMap (blocks : Fin 7 → Fin 4) : Prop :=
  Function.Surjective blocks ∧
    ∀ atomFirst atomSecond atomThird : Fin 7, atomFirst ≠ atomSecond →
      atomFirst ≠ atomThird → atomSecond ≠ atomThird →
        ¬ (blocks atomFirst = blocks atomSecond ∧ blocks atomFirst = blocks atomThird)

/-- A `List`-only thinness test. Deciding `IsThinBlockMap` through its `Finset`
quantifiers is far too slow in the kernel — `Finset.univ` on `Fin 7` is rebuilt
inside every nesting level — so the enumeration below routes through this Bool
instead. -/
def isThinBlockMapBool (blocks : Fin 7 → Fin 4) : Bool :=
  ((List.finRange 4).all fun label =>
      (List.finRange 7).any fun atomIndex => blocks atomIndex == label)
    && ((List.finRange 7).all fun atomFirst =>
      (List.finRange 7).all fun atomSecond =>
        (List.finRange 7).all fun atomThird =>
          (atomFirst == atomSecond) || (atomFirst == atomThird) || (atomSecond == atomThird)
            || (blocks atomFirst != blocks atomSecond)
            || (blocks atomFirst != blocks atomThird))

theorem isThinBlockMap_of_bool {blocks : Fin 7 → Fin 4}
    (hbool : isThinBlockMapBool blocks = true) : IsThinBlockMap blocks := by
  rw [isThinBlockMapBool, Bool.and_eq_true] at hbool
  obtain ⟨hsurjectiveBool, hthinBool⟩ := hbool
  rw [List.all_eq_true] at hsurjectiveBool hthinBool
  refine ⟨fun label => ?_, fun atomFirst atomSecond atomThird hfirstSecond hfirstThird
    hsecondThird hboth => ?_⟩
  · have hlabel := hsurjectiveBool label (List.mem_finRange label)
    rw [List.any_eq_true] at hlabel
    obtain ⟨atomIndex, -, hvalue⟩ := hlabel
    exact ⟨atomIndex, by simpa only [beq_iff_eq] using hvalue⟩
  · have houter := hthinBool atomFirst (List.mem_finRange atomFirst)
    rw [List.all_eq_true] at houter
    have hmiddle := houter atomSecond (List.mem_finRange atomSecond)
    rw [List.all_eq_true] at hmiddle
    have hinner := hmiddle atomThird (List.mem_finRange atomThird)
    simp only [Bool.or_eq_true, beq_iff_eq, bne_iff_ne, ne_eq] at hinner
    rcases hinner with ((((hcase | hcase) | hcase) | hcase) | hcase)
    · exact hfirstSecond hcase
    · exact hfirstThird hcase
    · exact hsecondThird hcase
    · exact hcase hboth.1
    · exact hcase hboth.2

/-- At a THIN block map, a triple of distinct atoms that repeats a direction
repeats it exactly twice, so exactly one of its three pairings is `3` and the
other two are `-1`. -/
private theorem tetraBlockDesign_squaredPairingSum_of_repeated {blocks : Fin 7 → Fin 4}
    (hthin : IsThinBlockMap blocks) {pivot pairFirst pairSecond : Fin 7}
    (hpivotFirst : pivot ≠ pairFirst) (hpivotSecond : pivot ≠ pairSecond)
    (hpairDistinct : pairFirst ≠ pairSecond)
    (hrepeat : blocks pivot = blocks pairFirst ∨ blocks pivot = blocks pairSecond
        ∨ blocks pairFirst = blocks pairSecond) :
    atomPairing (tetraBlockDesign blocks hthin.1) pairFirst pairSecond ^ 2
        + atomPairing (tetraBlockDesign blocks hthin.1) pivot pairFirst ^ 2
        + atomPairing (tetraBlockDesign blocks hthin.1) pivot pairSecond ^ 2 = 11
      ∧ atomPairing (tetraBlockDesign blocks hthin.1) pairFirst pairSecond
          * atomPairing (tetraBlockDesign blocks hthin.1) pivot pairFirst
          * atomPairing (tetraBlockDesign blocks hthin.1) pivot pairSecond = 3 := by
  rcases hrepeat with hsame | hsame | hsame
  · have hpivotSecondDifferent : blocks pivot ≠ blocks pairSecond := fun heq =>
      hthin.2 pivot pairFirst pairSecond hpivotFirst hpivotSecond hpairDistinct ⟨hsame, heq⟩
    have hpairDifferent : blocks pairFirst ≠ blocks pairSecond := fun heq =>
      hpivotSecondDifferent (hsame.trans heq)
    rw [tetraBlockDesign_atomPairing_of_differentBlock hthin.1 hpairDifferent,
      tetraBlockDesign_atomPairing_of_sameBlock hthin.1 hsame,
      tetraBlockDesign_atomPairing_of_differentBlock hthin.1 hpivotSecondDifferent]
    norm_num
  · have hpivotFirstDifferent : blocks pivot ≠ blocks pairFirst := fun heq =>
      hthin.2 pivot pairFirst pairSecond hpivotFirst hpivotSecond hpairDistinct ⟨heq, hsame⟩
    have hpairDifferent : blocks pairFirst ≠ blocks pairSecond := fun heq =>
      hpivotFirstDifferent (hsame.trans heq.symm)
    rw [tetraBlockDesign_atomPairing_of_differentBlock hthin.1 hpairDifferent,
      tetraBlockDesign_atomPairing_of_differentBlock hthin.1 hpivotFirstDifferent,
      tetraBlockDesign_atomPairing_of_sameBlock hthin.1 hsame]
    norm_num
  · have hpivotFirstDifferent : blocks pivot ≠ blocks pairFirst := fun heq =>
      hthin.2 pivot pairFirst pairSecond hpivotFirst hpivotSecond hpairDistinct
        ⟨heq, heq.trans hsame⟩
    have hpivotSecondDifferent : blocks pivot ≠ blocks pairSecond := fun heq =>
      hpivotFirstDifferent (heq.trans hsame.symm)
    rw [tetraBlockDesign_atomPairing_of_sameBlock hthin.1 hsame,
      tetraBlockDesign_atomPairing_of_differentBlock hthin.1 hpivotFirstDifferent,
      tetraBlockDesign_atomPairing_of_differentBlock hthin.1 hpivotSecondDifferent]
    norm_num

/-- **A triple repeating a direction FAILS by exactly `-8`**: `8 - 22 + 6`. -/
theorem tetraBlockDesign_discriminantTie_of_repeated {blocks : Fin 7 → Fin 4}
    (hthin : IsThinBlockMap blocks) {pivot pairFirst pairSecond : Fin 7}
    (hpivotFirst : pivot ≠ pairFirst) (hpivotSecond : pivot ≠ pairSecond)
    (hpairDistinct : pairFirst ≠ pairSecond)
    (hrepeat : blocks pivot = blocks pairFirst ∨ blocks pivot = blocks pairSecond
        ∨ blocks pairFirst = blocks pairSecond) :
    discriminantTie (tetraBlockDesign blocks hthin.1) pivot pairFirst pairSecond = -8 := by
  obtain ⟨hsquares, hproduct⟩ := tetraBlockDesign_squaredPairingSum_of_repeated hthin
    hpivotFirst hpivotSecond hpairDistinct hrepeat
  rw [tetraBlockDesign_discriminantTie_eq, show (2 : ℝ)
      * atomPairing (tetraBlockDesign blocks hthin.1) pairFirst pairSecond
        * atomPairing (tetraBlockDesign blocks hthin.1) pivot pairFirst
        * atomPairing (tetraBlockDesign blocks hthin.1) pivot pairSecond
      = 2 * (atomPairing (tetraBlockDesign blocks hthin.1) pairFirst pairSecond
        * atomPairing (tetraBlockDesign blocks hthin.1) pivot pairFirst
        * atomPairing (tetraBlockDesign blocks hthin.1) pivot pairSecond) from by ring,
    hsquares, hproduct]
  norm_num

/-- **A triple repeating a direction has minor sum `1`**: `12 - 11`. Strictly
positive — the `e_2` leg never binds ON THIS FAMILY. -/
theorem tetraBlockDesign_discriminantMinorSum_of_repeated {blocks : Fin 7 → Fin 4}
    (hthin : IsThinBlockMap blocks) {pivot pairFirst pairSecond : Fin 7}
    (hpivotFirst : pivot ≠ pairFirst) (hpivotSecond : pivot ≠ pairSecond)
    (hpairDistinct : pairFirst ≠ pairSecond)
    (hrepeat : blocks pivot = blocks pairFirst ∨ blocks pivot = blocks pairSecond
        ∨ blocks pairFirst = blocks pairSecond) :
    discriminantMinorSum (tetraBlockDesign blocks hthin.1) pivot pairFirst pairSecond = 1 := by
  obtain ⟨hsquares, -⟩ := tetraBlockDesign_squaredPairingSum_of_repeated hthin
    hpivotFirst hpivotSecond hpairDistinct hrepeat
  rw [tetraBlockDesign_discriminantMinorSum_eq, hsquares]
  norm_num

/-- **Every THIN block design is a point of the CLOSED tie-failure system**: all
`35` tie legs are `<= 0`. -/
theorem tetraBlockDesign_discriminantTie_nonpos {blocks : Fin 7 → Fin 4}
    (hthin : IsThinBlockMap blocks) {pivot pairFirst pairSecond : Fin 7}
    (hpivotFirst : pivot ≠ pairFirst) (hpivotSecond : pivot ≠ pairSecond)
    (hpairDistinct : pairFirst ≠ pairSecond) :
    discriminantTie (tetraBlockDesign blocks hthin.1) pivot pairFirst pairSecond ≤ 0 := by
  by_cases hpivotFirstSame : blocks pivot = blocks pairFirst
  · rw [tetraBlockDesign_discriminantTie_of_repeated hthin hpivotFirst hpivotSecond
      hpairDistinct (Or.inl hpivotFirstSame)]
    norm_num
  by_cases hpivotSecondSame : blocks pivot = blocks pairSecond
  · rw [tetraBlockDesign_discriminantTie_of_repeated hthin hpivotFirst hpivotSecond
      hpairDistinct (Or.inr (Or.inl hpivotSecondSame))]
    norm_num
  by_cases hpairSame : blocks pairFirst = blocks pairSecond
  · rw [tetraBlockDesign_discriminantTie_of_repeated hthin hpivotFirst hpivotSecond
      hpairDistinct (Or.inr (Or.inr hpairSame))]
    norm_num
  · rw [tetraBlockDesign_discriminantTie_of_rainbow hthin.1 hpivotFirstSame
      hpivotSecondSame hpairSame]

/-- **The block family's ties are cut out by the DETERMINANT leg alone.** At every
member of the tetrahedral block family with a THIN map, and at every one of its
`35` triples, the symmetric `e_2` leg is at least `1` while the `e_3` leg is at
most `0`, vanishing exactly on the rainbow triples.

SCOPE, and it matters for anyone reading this as facial-reduction data: the
statement is about THIS family and does not extend to the tie stratum at large.
The header records the measured counter-witness — inside
`Gtz.Ties.SplitClassTieFamily`, a `splitClassDesign` at non-uniform class totals
is all-heavy, has all `35` tie legs `<= 0`, and has `e_2 = 0` at four triples, so
"the `e_2` multiplier block stays strictly feasible on the tie stratum" is false
outside the uniform class-total members. -/
theorem tetraBlockDesign_symmetricSignature {blocks : Fin 7 → Fin 4}
    (hthin : IsThinBlockMap blocks) {pivot pairFirst pairSecond : Fin 7}
    (hpivotFirst : pivot ≠ pairFirst) (hpivotSecond : pivot ≠ pairSecond)
    (hpairDistinct : pairFirst ≠ pairSecond) :
    1 ≤ discriminantMinorSum (tetraBlockDesign blocks hthin.1) pivot pairFirst pairSecond
      ∧ discriminantTie (tetraBlockDesign blocks hthin.1) pivot pairFirst pairSecond ≤ 0 := by
  refine ⟨?_, tetraBlockDesign_discriminantTie_nonpos hthin hpivotFirst hpivotSecond
    hpairDistinct⟩
  by_cases hpivotFirstSame : blocks pivot = blocks pairFirst
  · rw [tetraBlockDesign_discriminantMinorSum_of_repeated hthin hpivotFirst hpivotSecond
      hpairDistinct (Or.inl hpivotFirstSame)]
  by_cases hpivotSecondSame : blocks pivot = blocks pairSecond
  · rw [tetraBlockDesign_discriminantMinorSum_of_repeated hthin hpivotFirst hpivotSecond
      hpairDistinct (Or.inr (Or.inl hpivotSecondSame))]
  by_cases hpairSame : blocks pairFirst = blocks pairSecond
  · rw [tetraBlockDesign_discriminantMinorSum_of_repeated hthin hpivotFirst hpivotSecond
      hpairDistinct (Or.inr (Or.inr hpairSame))]
  · rw [tetraBlockDesign_discriminantMinorSum_of_rainbow hthin.1 hpivotFirstSame
      hpivotSecondSame hpairSame]
    norm_num

/-! ### The split tetrahedron is the member at `![0,1,2,3,0,1,2]`

`DecisionAtlasSevenThree` builds `splitSevenDesign` by hand, with the weight
vector written out. It is exactly `tetraBlockDesign splitSevenDirection`, since
`blockLabelWeight` divides each direction's `1/4` by its fibre size and the three
duplicated directions have fibre size two. Identifying them turns every bespoke
`splitSevenDesign_*` lemma there into an instance of a Part II lemma. -/

theorem splitSevenDirection_surjective : Function.Surjective splitSevenDirection := by decide

/-- The three duplicated directions carry weight `1/8` per atom, the singleton
direction `1/4`. -/
theorem blockLabelWeight_splitSeven (label : Fin 4) :
    blockLabelWeight splitSevenDirection label = if label = 3 then 1/4 else 1/8 := by
  have hcard : (blockFibre splitSevenDirection label).card = if label = 3 then 1 else 2 := by
    revert label; decide
  rw [blockLabelWeight, hcard]
  by_cases hsingleton : label = 3
  · rw [if_pos hsingleton, if_pos hsingleton]; norm_num
  · rw [if_neg hsingleton, if_neg hsingleton]; norm_num

/-- **The split tetrahedron IS a block design.** Same atoms by definition, same
weights by `blockLabelWeight_splitSeven`, and the remaining fields are
propositions. -/
theorem splitSevenDesign_eq_tetraBlockDesign :
    splitSevenDesign
      = tetraBlockDesign splitSevenDirection splitSevenDirection_surjective := by
  refine WeightedDesign.ext rfl ?_
  funext atomIndex
  show (![1/8, 1/8, 1/8, 1/4, 1/8, 1/8, 1/8] : Fin 7 → ℝ) atomIndex
      = blockLabelWeight splitSevenDirection (splitSevenDirection atomIndex)
  rw [blockLabelWeight_splitSeven]
  fin_cases atomIndex <;> norm_num [splitSevenDirection] <;> decide

/-! ## Part III. The multiplier-support floor of a Stengle certificate

`Gtz.Certificates.PositivstellensatzObstruction` rules out the whole
Putinar/Schmuedgen half at every degree: the CLOSED tie-failure system is
inhabited (the split tetrahedron), so no identity built from a quadratic module
or a preordering alone can certify emptiness. What survives is the STRICT
Stengle form, whose multiplicative-monoid part is a genuine product

  `S = (product over a support of the strict tie generators) * (region factors)`.

At any point of the CLOSED system the identity `S + P + Z = 0` forces `S >= 0`,
`P >= 0`, `Z = 0` and hence `S = 0`; the region factors `t_c` and
`heavyExcess c` are strictly positive there, so it is the TIE factors that must
vanish. That is the whole content of `IsStengleTieSupportSeven` below, and it is
a statement about the SUPPORT only — multiplicities are irrelevant to vanishing.

WHAT THIS BOUNDS, EXACTLY. `IsStengleTieSupportSeven` quantifies over designs at
which every tie leg is `<= 0`, so the floor is about the ALL-TIE strict system,
not about `DiscriminantCovering 7`. The two are different sentences and
`exists_tieNonneg_notDominates_seven` proves it here: a block design at a NON-thin
surjection has a triple with `e_3 = 8 > 0` and `e_2 = -15 < 0`, so a nonnegative
tie leg does not imply domination. Emptiness of the tie system is necessary for
the covering and never sufficient. The floor therefore says nothing about the
atlas route, and nothing about a certificate whose monoid part uses an `e_2`
generator — `tetraBlockDesign_symmetricSignature` gives `e_2 >= 1 > 0` on the
block family, so such a factor does not vanish there and the argument below does
not apply to it.

Supports are indexed by `increasingTriplesSeven`, one ordered representative per
3-subset: legitimate because `discriminantTie` is `S_3`-invariant
(`exists_increasing_symmetricLegs` of Part I), so the `35` subsets carry `35`
distinct strict generators and not `210` ordered ones.

The floor is then combinatorial. Every member of the tetrahedral block family of
Part II is a point of the closed system whose tie leg vanishes EXACTLY on the
triples carrying three distinct directions, so a support must meet the rainbow
family of every block system. The `105` block systems of `Fin 7` are enumerated
below, and `hasSharedBlockForEveryTrio_true` checks by kernel evaluation that no
THREE triples meet all of them. Hence every support has at least FOUR triples.

Four is sharp FOR THE BLOCK-FAMILY HITTING CONDITION —
`{012, 013, 024, 034}` does meet every rainbow family — but that is MEASURED, not
mechanised here, and it is not sharpness for `IsStengleTieSupportSeven` itself,
whose quantifier ranges over every all-heavy tie-failure design. The degree
reading `4 * 3 = 12` in the Gram entries and `4 * 6 = 24` in the atom coordinates
is INFERRED from the cardinality floor and is presentation-dependent; see the
header. -/

/-- A block map with a CROWDED fibre: three atoms on direction `0`. It is
surjective, hence a legal member of the tetrahedral block family, and it is not
thin. -/
def crowdedBlockMap : Fin 7 → Fin 4 := ![0, 0, 0, 1, 2, 3, 3]

theorem crowdedBlockMap_surjective : Function.Surjective crowdedBlockMap := by decide

/-- **THE SCOPE OF THE FLOOR: the tie leg alone is not the covering.** The three
atoms `0, 1, 2` of the crowded block design all carry the same tetrahedron
direction, so all three of their pairings are `3` and the triple has
`e_3 = 8 - 2 * 27 + 2 * 27 = 8 >= 0` while `e_2 = 12 - 27 = -15 < 0`. It
therefore does NOT dominate. So "some triple has a nonnegative tie leg" is
strictly weaker than "some triple dominates", and a Stengle certificate for the
emptiness of the tie system would not close rank three. (The design is not a
counterexample to anything: seventeen of its other triples do dominate.) -/
theorem exists_tieNonneg_notDominates_seven :
    ∃ design : WeightedDesign 7 3, AllHeavy design ∧
      ∃ first second third : Fin 7, first ≠ second ∧ first ≠ third ∧ second ≠ third
        ∧ 0 ≤ discriminantTie design first second third
        ∧ ¬ Dominates design {first, second, third} := by
  refine ⟨tetraBlockDesign crowdedBlockMap crowdedBlockMap_surjective,
    tetraBlockDesign_allHeavy crowdedBlockMap crowdedBlockMap_surjective,
    0, 1, 2, by decide, by decide, by decide, ?_, ?_⟩
  · rw [tetraBlockDesign_discriminantTie_eq,
      tetraBlockDesign_atomPairing_of_sameBlock crowdedBlockMap_surjective
        (by decide : crowdedBlockMap 1 = crowdedBlockMap 2),
      tetraBlockDesign_atomPairing_of_sameBlock crowdedBlockMap_surjective
        (by decide : crowdedBlockMap 0 = crowdedBlockMap 1),
      tetraBlockDesign_atomPairing_of_sameBlock crowdedBlockMap_surjective
        (by decide : crowdedBlockMap 0 = crowdedBlockMap 2)]
    norm_num
  · rw [dominates_triple_iff_symmetricLegs _ (by decide) (by decide) (by decide)
      (tetraBlockDesign_allHeavy crowdedBlockMap crowdedBlockMap_surjective 0)
      (tetraBlockDesign_allHeavy crowdedBlockMap crowdedBlockMap_surjective 1)
      (tetraBlockDesign_allHeavy crowdedBlockMap crowdedBlockMap_surjective 2)]
    rw [tetraBlockDesign_discriminantMinorSum_eq,
      tetraBlockDesign_atomPairing_of_sameBlock crowdedBlockMap_surjective
        (by decide : crowdedBlockMap 1 = crowdedBlockMap 2),
      tetraBlockDesign_atomPairing_of_sameBlock crowdedBlockMap_surjective
        (by decide : crowdedBlockMap 0 = crowdedBlockMap 1),
      tetraBlockDesign_atomPairing_of_sameBlock crowdedBlockMap_surjective
        (by decide : crowdedBlockMap 0 = crowdedBlockMap 2)]
    norm_num

/-- The `35` increasing index triples of `Fin 7`, as a list, so the kernel search
below runs over `35^3` cases rather than over `343^3`. -/
def triplesSevenList : List (Fin 7 × Fin 7 × Fin 7) :=
  [   (0, 1, 2), (0, 1, 3), (0, 1, 4), (0, 1, 5), (0, 1, 6),
   (0, 2, 3), (0, 2, 4), (0, 2, 5), (0, 2, 6), (0, 3, 4),
   (0, 3, 5), (0, 3, 6), (0, 4, 5), (0, 4, 6), (0, 5, 6),
   (1, 2, 3), (1, 2, 4), (1, 2, 5), (1, 2, 6), (1, 3, 4),
   (1, 3, 5), (1, 3, 6), (1, 4, 5), (1, 4, 6), (1, 5, 6),
   (2, 3, 4), (2, 3, 5), (2, 3, 6), (2, 4, 5), (2, 4, 6),
   (2, 5, 6), (3, 4, 5), (3, 4, 6), (3, 5, 6), (4, 5, 6)]

/-- The `105` block systems of `Fin 7`: every partition into three blocks of size
two and one singleton, labelled so that the singleton carries direction `3`. The
order is chosen to make the kernel search below terminate early. -/
def blockMapsSeven : List (Fin 7 → Fin 4) :=
  [   ![3, 0, 0, 1, 1, 2, 2], ![0, 3, 0, 1, 2, 1, 2], ![0, 0, 3, 1, 2, 2, 1],
   ![0, 1, 2, 3, 0, 1, 2], ![0, 1, 2, 0, 3, 2, 1], ![0, 1, 2, 1, 2, 3, 0],
   ![0, 1, 2, 2, 1, 0, 3], ![3, 0, 1, 0, 2, 1, 2], ![0, 1, 3, 2, 0, 2, 1],
   ![0, 1, 2, 0, 2, 1, 3], ![0, 3, 1, 1, 2, 2, 0], ![0, 1, 1, 2, 3, 0, 2],
   ![0, 1, 0, 3, 1, 2, 2], ![0, 0, 1, 2, 2, 3, 1], ![0, 0, 1, 1, 3, 2, 2],
   ![0, 3, 1, 0, 2, 2, 1], ![0, 1, 2, 3, 1, 2, 0], ![0, 1, 0, 2, 2, 3, 1],
   ![3, 0, 1, 1, 2, 0, 2], ![0, 1, 1, 2, 3, 2, 0], ![0, 1, 3, 1, 0, 2, 2],
   ![0, 3, 1, 2, 1, 0, 2], ![0, 1, 0, 1, 2, 2, 3], ![0, 1, 1, 0, 2, 3, 2],
   ![3, 0, 1, 2, 0, 2, 1], ![0, 3, 1, 2, 0, 1, 2], ![0, 1, 3, 2, 2, 1, 0],
   ![0, 1, 2, 3, 2, 0, 1], ![0, 0, 1, 2, 1, 2, 3], ![0, 1, 0, 2, 3, 1, 2],
   ![0, 1, 3, 0, 1, 2, 2], ![0, 0, 1, 3, 2, 1, 2], ![3, 0, 1, 1, 2, 2, 0],
   ![0, 3, 1, 2, 2, 0, 1], ![0, 1, 1, 2, 0, 3, 2], ![0, 1, 2, 1, 2, 0, 3],
   ![3, 0, 0, 1, 2, 2, 1], ![0, 0, 1, 3, 1, 2, 2], ![3, 0, 1, 0, 2, 2, 1],
   ![0, 3, 1, 1, 2, 0, 2], ![0, 1, 1, 2, 2, 3, 0], ![0, 1, 2, 2, 0, 1, 3],
   ![0, 0, 3, 1, 1, 2, 2], ![0, 0, 1, 2, 3, 1, 2], ![3, 0, 0, 1, 2, 1, 2],
   ![0, 3, 0, 1, 2, 2, 1], ![0, 1, 3, 2, 0, 1, 2], ![0, 1, 2, 3, 0, 2, 1],
   ![0, 1, 1, 0, 3, 2, 2], ![0, 0, 1, 1, 2, 2, 3], ![3, 0, 1, 2, 2, 1, 0],
   ![0, 1, 3, 2, 1, 0, 2], ![0, 1, 1, 3, 0, 2, 2], ![0, 0, 1, 2, 1, 3, 2],
   ![0, 1, 2, 0, 2, 3, 1], ![3, 0, 1, 2, 2, 0, 1], ![0, 3, 1, 0, 2, 1, 2],
   ![0, 1, 3, 2, 2, 0, 1], ![0, 1, 2, 3, 1, 0, 2], ![0, 0, 1, 2, 3, 2, 1],
   ![0, 1, 0, 2, 3, 2, 1], ![0, 1, 0, 2, 1, 2, 3], ![0, 1, 0, 2, 2, 1, 3],
   ![0, 3, 1, 2, 0, 2, 1], ![0, 1, 3, 0, 2, 2, 1], ![0, 0, 1, 3, 2, 2, 1],
   ![0, 1, 0, 1, 3, 2, 2], ![0, 0, 1, 1, 2, 3, 2], ![0, 1, 0, 1, 2, 3, 2],
   ![3, 0, 1, 1, 0, 2, 2], ![3, 0, 1, 2, 0, 1, 2], ![0, 3, 1, 1, 0, 2, 2],
   ![0, 1, 3, 0, 2, 1, 2], ![0, 1, 0, 3, 2, 2, 1], ![0, 1, 2, 0, 3, 1, 2],
   ![0, 1, 0, 2, 1, 3, 2], ![0, 0, 1, 2, 2, 1, 3], ![0, 1, 2, 0, 1, 2, 3],
   ![0, 1, 2, 1, 0, 2, 3], ![0, 3, 0, 1, 1, 2, 2], ![0, 3, 1, 0, 1, 2, 2],
   ![0, 0, 3, 1, 2, 1, 2], ![0, 1, 3, 1, 2, 0, 2], ![0, 1, 0, 3, 2, 1, 2],
   ![0, 1, 1, 3, 2, 0, 2], ![0, 1, 2, 1, 3, 0, 2], ![0, 1, 2, 2, 3, 0, 1],
   ![0, 1, 2, 0, 1, 3, 2], ![0, 1, 2, 1, 0, 3, 2], ![3, 0, 1, 0, 1, 2, 2],
   ![3, 0, 1, 2, 1, 0, 2], ![3, 0, 1, 2, 1, 2, 0], ![0, 3, 1, 2, 1, 2, 0],
   ![0, 3, 1, 2, 2, 1, 0], ![0, 1, 3, 1, 2, 2, 0], ![0, 1, 3, 2, 1, 2, 0],
   ![0, 1, 1, 3, 2, 2, 0], ![0, 1, 2, 3, 2, 1, 0], ![0, 1, 2, 1, 3, 2, 0],
   ![0, 1, 2, 2, 3, 1, 0], ![0, 1, 2, 2, 0, 3, 1], ![0, 1, 2, 2, 1, 3, 0],
   ![0, 1, 1, 0, 2, 2, 3], ![0, 1, 1, 2, 0, 2, 3], ![0, 1, 1, 2, 2, 0, 3]]

/-- Every listed block system is thin, so each of them defines a member of the
tetrahedral block family of Part II. -/
theorem blockMapsSeven_thin : ∀ blocks ∈ blockMapsSeven, IsThinBlockMap blocks := by
  have hbool : blockMapsSeven.all isThinBlockMapBool = true := by decide
  rw [List.all_eq_true] at hbool
  exact fun blocks hmem => isThinBlockMap_of_bool (hbool blocks hmem)

/-- Does a triple share a block? True when two of its three atoms carry the same
direction — equivalently, when it is not rainbow, and then its tie leg is `-8`. -/
def isBlockSharedInTriple (blocks : Fin 7 → Fin 4) (triple : Fin 7 × Fin 7 × Fin 7) : Bool :=
  (blocks triple.1 == blocks triple.2.1)
    || ((blocks triple.1 == blocks triple.2.2) || (blocks triple.2.1 == blocks triple.2.2))

theorem blocksAgreeSomewhere_of_isBlockSharedInTriple {blocks : Fin 7 → Fin 4}
    {triple : Fin 7 × Fin 7 × Fin 7}
    (hshares : isBlockSharedInTriple blocks triple = true) :
    blocks triple.1 = blocks triple.2.1 ∨ blocks triple.1 = blocks triple.2.2
      ∨ blocks triple.2.1 = blocks triple.2.2 := by
  simpa only [isBlockSharedInTriple, Bool.or_eq_true, beq_iff_eq] using hshares

/-- The kernel search: does every ordered choice of three of the `35` triples have
some one of the `105` block systems making all three share a block? -/
def hasSharedBlockForEveryTrio : Bool :=
  triplesSevenList.all fun first => triplesSevenList.all fun second =>
    triplesSevenList.all fun third =>
      blockMapsSeven.any fun blocks =>
        isBlockSharedInTriple blocks first && isBlockSharedInTriple blocks second
          && isBlockSharedInTriple blocks third

set_option maxRecDepth 20000 in
set_option maxHeartbeats 4000000 in
/-- **THE COMBINATORIAL FLOOR**, by kernel evaluation of `35^3` cases: no three
triples of `Fin 7` meet the rainbow family of every block system. -/
theorem hasSharedBlockForEveryTrio_true : hasSharedBlockForEveryTrio = true := by decide

/-- The extracted form of the search. -/
theorem exists_blockMap_sharing {first second third : Fin 7 × Fin 7 × Fin 7}
    (hfirst : first ∈ triplesSevenList) (hsecond : second ∈ triplesSevenList)
    (hthird : third ∈ triplesSevenList) :
    ∃ blocks ∈ blockMapsSeven, isBlockSharedInTriple blocks first = true
      ∧ isBlockSharedInTriple blocks second = true
      ∧ isBlockSharedInTriple blocks third = true := by
  have houter := hasSharedBlockForEveryTrio_true
  rw [hasSharedBlockForEveryTrio, List.all_eq_true] at houter
  have hmiddle := houter first hfirst
  rw [List.all_eq_true] at hmiddle
  have hinner := hmiddle second hsecond
  rw [List.all_eq_true] at hinner
  have hfound := hinner third hthird
  rw [List.any_eq_true] at hfound
  obtain ⟨blocks, hmem, hconjunction⟩ := hfound
  rw [Bool.and_eq_true, Bool.and_eq_true] at hconjunction
  exact ⟨blocks, hmem, hconjunction.1.1, hconjunction.1.2, hconjunction.2⟩

/-- The list holds every strictly increasing index triple. -/
private theorem triplesSevenList_complete :
    ∀ first second third : Fin 7, first < second → second < third →
      (first, second, third) ∈ triplesSevenList := by decide

/-- The canonical index set of the covering is exactly the list searched above. -/
theorem mem_triplesSevenList_of_mem_increasing {triple : Fin 7 × Fin 7 × Fin 7}
    (hmem : triple ∈ increasingTriplesSeven) : triple ∈ triplesSevenList := by
  rw [increasingTriplesSeven, Finset.mem_filter] at hmem
  exact triplesSevenList_complete triple.1 triple.2.1 triple.2.2 hmem.2.1 hmem.2.2

/-- At a thin block design, a triple that shares a block fails by exactly `-8`. -/
private theorem tetraBlockDesign_tie_of_isBlockSharedInTriple {blocks : Fin 7 → Fin 4}
    (hthin : IsThinBlockMap blocks) {triple : Fin 7 × Fin 7 × Fin 7}
    (hmem : triple ∈ increasingTriplesSeven)
    (hshares : isBlockSharedInTriple blocks triple = true) :
    discriminantTie (tetraBlockDesign blocks hthin.1) triple.1 triple.2.1 triple.2.2 = -8 := by
  obtain ⟨hfirstSecond, hfirstThird, hsecondThird⟩ := increasingTriplesSeven_distinct hmem
  exact tetraBlockDesign_discriminantTie_of_repeated hthin hfirstSecond hfirstThird
    hsecondThird (blocksAgreeSomewhere_of_isBlockSharedInTriple hshares)

/-- **The tie-generator support of a Stengle monoid multiplier.** A strict
Stengle certificate for the emptiness of the tie-failure system carries a factor
`prod over the support of (- discriminantTie T)^(e_T)` with every `e_T >= 1`, and
at every point of the CLOSED system that factor must vanish while the region
factors do not. Since a product of reals vanishes exactly when one factor does,
the certificate's support has to contain, at every such point, a triple whose tie
leg is exactly `0`. That — and nothing about degrees, multiplicities, or
polynomiality — is what is recorded here. -/
def IsStengleTieSupportSeven (support : Finset (Fin 7 × Fin 7 × Fin 7)) : Prop :=
  ∀ design : WeightedDesign 7 3, AllHeavy design →
    (∀ triple ∈ increasingTriplesSeven,
        discriminantTie design triple.1 triple.2.1 triple.2.2 ≤ 0) →
      ∃ triple ∈ support, discriminantTie design triple.1 triple.2.1 triple.2.2 = 0

/-- **The definition is exactly calibrated, neither vacuous nor free.** The FULL
index set is an admissible support precisely when the tie leg alone covers — a
consequence of `DiscriminantCovering 7`, hence open, hence not something this
file trivially supplies. -/
theorem isStengleTieSupportSeven_increasing_iff :
    IsStengleTieSupportSeven increasingTriplesSeven ↔
      ∀ design : WeightedDesign 7 3, AllHeavy design →
        ∃ triple ∈ increasingTriplesSeven,
          0 ≤ discriminantTie design triple.1 triple.2.1 triple.2.2 := by
  constructor
  · intro hsupport design hheavy
    by_cases hnonpos : ∀ triple ∈ increasingTriplesSeven,
        discriminantTie design triple.1 triple.2.1 triple.2.2 ≤ 0
    · obtain ⟨triple, hmem, hzero⟩ := hsupport design hheavy hnonpos
      exact ⟨triple, hmem, le_of_eq hzero.symm⟩
    · push Not at hnonpos
      obtain ⟨triple, hmem, hpositive⟩ := hnonpos
      exact ⟨triple, hmem, le_of_lt hpositive⟩
  · intro hcover design hheavy hnonpos
    obtain ⟨triple, hmem, hnonneg⟩ := hcover design hheavy
    exact ⟨triple, hmem, le_antisymm (hnonpos triple hmem) hnonneg⟩

/-- **THE SUPPORT FLOOR.** No set of at most three triples is the tie-generator
support of a Stengle certificate at `(7,3)`. The witness is a member of the
tetrahedral block family: it is all-heavy, every one of its `35` tie legs is
`<= 0`, and the three chosen triples all fail by exactly `-8`, so none of them
vanishes. -/
theorem not_isStengleTieSupportSeven_of_card_le_three
    {support : Finset (Fin 7 × Fin 7 × Fin 7)} (hsubset : support ⊆ increasingTriplesSeven)
    (hcard : support.card ≤ 3) : ¬ IsStengleTieSupportSeven support := by
  obtain ⟨enlarged, hsupportSub, hEnlargedSub, hcardThree⟩ :=
    Finset.exists_subsuperset_card_eq hsubset hcard
      (by rw [increasingTriplesSeven_card]; norm_num)
  obtain ⟨first, second, third, -, -, -, hEnlarged⟩ := Finset.card_eq_three.mp hcardThree
  have hfirstMem : first ∈ increasingTriplesSeven := hEnlargedSub (by rw [hEnlarged]; simp)
  have hsecondMem : second ∈ increasingTriplesSeven := hEnlargedSub (by rw [hEnlarged]; simp)
  have hthirdMem : third ∈ increasingTriplesSeven := hEnlargedSub (by rw [hEnlarged]; simp)
  obtain ⟨blocks, hblocksMem, hfirstShares, hsecondShares, hthirdShares⟩ :=
    exists_blockMap_sharing (mem_triplesSevenList_of_mem_increasing hfirstMem)
      (mem_triplesSevenList_of_mem_increasing hsecondMem)
      (mem_triplesSevenList_of_mem_increasing hthirdMem)
  have hthin : IsThinBlockMap blocks := blockMapsSeven_thin blocks hblocksMem
  intro hstengle
  obtain ⟨triple, hmem, hzero⟩ := hstengle (tetraBlockDesign blocks hthin.1)
    (tetraBlockDesign_allHeavy blocks hthin.1) (fun triple hmem => by
      obtain ⟨hfirstSecond, hfirstThird, hsecondThird⟩ := increasingTriplesSeven_distinct hmem
      exact tetraBlockDesign_discriminantTie_nonpos hthin hfirstSecond hfirstThird hsecondThird)
  have hinEnlarged : triple ∈ ({first, second, third} : Finset (Fin 7 × Fin 7 × Fin 7)) := by
    rw [← hEnlarged]; exact hsupportSub hmem
  rw [Finset.mem_insert, Finset.mem_insert, Finset.mem_singleton] at hinEnlarged
  rcases hinEnlarged with hchoice | hchoice | hchoice
  · rw [hchoice, tetraBlockDesign_tie_of_isBlockSharedInTriple hthin hfirstMem
      hfirstShares] at hzero
    norm_num at hzero
  · rw [hchoice, tetraBlockDesign_tie_of_isBlockSharedInTriple hthin hsecondMem
      hsecondShares] at hzero
    norm_num at hzero
  · rw [hchoice, tetraBlockDesign_tie_of_isBlockSharedInTriple hthin hthirdMem
      hthirdShares] at hzero
    norm_num at hzero

/-- **The floor, as a cardinality statement.** Every Stengle tie-generator support
at `(7,3)` has at least four triples. The degree reading that follows —
`4 * 3 = 12` in the `28` Gram entries, `4 * 6 = 24` in the `21` atom coordinates —
is INFERRED, not mechanised, and holds only for the presentation whose strict
generators are the `35` tie legs, and only for the ALL-TIE system, which
`exists_tieNonneg_notDominates_seven` shows is strictly weaker than
`DiscriminantCovering 7`. -/
theorem four_le_card_of_isStengleTieSupportSeven
    {support : Finset (Fin 7 × Fin 7 × Fin 7)} (hsubset : support ⊆ increasingTriplesSeven)
    (hstengle : IsStengleTieSupportSeven support) : 4 ≤ support.card := by
  by_contra hsmall
  exact not_isStengleTieSupportSeven_of_card_le_three hsubset (by omega) hstengle

end Gtz
