/-
# The realness engine: equiangularity settled, and the Bargmann triangle certificate

Realness is the one ingredient no GTZ proof can avoid: weighted `(4,2)` and
weighted `(6,3)` are both FALSE over `ℂ` (`complexGtzWeighted_four_fails`,
`complexGtzWeighted_six_three_fails`), so every argument must consume the ground
field somewhere. This file makes two field-sensitive structures explicit and
kernel-checks what each one does, and does not, deliver.

**1. Equiangular lines are the wrong separator, and the proof is the icosahedron.**
The maximum number of pairwise equiangular lines is `6` in `ℝ³` against `9` in
`ℂ³`, which invites the guess that the binding `(6,3)` case is that `6`-vs-`9`
gap. It is not, and the exact facts here say so:

* `icosaDesign` — the maximal real equiangular set in `ℝ³`, six lines at squared
  cosine `1/5`, is a genuine weighted `(6,3)` design (`icosaAtom_isEquiangular`,
  `icosaAtom_distinct_lines`) which dominates STRICTLY
  (`icosaDesign_strictly_dominates`), with margin exactly `2 − 3/√5`, pinned two-
  sidedly (`icosaDesign_rayleigh_floor`, `icosaDesign_rayleigh_attained`) inside
  the rational window `(1/2, 2/3)` (`icosa_margin_window`). The real ceiling is a
  comfortable DOMINATOR, not an obstruction;
* `splitTetraAtom_not_equiangular` / `splitTetraAtom_lineCount_four` — the repo's
  own `(6,3)` tie carries only FOUR distinct lines, not six;
* `sharpAtom_not_equiangular` — the non-tetrahedral `(4,3)` tie has two squared
  cosines, `1/19` and `64/361`, so real ties are not forced equiangular at all;
* `paddedAtom_spikes_share_a_line` / `paddedAtom_not_equiangular` — the shipped
  `(6,3)` complex witness is not nine equiangular lines in `ℂ³`. Its two spikes
  span ONE line and each is orthogonal to each flat atom, so three squared cosines
  occur (`1`, `0`, and the SIC's `1/3`) and the family is not equiangular: it is
  FIVE lines, the `ℂ²` SIC direct-summed with an orthogonal antipodal pair.

**2. The Bargmann triangle invariant is the right separator — and it is exactly
realness.** For a triangle of atoms the invariant `T = ⟨a,b⟩⟨b,c⟩⟨c,a⟩` is real
for free over `ℝ` (`realFamily_hasRealTriangleBargmann`, whose real-side content
is the `ring` identity `realTriangle_bargmann_extremal`), and for the complex
witnesses it is PURELY IMAGINARY — the maximal possible deviation from realness:
`−8√3/9` for the SIC (`sicBargmann_im`, `sicBargmann_re`) and `−8000√3/6561` for
the padded SIC (`paddedBargmann_im`), so both fail the certificate
(`sicAtom_not_hasRealTriangleBargmann`, `paddedAtom_not_hasRealTriangleBargmann`,
assembled as `realness_gate_separates`).

That is a genuine candidate minimal realness axiom: it quantifies over no subset,
mentions no eigenvalue and no Loewner order, so it is not a rename of DOMINATION —
`icosaDesign` and `tetraDesign` both satisfy it while one dominates strictly and
the other only ties, so the certificate does not determine the margin. But it looks
like a rename of REALNESS, and that is the ceiling: over an overlap support whose
cycle space is generated by triangles, "every triangle invariant is real" is the
standard gauge criterion for a Gram matrix to be diagonally equivalent to a real
one — an UNMECHANISED classical input, stated here as a caveat and not used by any
proof below — so "this certificate implies domination" would be `GtzWeighted 6 3`
itself rather than a weaker step toward it. Recorded as an honest ceiling on the
realness-first strategy, not as progress against the residue.
-/
import Mathlib
import Gtz.Core.Basic
import Gtz.Core.Sanity
import Gtz.LinAlg.SchurRankOne
import Gtz.Design.StressCertificate
import Gtz.Reduction.RayleighCertificate
import Gtz.Ties.NonTetrahedralTie
import Gtz.Ties.SplitTetrahedronTie
import Gtz.Complex.ComplexPadding

set_option autoImplicit false
set_option relaxedAutoImplicit false

namespace Gtz

open Matrix

/-! ## Equiangularity, over `ℝ` and over `ℂ`

Two lines through the origin sit at squared cosine `cosSqValue` when
`⟨u,v⟩² = cosSqValue·|u|²·|v|²`; a family is equiangular when one value serves
every distinct pair. Squared cosine `1` is Cauchy–Schwarz equality, i.e. the two
vectors span the SAME line — that is how the line COUNTS below are read off. -/

/-- A real family is equiangular at squared cosine `cosSqValue`. -/
def IsEquiangularAt {m k : ℕ} (vec : Fin m → (Fin k → ℝ)) (cosSqValue : ℝ) : Prop :=
  ∀ first second : Fin m, first ≠ second →
    (vec first ⬝ᵥ vec second) ^ 2
      = cosSqValue * ((vec first ⬝ᵥ vec first) * (vec second ⬝ᵥ vec second))

/-- Two real vectors span the same line: Cauchy–Schwarz holds with equality. -/
def SpansSameLine {k : ℕ} (leftVec rightVec : Fin k → ℝ) : Prop :=
  (leftVec ⬝ᵥ rightVec) ^ 2 = (leftVec ⬝ᵥ leftVec) * (rightVec ⬝ᵥ rightVec)

/-- A complex family is equiangular at squared cosine `cosSqValue`. -/
def ComplexIsEquiangularAt {m k : ℕ} (vec : Fin m → (Fin k → ℂ)) (cosSqValue : ℂ) :
    Prop :=
  ∀ first second : Fin m, first ≠ second →
    (star (vec first) ⬝ᵥ vec second) * (star (vec second) ⬝ᵥ vec first)
      = cosSqValue
        * ((star (vec first) ⬝ᵥ vec first) * (star (vec second) ⬝ᵥ vec second))

/-- Two complex vectors span the same line. -/
def ComplexSpansSameLine {k : ℕ} (leftVec rightVec : Fin k → ℂ) : Prop :=
  (star leftVec ⬝ᵥ rightVec) * (star rightVec ⬝ᵥ leftVec)
    = (star leftVec ⬝ᵥ leftVec) * (star rightVec ⬝ᵥ rightVec)

/-! ## The repo's real configurations, exactly

`tetraAtom` IS equiangular; the `(6,3)` tie and the non-tetrahedral `(4,3)` tie
are NOT. -/

/-- The regular tetrahedron is equiangular at squared cosine `1/9`: leverage `3`
everywhere, every distinct pair squaring to `1`. -/
theorem tetraAtom_isEquiangular : IsEquiangularAt tetraAtom (1 / 9) := by
  intro first second hne
  rw [tetraAtom_dot_sq_of_ne hne, tetraAtom_dot_self, tetraAtom_dot_self]
  norm_num

/-- The four tetrahedron directions span four DISTINCT lines. -/
theorem tetraAtom_distinct_lines {first second : Fin 4} (hne : first ≠ second) :
    ¬ SpansSameLine (tetraAtom first) (tetraAtom second) := by
  rw [SpansSameLine, tetraAtom_dot_sq_of_ne hne, tetraAtom_dot_self,
    tetraAtom_dot_self]
  norm_num

/-- The `(6,3)` split-tetrahedron tie is NOT an equiangular family: the duplicated
pair `(2,3)` sits at squared cosine `1`, the pair `(0,1)` at `1/9`. -/
theorem splitTetraAtom_not_equiangular :
    ¬ ∃ cosSqValue : ℝ, IsEquiangularAt splitTetraAtom cosSqValue := by
  rintro ⟨cosSqValue, hequi⟩
  have hdup := hequi 2 3 (by decide)
  have hsep := hequi 0 1 (by decide)
  have hdupAtom : splitTetraAtom (2 : Fin 6) = splitTetraAtom (3 : Fin 6) := rfl
  have hlevThree : splitTetraAtom (3 : Fin 6) ⬝ᵥ splitTetraAtom (3 : Fin 6) = 3 :=
    tetraAtom_dot_self _
  have hlevZero : splitTetraAtom (0 : Fin 6) ⬝ᵥ splitTetraAtom (0 : Fin 6) = 3 :=
    tetraAtom_dot_self _
  have hlevOne : splitTetraAtom (1 : Fin 6) ⬝ᵥ splitTetraAtom (1 : Fin 6) = 3 :=
    tetraAtom_dot_self _
  have hcross :
      (splitTetraAtom (0 : Fin 6) ⬝ᵥ splitTetraAtom (1 : Fin 6)) ^ 2 = 1 :=
    splitTetraAtom_dot_sq_of_ne (by decide)
  rw [hdupAtom, hlevThree] at hdup
  rw [hlevZero, hlevOne, hcross] at hsep
  norm_num at hdup hsep
  linarith

/-- The six atoms of the `(6,3)` tie fall into exactly the four tetrahedron
directions: two spans agree iff their direction indices agree. -/
theorem splitTetraAtom_sameLine_iff (first second : Fin 6) :
    SpansSameLine (splitTetraAtom first) (splitTetraAtom second)
      ↔ splitTetraDirIndex first = splitTetraDirIndex second := by
  constructor
  · intro hsame
    by_contra hne
    exact tetraAtom_distinct_lines hne hsame
  · intro heq
    have hatomEq : splitTetraAtom first = splitTetraAtom second := by
      simp only [splitTetraAtom, heq]
    have hlev : splitTetraAtom second ⬝ᵥ splitTetraAtom second = 3 :=
      tetraAtom_dot_self _
    rw [SpansSameLine, hatomEq, hlev]
    norm_num

/-- **The `(6,3)` tie carries exactly FOUR distinct lines, not six.** The real
maximum in `ℝ³` is six; the campaign's `(6,3)` tie sits two lines below it. -/
theorem splitTetraAtom_lineCount_four :
    (Finset.univ.image splitTetraDirIndex).card = 4 := by decide

/-- **Real ties are not forced equiangular.** The non-tetrahedral `(4,3)` tie has
squared cosine `1/19` on the pairs through atom `0` and `64/361` elsewhere, and
`1/19 = 19/361 ≠ 64/361`. -/
theorem sharpAtom_not_equiangular :
    ¬ ∃ cosSqValue : ℝ, IsEquiangularAt sharpAtom cosSqValue := by
  rintro ⟨cosSqValue, hequi⟩
  have hshort := hequi 0 1 (by decide)
  have hlong := hequi 1 2 (by decide)
  simp only [sharpAtom, dotProduct, Fin.sum_univ_three, Matrix.cons_val_zero,
    Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_two,
    Matrix.tail_cons] at hshort hlong
  norm_num at hshort hlong
  linarith

/-! ## The maximal real equiangular set in `ℝ³` — and it DOMINATES

Six equiangular lines is the real maximum in dimension three (Lemmens–Seidel),
attained by the icosahedron diagonals at squared cosine `1/5`. Scaled to leverage
`3` the six diagonals are a weighted `(6,3)` design at uniform weight `1/6`, and
the triple `{0,2,4}` — the one whose three overlaps all carry the SAME sign —
dominates strictly. So the equiangular ceiling cannot be what obstructs `(6,3)`:
sitting exactly on that ceiling is comfortable. -/

/-- The common overlap modulus of the icosahedron at leverage `3`: `3/√5`. -/
noncomputable def icosaRadius : ℝ := 3 * Real.sqrt 5 / 5

theorem icosaRadius_sq : icosaRadius ^ 2 = 9 / 5 := by
  have hfive : Real.sqrt 5 ^ 2 = 5 := Real.sq_sqrt (by norm_num)
  rw [icosaRadius, div_pow, mul_pow, hfive]
  norm_num

theorem icosaRadius_pos : 0 < icosaRadius := by
  have hsqrtPos : 0 < Real.sqrt 5 := Real.sqrt_pos.mpr (by norm_num)
  rw [icosaRadius]
  linarith

/-- `1 < 3/√5` — needed for the short entry to be a real number. -/
theorem icosaRadius_lower : 1 < icosaRadius := by
  nlinarith [icosaRadius_sq, icosaRadius_pos]

/-- `3/√5 < 3/2` — the window that gives the strict domination margin `2 − 3/√5`. -/
theorem icosaRadius_upper : icosaRadius < 3 / 2 := by
  nlinarith [icosaRadius_sq, icosaRadius_pos]

/-- The short entry of an icosahedron diagonal. -/
noncomputable def icosaShort : ℝ := Real.sqrt ((3 - icosaRadius) / 2)

/-- The long entry of an icosahedron diagonal. -/
noncomputable def icosaLong : ℝ := Real.sqrt ((3 + icosaRadius) / 2)

theorem icosaShort_sq : icosaShort ^ 2 = (3 - icosaRadius) / 2 :=
  Real.sq_sqrt (by nlinarith [icosaRadius_upper])

theorem icosaLong_sq : icosaLong ^ 2 = (3 + icosaRadius) / 2 :=
  Real.sq_sqrt (by nlinarith [icosaRadius_pos])

/-- The two entries multiply to the overlap modulus itself — the identity that
makes every off-diagonal Gram entry `±3/√5`. -/
theorem icosaShort_mul_icosaLong : icosaShort * icosaLong = icosaRadius := by
  have hnonneg : (0 : ℝ) ≤ (3 - icosaRadius) / 2 := by nlinarith [icosaRadius_upper]
  have hprod : (3 - icosaRadius) / 2 * ((3 + icosaRadius) / 2) = icosaRadius ^ 2 := by
    linear_combination (-(5 : ℝ) / 4) * icosaRadius_sq
  rw [icosaShort, icosaLong, ← Real.sqrt_mul hnonneg, hprod,
    Real.sqrt_sq icosaRadius_pos.le]

/-- The six icosahedron diagonals at leverage `3`, in cyclic form: each coordinate
pair carries one `±short` and one `long`. -/
noncomputable def icosaAtom : Fin 6 → Fin 3 → ℝ :=
  ![![icosaShort, icosaLong, 0], ![-icosaShort, icosaLong, 0],
    ![0, icosaShort, icosaLong], ![0, -icosaShort, icosaLong],
    ![icosaLong, 0, icosaShort], ![icosaLong, 0, -icosaShort]]

/-- Every diagonal has leverage `3` — the normalisation that makes uniform weight
`1/6` resolve the identity. -/
theorem icosaAtom_leverage (index : Fin 6) :
    icosaAtom index ⬝ᵥ icosaAtom index = 3 := by
  have hs := icosaShort_sq
  have hl := icosaLong_sq
  fin_cases index <;> simp [icosaAtom, dotProduct, Fin.sum_univ_three] <;>
    linear_combination hs + hl

/-- **Every distinct pair of diagonals overlaps to `±3/√5`**, so the squared overlap
is uniformly `9/5` — equiangularity in its raw form. Thirty ordered pairs, each
closed by one of only TWO certificates: the overlap is either `long² − short²` or
`±short·long`, and squaring erases the sign. -/
theorem icosaAtom_dot_sq_of_ne {first second : Fin 6} (hne : first ≠ second) :
    (icosaAtom first ⬝ᵥ icosaAtom second) ^ 2 = 9 / 5 := by
  have hs := icosaShort_sq
  have hl := icosaLong_sq
  have hsl := icosaShort_mul_icosaLong
  have hr := icosaRadius_sq
  fin_cases first <;> fin_cases second <;>
    simp [icosaAtom, dotProduct, Fin.sum_univ_three] <;>
    first
      | exact absurd rfl hne
      | linear_combination (icosaShort * icosaLong + icosaRadius) * hsl + hr
      | linear_combination
          (icosaLong ^ 2 - icosaShort ^ 2 + icosaRadius) * hl
            - (icosaLong ^ 2 - icosaShort ^ 2 + icosaRadius) * hs + hr

/-- **The icosahedron is equiangular at squared cosine `1/5`** — the real maximum
in `ℝ³`, realised. -/
theorem icosaAtom_isEquiangular : IsEquiangularAt icosaAtom (1 / 5) := by
  intro first second hne
  rw [icosaAtom_dot_sq_of_ne hne, icosaAtom_leverage, icosaAtom_leverage]
  norm_num

/-- **The six diagonals span six DISTINCT lines**: squared cosine `1/5`, not `1`. -/
theorem icosaAtom_distinct_lines {first second : Fin 6} (hne : first ≠ second) :
    ¬ SpansSameLine (icosaAtom first) (icosaAtom second) := by
  rw [SpansSameLine, icosaAtom_dot_sq_of_ne hne, icosaAtom_leverage,
    icosaAtom_leverage]
  norm_num

set_option linter.unusedSimpArgs false in
/-- **The maximal real equiangular set is a weighted `(6,3)` design**, at uniform
weight `1/6`: each coordinate pair contributes `2·short²` and `2·long²` to one
diagonal entry, and every cross term cancels against its sign partner. -/
noncomputable def icosaDesign : WeightedDesign 6 3 where
  atom := icosaAtom
  weight := fun _ => (1 : ℝ) / 6
  weight_pos := fun _ => by norm_num
  weight_sum_one := by rw [Fin.sum_univ_six]; norm_num
  isParseval := by
    have hs := icosaShort_sq
    have hl := icosaLong_sq
    ext rowIndex colIndex
    simp only [Matrix.sum_apply, Matrix.smul_apply, atomMatrix,
      Matrix.vecMulVec_apply, Fin.sum_univ_six, smul_eq_mul]
    fin_cases rowIndex <;> fin_cases colIndex <;>
      simp only [icosaAtom, Matrix.cons_val', Matrix.cons_val_zero,
        Matrix.cons_val_one, Matrix.head_cons, Matrix.empty_val',
        Matrix.cons_val_fin_one, Matrix.cons_val_succ, Matrix.cons_val_two,
        Matrix.cons_val_three, Matrix.cons_val_four, Matrix.cons_val,
        Matrix.tail_cons, Matrix.one_apply] <;>
      norm_num <;>
      linear_combination hs / 3 + hl / 3

@[simp] theorem icosaDesign_atom : icosaDesign.atom = icosaAtom := rfl

/-- The excess of the triple `{0,2,4}` is the circulant `2·I + icosaRadius·(J − I)`,
read through its quadratic form:
`icosaRadius·(x₀+x₁+x₂)² + (2 − icosaRadius)·|x|²`. Both coefficients are positive
because `1 < icosaRadius < 3/2 < 2`. -/
theorem icosaDesign_excess_form (vecArg : Fin 3 → ℝ) :
    vecArg ⬝ᵥ ((subsetSum icosaDesign {0, 2, 4} - 1) *ᵥ vecArg)
      = icosaRadius * (vecArg 0 + vecArg 1 + vecArg 2) ^ 2
        + (2 - icosaRadius) * (vecArg ⬝ᵥ vecArg) := by
  have hs := icosaShort_sq
  have hl := icosaLong_sq
  have hsl := icosaShort_mul_icosaLong
  rw [dominationGap_form,
    show ({0, 2, 4} : Finset (Fin 6)) = insert 0 (insert 2 {4}) from rfl,
    Finset.sum_insert (by decide), Finset.sum_insert (by decide),
    Finset.sum_singleton]
  simp [icosaDesign_atom, icosaAtom, dotProduct, Fin.sum_univ_three]
  linear_combination (vecArg 0 ^ 2 + vecArg 1 ^ 2 + vecArg 2 ^ 2) * hs
    + (vecArg 0 ^ 2 + vecArg 1 ^ 2 + vecArg 2 ^ 2) * hl
    + (2 * vecArg 0 * vecArg 1 + 2 * vecArg 0 * vecArg 2
      + 2 * vecArg 1 * vecArg 2) * hsl

/-- **The maximal real equiangular design dominates.** -/
theorem icosaDesign_dominates : Dominates icosaDesign {0, 2, 4} := by
  refine Matrix.posSemidef_iff_dotProduct_mulVec.mpr ⟨?_, fun vecArg => ?_⟩
  · exact ((Matrix.posSemidef_sum ({0, 2, 4} : Finset (Fin 6)) fun c _ =>
      posSemidef_atomMatrix (icosaDesign.atom c)).1).sub Matrix.isHermitian_one
  · have hnormNonneg : (0 : ℝ) ≤ vecArg ⬝ᵥ vecArg :=
      Finset.sum_nonneg fun i _ => mul_self_nonneg (vecArg i)
    rw [star_trivial, icosaDesign_excess_form]
    nlinarith [sq_nonneg (vecArg 0 + vecArg 1 + vecArg 2), icosaRadius_pos,
      icosaRadius_upper, hnormNonneg]

/-- **It dominates STRICTLY** — so it is not even a tie: the excess is positive
definite, every eigenvalue at least `2 − 3/√5 > 0`. -/
theorem icosaDesign_strictly_dominates :
    (subsetSum icosaDesign {0, 2, 4} - 1).PosDef := by
  refine Matrix.posDef_iff_dotProduct_mulVec.mpr ⟨?_, fun vecArg hne => ?_⟩
  · exact ((Matrix.posSemidef_sum ({0, 2, 4} : Finset (Fin 6)) fun c _ =>
      posSemidef_atomMatrix (icosaDesign.atom c)).1).sub Matrix.isHermitian_one
  · have hnormPos : (0 : ℝ) < vecArg ⬝ᵥ vecArg := by
      obtain ⟨badIndex, hbadRaw⟩ := Function.ne_iff.mp hne
      have hbad : vecArg badIndex ≠ 0 := by simpa using hbadRaw
      exact Finset.sum_pos' (fun i _ => mul_self_nonneg (vecArg i))
        ⟨badIndex, Finset.mem_univ _,
          lt_of_le_of_ne (mul_self_nonneg _) (Ne.symm (mul_ne_zero hbad hbad))⟩
    rw [star_trivial, icosaDesign_excess_form]
    nlinarith [sq_nonneg (vecArg 0 + vecArg 1 + vecArg 2), icosaRadius_pos,
      icosaRadius_upper, hnormPos]

/-- **The margin floor**: every Rayleigh value of the excess is at least
`(2 − 3/√5)·|x|²`. -/
theorem icosaDesign_rayleigh_floor (vecArg : Fin 3 → ℝ) :
    (2 - icosaRadius) * (vecArg ⬝ᵥ vecArg)
      ≤ vecArg ⬝ᵥ ((subsetSum icosaDesign {0, 2, 4} - 1) *ᵥ vecArg) := by
  rw [icosaDesign_excess_form]
  nlinarith [sq_nonneg (vecArg 0 + vecArg 1 + vecArg 2), icosaRadius_pos]

/-- **The floor is attained**, at the direction `(1,−1,0)` of squared length `2`
where the circulant's all-ones part vanishes. Together with
`icosaDesign_rayleigh_floor` this pins the margin of the maximal real equiangular
design to EXACTLY `2 − 3/√5`. -/
theorem icosaDesign_rayleigh_attained :
    (![1, -1, 0] : Fin 3 → ℝ)
        ⬝ᵥ ((subsetSum icosaDesign {0, 2, 4} - 1) *ᵥ ![1, -1, 0])
      = 2 * (2 - icosaRadius) := by
  rw [icosaDesign_excess_form]
  simp [dotProduct, Fin.sum_univ_three]
  ring

/-- **The real margin, pinned to a rational window**: `1/2 < 2 − 3/√5 < 2/3`. The
mirror of `complex_sic_slack_window`, which pins the ℂ-side violation into
`(−1/6, −1/10)`. The two sides sit on opposite sides of zero and NEITHER is
marginal: the ℂ witness undershoots by more than `1/10`, the maximal real
equiangular design overshoots by more than `1/2`. Rational certificates only —
`45 < 56.25` below, `400 < 405` above. -/
theorem icosa_margin_window :
    1 / 2 < 2 - icosaRadius ∧ 2 - icosaRadius < 2 / 3 := by
  refine ⟨?_, ?_⟩
  · nlinarith [icosaRadius_sq, icosaRadius_pos]
  · nlinarith [icosaRadius_sq, icosaRadius_pos]

/-- **The headline of the equiangular lane.** There is a weighted `(6,3)` design
whose six atoms are pairwise-distinct EQUIANGULAR lines in `ℝ³` — the real maximum,
`6`, exactly attained — and which has a strictly dominating `3`-subset. So the
`6`-vs-`9` equiangular gap cannot be the obstruction at `(6,3)`: the real ceiling
is a comfortable dominator, and any argument reaching for Lemmens–Seidel at rank
three is reaching for an inert fact. -/
theorem exists_maximal_equiangular_design_strictly_dominating :
    ∃ D : WeightedDesign 6 3,
      IsEquiangularAt D.atom (1 / 5)
      ∧ (∀ first second : Fin 6, first ≠ second →
          ¬ SpansSameLine (D.atom first) (D.atom second))
      ∧ ∃ C : Finset (Fin 6), C.card = 3 ∧ (subsetSum D C - 1).PosDef :=
  ⟨icosaDesign, icosaAtom_isEquiangular,
    fun _ _ hne => icosaAtom_distinct_lines hne,
    ⟨{0, 2, 4}, by decide, icosaDesign_strictly_dominates⟩⟩

/-! ## The shipped `(6,3)` complex witness is five lines, not nine

The equiangular hypothesis reads the `(6,3)` complex failure as "nine equiangular
lines in `ℂ³`". The actual witness is not that. Its two spikes are antipodal —
one line, not two — and each spike is orthogonal to each of the four flat atoms,
so three different squared cosines occur and the family is not equiangular. -/

/-- The two spikes of the padded SIC span the SAME line: `√10·e₂` and `−√10·e₂`. -/
theorem paddedAtom_spikes_share_a_line :
    ComplexSpansSameLine (paddedAtom 4) (paddedAtom 5) := by
  rw [ComplexSpansSameLine, paddedAtom_spike_four, paddedAtom_spike_five]
  simp only [dotProduct, Fin.sum_univ_three, Pi.star_apply, RCLike.star_def,
    Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons,
    Matrix.cons_val_two, Matrix.tail_cons, map_zero, map_neg, spikeAmpC_conj]
  ring

/-- The spike-pair overlap product is `100 = 10·10`: full Cauchy–Schwarz equality. -/
theorem paddedAtom_spike_cross :
    (star (paddedAtom 4) ⬝ᵥ paddedAtom 5) * (star (paddedAtom 5) ⬝ᵥ paddedAtom 4)
      = 100 := by
  rw [paddedAtom_spike_four, paddedAtom_spike_five]
  simp only [dotProduct, Fin.sum_univ_three, Pi.star_apply, RCLike.star_def,
    Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons,
    Matrix.cons_val_two, Matrix.tail_cons, map_zero, map_neg, spikeAmpC_conj]
  linear_combination (spikeAmpC * spikeAmpC + 10) * spikeAmpC_sq

theorem paddedAtom_spike_four_leverage :
    star (paddedAtom 4) ⬝ᵥ paddedAtom 4 = 10 := by
  rw [paddedAtom_spike_four]
  simp only [dotProduct, Fin.sum_univ_three, Pi.star_apply, RCLike.star_def,
    Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons,
    Matrix.cons_val_two, Matrix.tail_cons, map_zero, spikeAmpC_conj]
  linear_combination spikeAmpC_sq

theorem paddedAtom_spike_five_leverage :
    star (paddedAtom 5) ⬝ᵥ paddedAtom 5 = 10 := by
  rw [paddedAtom_spike_five]
  simp only [dotProduct, Fin.sum_univ_three, Pi.star_apply, RCLike.star_def,
    Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons,
    Matrix.cons_val_two, Matrix.tail_cons, map_zero, map_neg, spikeAmpC_conj]
  linear_combination spikeAmpC_sq

/-- A flat atom and a spike are orthogonal — the third coordinate of a flat atom is
zero and the first two of a spike are. -/
theorem paddedAtom_flat_spike_orthogonal :
    star (paddedAtom 0) ⬝ᵥ paddedAtom 4 = 0 := by
  rw [paddedAtom_spike_four, show paddedAtom 0 = extendFlat (scaledSic 0) from rfl]
  simp only [dotProduct, Fin.sum_univ_three, Pi.star_apply, RCLike.star_def,
    extendFlat, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons,
    Matrix.cons_val_two, Matrix.tail_cons, map_zero, mul_zero, zero_mul, add_zero]

theorem paddedAtom_spike_flat_orthogonal :
    star (paddedAtom 4) ⬝ᵥ paddedAtom 0 = 0 := by
  rw [paddedAtom_spike_four, show paddedAtom 0 = extendFlat (scaledSic 0) from rfl]
  simp only [dotProduct, Fin.sum_univ_three, Pi.star_apply, RCLike.star_def,
    extendFlat, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons,
    Matrix.cons_val_two, Matrix.tail_cons, map_zero, mul_zero, zero_mul, add_zero]

/-- **The `(6,3)` complex witness is NOT equiangular.** The spike pair sits at
squared cosine `1` while a spike and a flat atom sit at `0`: two different values,
so no single `cosSqValue` serves. In particular the witness is not nine equiangular
lines in `ℂ³` — it is the `ℂ²` SIC plus one orthogonal line. -/
theorem paddedAtom_not_equiangular :
    ¬ ∃ cosSqValue : ℂ, ComplexIsEquiangularAt paddedAtom cosSqValue := by
  rintro ⟨cosSqValue, hequi⟩
  have hspikes := hequi 4 5 (by decide)
  have hmixed := hequi 0 4 (by decide)
  have hflatNorm : star (paddedAtom 0) ⬝ᵥ paddedAtom 0 = 20 / 9 := by
    have hplane := scaledSic_norm 0
    rw [show paddedAtom 0 = extendFlat (scaledSic 0) from rfl]
    simp only [dotProduct, Fin.sum_univ_three, Fin.sum_univ_two, Pi.star_apply,
      RCLike.star_def, extendFlat, Matrix.cons_val_zero, Matrix.cons_val_one,
      Matrix.head_cons, Matrix.cons_val_two, Matrix.tail_cons, map_zero, mul_zero,
      add_zero] at hplane ⊢
    exact hplane
  rw [paddedAtom_spike_cross, paddedAtom_spike_four_leverage,
    paddedAtom_spike_five_leverage] at hspikes
  rw [paddedAtom_flat_spike_orthogonal, paddedAtom_spike_flat_orthogonal, hflatNorm,
    paddedAtom_spike_four_leverage] at hmixed
  have hcosOne : cosSqValue = 1 := by linear_combination (-(1 : ℂ) / 100) * hspikes
  have hcosZero : cosSqValue = 0 := by
    linear_combination (-(9 : ℂ) / 200) * hmixed
  rw [hcosOne] at hcosZero
  norm_num at hcosZero

/-! ## The Bargmann triangle certificate

`T = ⟨a,b⟩⟨b,c⟩⟨c,a⟩` is the smallest gauge-invariant functional of a
configuration that sees the ground field at all: rescaling any atom by a unit
phase leaves it fixed, and over `ℝ` it is a product of three reals. Every real
family passes; both complex witnesses fail as badly as possible, with `T` purely
imaginary. -/

/-- The complexification of a real vector. -/
def complexify {k : ℕ} (realVec : Fin k → ℝ) : Fin k → ℂ := fun i => (realVec i : ℂ)

theorem starDot_complexify {k : ℕ} (leftVec rightVec : Fin k → ℝ) :
    star (complexify leftVec) ⬝ᵥ complexify rightVec
      = ((leftVec ⬝ᵥ rightVec : ℝ) : ℂ) := by
  simp only [dotProduct, complexify, Pi.star_apply, RCLike.star_def,
    Complex.conj_ofReal, Complex.ofReal_sum, Complex.ofReal_mul]

/-- The Bargmann triangle invariant of three complex atoms. -/
def triangleBargmann {k : ℕ} (firstVec secondVec thirdVec : Fin k → ℂ) : ℂ :=
  (star firstVec ⬝ᵥ secondVec) * (star secondVec ⬝ᵥ thirdVec)
    * (star thirdVec ⬝ᵥ firstVec)

/-- A complex family passes the realness certificate when every triangle invariant
is real. -/
def HasRealTriangleBargmann {m k : ℕ} (vec : Fin m → (Fin k → ℂ)) : Prop :=
  ∀ firstIdx secondIdx thirdIdx : Fin m,
    (triangleBargmann (vec firstIdx) (vec secondIdx) (vec thirdIdx)).im = 0

/-- **The real-side content, as a `ring` identity**: over `ℝ` the triangle
invariant is EXTREMAL — its square is exactly the product of the three squared
overlaps, with no phase left over. Over `ℂ` only `(Re T)² ≤ |T|²` holds, and that
gap is where realness lives. -/
theorem realTriangle_bargmann_extremal {k : ℕ}
    (firstVec secondVec thirdVec : Fin k → ℝ) :
    ((firstVec ⬝ᵥ secondVec) * (secondVec ⬝ᵥ thirdVec) * (thirdVec ⬝ᵥ firstVec)) ^ 2
      = (firstVec ⬝ᵥ secondVec) ^ 2
        * ((secondVec ⬝ᵥ thirdVec) ^ 2 * (thirdVec ⬝ᵥ firstVec) ^ 2) := by
  ring

/-- **Clause (i), for free.** Every real family passes the certificate — no
hypothesis on the vectors, no design condition, nothing to discharge. -/
theorem realFamily_hasRealTriangleBargmann {m k : ℕ} (vec : Fin m → (Fin k → ℝ)) :
    HasRealTriangleBargmann (fun c => complexify (vec c)) := by
  intro firstIdx secondIdx thirdIdx
  rw [triangleBargmann, starDot_complexify, starDot_complexify, starDot_complexify,
    ← Complex.ofReal_mul, ← Complex.ofReal_mul]
  exact Complex.ofReal_im _

/-! ### The complex witnesses fail, maximally -/

theorem omegaRoot_re : omegaRoot.re = -(1 / 2) := rfl

theorem omegaRoot_im : omegaRoot.im = Real.sqrt 3 / 2 := rfl

/-- The cube of the SIC's common side overlap, reduced by the cube-root relations
alone: `(2/3 + (4/3)ω)³ = −8/9 − (16/9)ω`. No real/imaginary extraction is needed —
this is `linear_combination` over `1 + ω + ω² = 0` and `ω³ = 1`. -/
theorem sicCube_value : ((2 : ℂ) / 3 + 4 / 3 * omegaRoot) ^ 3
    = ((-8 / 9 : ℝ) : ℂ) - ((16 / 9 : ℝ) : ℂ) * omegaRoot := by
  push_cast
  linear_combination (64 / 27 : ℂ) * omegaRoot_cube + (32 / 9 : ℂ) * omegaRoot_sum

theorem sicCube_re : (((2 : ℂ) / 3 + 4 / 3 * omegaRoot) ^ 3).re = 0 := by
  rw [sicCube_value, Complex.sub_re, Complex.ofReal_re, Complex.mul_re,
    Complex.ofReal_re, Complex.ofReal_im, omegaRoot_re, omegaRoot_im]
  ring

theorem sicCube_im : (((2 : ℂ) / 3 + 4 / 3 * omegaRoot) ^ 3).im
    = -(8 * Real.sqrt 3 / 9) := by
  rw [sicCube_value, Complex.sub_im, Complex.ofReal_im, Complex.mul_im,
    Complex.ofReal_re, Complex.ofReal_im, omegaRoot_re, omegaRoot_im]
  ring

/-- The SIC's triangle `{1,2,3}` has invariant `(2/3 + (4/3)ω)³`. -/
theorem sicBargmann_value :
    triangleBargmann (sicAtom 1) (sicAtom 2) (sicAtom 3)
      = ((2 : ℂ) / 3 + 4 / 3 * omegaRoot) ^ 3 := by
  rw [triangleBargmann, sicOv_one_two, sicOv_two_three, sicOv_three_one]
  ring

/-- **The SIC's triangle invariant is PURELY IMAGINARY**: real part `0`, imaginary
part `−8√3/9`. Every real family has a real invariant, so this is the maximal
possible deviation — the squared real part is `0` while `|T|² = (4/3)³ = 64/27`. -/
theorem sicBargmann_re :
    (triangleBargmann (sicAtom 1) (sicAtom 2) (sicAtom 3)).re = 0 := by
  rw [sicBargmann_value]
  exact sicCube_re

theorem sicBargmann_im :
    (triangleBargmann (sicAtom 1) (sicAtom 2) (sicAtom 3)).im
      = -(8 * Real.sqrt 3 / 9) := by
  rw [sicBargmann_value]
  exact sicCube_im

/-- **The `(4,2)` complex witness fails the realness certificate.** -/
theorem sicAtom_not_hasRealTriangleBargmann : ¬ HasRealTriangleBargmann sicAtom := by
  intro hall
  have hzero := hall 1 2 3
  rw [sicBargmann_im] at hzero
  have hsqrtPos : (0 : ℝ) < Real.sqrt 3 := Real.sqrt_pos.mpr (by norm_num)
  linarith

/-! ### The padded `(6,3)` witness, the binding object -/

theorem starDot_extendFlat (leftPlane rightPlane : Fin 2 → ℂ) :
    star (extendFlat leftPlane) ⬝ᵥ extendFlat rightPlane
      = star leftPlane ⬝ᵥ rightPlane := by
  simp only [dotProduct, Fin.sum_univ_three, Fin.sum_univ_two, Pi.star_apply,
    RCLike.star_def, extendFlat, Matrix.cons_val_zero, Matrix.cons_val_one,
    Matrix.head_cons, Matrix.cons_val_two, Matrix.tail_cons, map_zero, mul_zero,
    add_zero]

theorem starDot_scaledSic (firstIdx secondIdx : Fin 4) :
    star (scaledSic firstIdx) ⬝ᵥ scaledSic secondIdx
      = (10 / 9 : ℂ) * (star (sicAtom firstIdx) ⬝ᵥ sicAtom secondIdx) := by
  have hpull : star (scaledSic firstIdx) ⬝ᵥ scaledSic secondIdx
      = scaleAmpC * scaleAmpC * (star (sicAtom firstIdx) ⬝ᵥ sicAtom secondIdx) := by
    simp only [scaledSic, star_smul, smul_dotProduct, dotProduct_smul, smul_eq_mul,
      RCLike.star_def, scaleAmpC_conj]
    ring
  rw [hpull, scaleAmpC_sq]

/-- The padded witness's flat triangle `{1,2,3}` carries the SIC invariant scaled
by `(10/9)³ = 1000/729`. -/
theorem paddedBargmann_value :
    triangleBargmann (paddedAtom 1) (paddedAtom 2) (paddedAtom 3)
      = ((1000 / 729 : ℝ) : ℂ) * ((2 : ℂ) / 3 + 4 / 3 * omegaRoot) ^ 3 := by
  rw [triangleBargmann,
    show paddedAtom 1 = extendFlat (scaledSic 1) from rfl,
    show paddedAtom 2 = extendFlat (scaledSic 2) from rfl,
    show paddedAtom 3 = extendFlat (scaledSic 3) from rfl,
    starDot_extendFlat, starDot_extendFlat, starDot_extendFlat,
    starDot_scaledSic, starDot_scaledSic, starDot_scaledSic,
    sicOv_one_two, sicOv_two_three, sicOv_three_one]
  push_cast
  ring

/-- **The binding `(6,3)` complex witness fails the realness certificate too**, and
by exactly the same mechanism: its flat triangle's Bargmann invariant is purely
imaginary, `−8000√3/6561`. -/
theorem paddedBargmann_im :
    (triangleBargmann (paddedAtom 1) (paddedAtom 2) (paddedAtom 3)).im
      = -(8000 * Real.sqrt 3 / 6561) := by
  rw [paddedBargmann_value, Complex.mul_im, Complex.ofReal_re, Complex.ofReal_im,
    sicCube_im, sicCube_re]
  ring

theorem paddedAtom_not_hasRealTriangleBargmann :
    ¬ HasRealTriangleBargmann paddedAtom := by
  intro hall
  have hzero := hall 1 2 3
  rw [paddedBargmann_im] at hzero
  have hsqrtPos : (0 : ℝ) < Real.sqrt 3 := Real.sqrt_pos.mpr (by norm_num)
  linarith

/-- **The realness gate in explicit form.** One property, `HasRealTriangleBargmann`:
free for every real family (no hypotheses at all) and violated by BOTH complex
refutations — the `(4,2)` SIC and the binding `(6,3)` padded SIC. It quantifies
over no subset and mentions no eigenvalue, so it is not a rename of domination.

The honest ceiling, stated as a caveat and consumed by nothing below: over an
overlap support whose cycle space is generated by triangles, "every triangle
invariant is real" is the standard gauge criterion for a Gram matrix to be
diagonally equivalent to a real one, so the property looks equivalent to REALNESS
and strengthening it to "…therefore some `k`-subset dominates" would be
`GtzWeighted 6 3` itself. Every strictly weaker variant tested in the realness-first
workflow was refuted: "SOME triangle is real-extremal" holds for the Hesse `(9,3)`
SIC, which carries twelve real-extremal triangles and still admits no dominating
triple. -/
theorem realness_gate_separates :
    (∀ m k : ℕ, ∀ vec : Fin m → (Fin k → ℝ),
        HasRealTriangleBargmann (fun c => complexify (vec c)))
      ∧ ¬ HasRealTriangleBargmann sicAtom
      ∧ ¬ HasRealTriangleBargmann paddedAtom :=
  ⟨fun _ _ vec => realFamily_hasRealTriangleBargmann vec,
    sicAtom_not_hasRealTriangleBargmann, paddedAtom_not_hasRealTriangleBargmann⟩

end Gtz
